govuk-one-login/di-account-management-frontend

ci/terraform/account-management-client.tf

Set subject id to public
Fixes issue with logging in.

Set subject identiifer for AM to public

---

.github/workflows/pre-merge-checks.yml
docker-compose.yml
src/locales/en/translation.json

Currently, the session duration is set to 1800sec (30mins). We need to change it to 3600sec (60mins).

Session time from 30 mins to 60 mins

---

src/components/change-email/change-email-controller.ts
src/components/change-email/change-email-service.ts
src/components/change-email/types.ts
src/components/change-password/change-password-controller.ts
src/components/change-password/change-password-service.ts
src/components/change-password/types.ts
src/components/change-phone-number/change-phone-number-controller.ts
src/components/change-phone-number/change-phone-number-service.ts
src/components/change-phone-number/types.ts
src/components/check-your-email/check-your-email-controller.ts
src/components/check-your-email/check-your-email-service.ts
src/components/check-your-email/types.ts
src/components/check-your-phone/check-your-phone-controller.ts
src/components/check-your-phone/check-your-phone-service.ts
src/components/check-your-phone/types.ts
src/components/delete-account/delete-account-controller.ts
src/components/delete-account/delete-account-service.ts
src/components/delete-account/types.ts
src/components/enter-password/enter-password-controller.ts
src/components/enter-password/enter-password-service.ts
src/components/enter-password/types.ts
src/utils/http.ts

Push clientIp to backend
Needed for auditing

GOVSI-829: Send missing data to frontend

---

ci/tasks/deploy-account-management.yml
ci/tasks/terraform-taint.yml

- Parameterise the hard-coded state bucket, this will be different for production
We are preparing to deploy a production environment

GOVSI-822: Update Terraform tasks with configurable state bucket

---

src/components/change-password/tests/change-password-integration.test.ts
src/components/check-your-email/tests/check-your-email-integration.test.ts
src/components/common/layout/base.njk
src/components/delete-account/index.njk
src/components/delete-account/tests/delete-account-integration.test.ts
src/components/enter-password/index.njk
src/components/manage-your-account/index.njk
src/components/update-confirmation/index.njk
src/components/update-confirmation/update-confirmation-controller.ts
src/locales/cy/translation.json
src/locales/en/translation.json

- added missing back buttons
- updated delete account page content
- added missing sign out links
To align with figma

Update content to match figma

---

src/components/delete-account/delete-account-controller.ts

Fix method name for error object.

Fix method name for error

---

.github/workflows/pre-merge-checks.yml
Dockerfile
package.json
src/app.constants.ts
src/app.ts
src/components/change-password/tests/change-password-integration.test.ts
src/components/oidc-callback/call-back-controller.ts
src/components/oidc-callback/tests/callback-controller.test.ts
src/components/start/start-controller.ts
src/components/start/tests/start-controller.test.ts

Check vot value in id token to see if user authenticated at the right level.
So users can't login to AM without doing 2fa.

Check vot value in ID token is right level

---

.github/workflows/pre-merge-checks.yml
Dockerfile
package.json
src/components/check-your-email/check-your-email-controller.ts
src/components/delete-account/delete-account-controller.ts

Upgrade node to next LTS version.
To use an LTS version of node.

Upgrade node to next LTS version

---

package.json
yarn.lock

Update yarn lock and package for node types

---

.github/workflows/pre-merge-checks-terraform.yml

- Add terraform github action
- As we have terraform within this repo

BAU - Add terraform github action

---

src/app.ts
src/components/oidc-callback/call-back-controller.ts
src/components/oidc-callback/tests/callback-controller.test.ts
src/components/start/start-controller.ts
src/middleware/set-local-vars-middleware.ts
src/utils/http.ts

Add support for _ga query param to be passed on redirects.
For performance team.

Add support for _ga parameter

---

sonar-project.properties
src/app.ts
src/middleware/auth-middleware.ts
src/utils/state-machine.ts

Fixed sonar code smells

---

README.md

Update docs with how to run the app locally
There are some additional steps to follow now

BAU: update docs with how to run the app locally

---

src/components/common/layout/base.njk
src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Fix broken feedback link to point to auth support form.

Fix feedback link

---

src/config.ts

Add prefix to url

---

package.json
src/assets/javascript/application.js
src/assets/javascript/showPassword.js
src/components/change-password/index.njk
src/components/common/layout/base.njk
src/components/common/show-password/macro.njk
src/components/enter-password/_change-email.njk
src/components/enter-password/_change-password.njk
src/components/enter-password/_change-phone-number.njk
src/components/enter-password/_delete-account.njk
src/components/enter-password/index.njk

For consistency add the show password feature on all password inputs.

Implement show password

---

src/components/common/layout/base.njk

Add block end

---

src/assets/scss/application.scss
src/components/enter-password/index.njk

Add missing styles and script for show password.

Add missing styles and script

---

src/assets/javascript/cookies.js
src/components/common/layout/base-menu.njk
src/components/oidc-callback/call-back-controller.ts
src/middleware/set-local-vars-middleware.ts

Add ga linker to generate cross domain tracking value.
To avoid using gov.uk accounts value as this expires after 2 minutes causing issues in tracking.

Add GA linker for cross domain tracking

---

sandpit-push.sh

Add the sandpit push script for account management.
The script was in frontend but not account management.

BAU: add the sandpit push script for account management

---

package.json
src/app.ts
src/components/delete-account/tests/delete-account-integration.test.ts
src/config.ts
src/config/aws.ts
src/config/cf.ts
src/config/oidc.ts
src/config/session.ts
src/types.ts
yarn.lock

Remove paas redis specific code after fargate migration.

Remove paas redis code

---

ci/terraform/build.tfvars
ci/terraform/integration.tfvars
ci/terraform/variables.tf

ECS rollout config tweaks to all environments.
Rollout to build and integration was successful.
#454

AUT-212: ecs rollout config tweaks to all environments

---

ci/terraform/build.tfvars

Switch on account management auto scaling in build.
Gradual rollout of auto scaling, testing in build.
#461

AUT-213: switch on account management auto scaling in build

---

package.json
yarn.lock

Update design system

---

src/components/common/layout/banner.njk

Update cookie banner with correct content and formatting

Update cookie banner with correct content and formatting

---

Dockerfile
local.Dockerfile
package.json

Optimise docker images.
- Do not deploy dev dependencies
- Change file ownership to node in target image
- Add image digests
https://github.com/alphagov/di-authentication-frontend/pull/609

AUT-354: Optimise docker images

---

deploy-sandpit.sh

- Fixes to the `deploy-sandpit.sh` to ensure correct behaviour
- Skip ECS wait if Terraform destroy was requested.
The deploy wasn't working correctly due to incorrect image name and variable name (caused by copy/paste).
When destroying Terraform infrastructure there is no need to have the "wait for ECS" step as the ECS tasks will no longer exist.

AUT-434: Fixes to deploy-sandpit.sh

---

src/components/change-password/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

- Update password quality text
- Ensure the user knows the restrictions on passwords before they change their password
- It is important to provide users with information prior to error handling, to help them clearly understand what the specific requirements are for entering data.

AUT-461 - Update password quality text

---

src/components/manage-your-account/manage-your-account-controller.ts
src/components/manage-your-account/tests/manage-your-account-controller.test.ts

- Fix typo that snuck through
- Add test to capture any changes for the future
- Otherwise phone number will not be displayed in Account Management

AUT-35 - Fix typo that snuck through

---

CODEOWNERS

Does exactly what it says on the tin

BAU: Allow the accounts team to approve PRs

---

ci/tasks/deploy-account-management.yml
ci/terraform/build.tfvars
ci/terraform/cloudwatch.tf
ci/terraform/integration.tfvars
ci/terraform/production.tfvars
ci/terraform/sandpit.tfvars
ci/terraform/variables.tf

Migrating to new CSLS endpoint

BAU: Publish logs to multiple CSLS endpoints

---

ci/terraform/production.tfvars

Reverts alphagov/di-authentication-account-management#641

Revert "DCP-88: Enable Welsh language in production"

---

docs/adr/0001-record-adrs.md

Start recording relevant changes for this application in a `docs/adr` repo and explain why.
https://github.com/alphagov/di-account-management-backend/pull/31

GUA-477: Start recording ADRs locally

---

docs/adr/0001-record-adrs.md
docs/adr/0002-move-to-secure-pipelines.md

⚠️ Merge https://github.com/alphagov/di-authentication-account-management/pull/652 first ⚠️ 
Describe the plan to take over the application, and changes that arise as a consequence
We'd not actually documented this anywhere
https://github.com/alphagov/di-authentication-account-management/pull/652

BAU GOV.UK Account team take over app

---

deploy/samconfig.toml
deploy/template.yaml

Implemented WAF on Fargate which was achieved by connecting our WAF to HTTP API Gateway via a CloudFront Distribution.
To act as an additional layer of security on the Accounts Management Front-end Application.
Relates to the following PR which defines related resources outside of the eu-west-2 region (either Regional CloudFront or us-east-1 resources to enable CloudFront distribution)
https://github.com/alphagov/di-accounts-infra/pull/10

ATB-63 Implemented WAF on Fargate

---

src/components/delete-account/delete-account-controller.ts
src/components/delete-account/tests/delete-account-controller.test.ts

Reverts alphagov/di-authentication-account-management#673
- Reverting this PR as although this fixes the 500, it causes another issue when the user attempts to click the sign in link again.

Revert "AUT-879 - Delete all sessions when account is deleted"

---

.env.sample

There was a typo in the .env.sample and a few missing values.

BAU: Make .env.sample more accurate

---

src/components/delete-account/delete-account-controller.ts
src/components/delete-account/tests/delete-account-controller.test.ts

Reverts alphagov/di-authentication-account-management#684

Revert "Revert "AUT-879 - Delete all sessions when account is deleted""

---

README.md

Add instructions to the readme for how to deploy to the dev environment

BAU: Add instructions to deploy to the dev environment

---

.gitignore
ci/terraform/alb.tf
ci/terraform/redirect-lambda.tf
ci/terraform/sandpit.tfvars
ci/terraform/shared.tf
ci/terraform/variables.tf
deploy-sandpit.sh
redirect.js

- Create a redirect lambda that does an HTTP redirect to a configured URL plus sets the required HSTS headers (this required for HSTS preload)
- Terraform an IAM role for the lambda
- Terraform the function
- Update sandpit deployment to test
We need to redirect from old AM domain to new AM domain.

AUT-895: Create a redirection lambda function

---

ci/tasks/deploy-account-management.yml

- Need to include state bucket variable in deployment task
Missed from previous PR
#696

AUT-895: Add missing pipeline update

---

ci/tasks/deploy-account-management.yml

Fix Terraform deployment task for redirect lambda
- Add `redirect_lambda_zip` Terraform variable to deploy task
Deployment pipeline is failing

AUT-895: Fix deployment task

---

.github/workflows/build-test-application.yml
.github/workflows/cd-only.yml
.github/workflows/validate-docker-image.yml
.github/workflows/validate-sam-template.yml
README.md

ATB-125: Enable Branch deploys

---

src/components/common/layout/navigation.njk

Updated navigation to point to "/your-services". 
Will need an update to point to "/" root with redirects.

GUA-462-update the navigation to point to /your-services

---

src/app.constants.ts
src/app.ts
src/components/enter-password/enter-password-controller.ts
src/components/enter-password/tests/enter-password-controller.test.ts
src/components/manage-your-account/manage-your-account-routes.ts
src/components/manage-your-account/tests/manage-your-account-integration.test.ts
src/components/oidc-callback/call-back-controller.ts
src/components/oidc-callback/tests/callback-controller.test.ts
src/components/redirects/redirects-routes.ts
src/middleware/validate-state-middleware.ts

Add Redirects to the account space

GUA-462 Redirects

---

src/locales/cy/translation.json
src/locales/en/translation.json

- Update Client registry for gov.uk publishing on integration

GUA-462: update the client id for gov.uk

---

src/config.ts

Add gov.uk integration value to allow list.

GUA-462: Add gov.uk integration value to the allow list

---

deploy/template.yaml

Added additional access log variables for the AMF API Gateway:
- requestId
- requestTime
- httpMethod
- domainName
- path
- routeKey
- protocol
- status
- responseLength
- responseLatency
- integrationStatus
- integrationLatency
- integrationErrorMessage
- errorMessage
- errorResponseType
To have a better view of access logs for the AMF API Gateway
- [ATB-169](https://govukverify.atlassian.net/browse/ATB-169)
N/A
[ATB-169]: https://govukverify.atlassian.net/browse/ATB-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ATB-169 Add additional access logs for API Gateway

---

src/locales/cy/translation.json
src/locales/en/translation.json

Update the publishing service url in integration

GUA-462 : Update the publishing service url in integration

---

package-lock.json
src/app.constants.ts
src/app.ts
src/components/change-email/change-email-controller.ts
src/components/change-email/tests/change-email-controller.test.ts
src/components/change-email/tests/change-email-service.test.ts
src/components/change-email/types.ts
src/components/change-password/tests/change-password-controller.test.ts
src/components/change-password/tests/change-password-service.test.ts
src/components/change-phone-number/tests/change-phone-number-service.test.ts
src/components/check-your-email/tests/check-your-email-service.test.ts
src/components/check-your-phone/tests/check-your-phone-service.test.ts
src/components/enter-password/tests/enter-password-service.test.ts
src/components/manage-your-account/tests/manage-your-account-integration.test.ts
src/components/oidc-callback/tests/callback-controller.test.ts
src/components/resend-email-code/resend-email-code-controller.ts

GUA-550: Improving test coverage on the service .
- Additions of more tests around services
- Improving the coverage for line which are not covered currently by test in the controller. 
This change was made to improve quality of tests .
- [GUA-550](https://govukverify.atlassian.net/browse/GUA-550)
[GUA-550]: https://govukverify.atlassian.net/browse/GUA-550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GUA: 550 improve test coverage

---

src/components/change-email/tests/change-email-integration.test.ts
src/components/change-password/tests/change-password-integration.test.ts
src/components/change-phone-number/tests/change-phone-number-integration.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

- [ATB-XXX](https://govukverify.atlassian.net/browse/ATB-XXX)

GUA-523: Update content to support One Login name change 

---

deploy/template.yaml

Provided the default value for Environment parameter
[ATB-230] Adding default environment as dev to the environment parameters`
Added 'dev' as default environment to the environment parameters of the template.yaml
To assign a default environment in the AMF template.
- [ATB-230](https://govukverify.atlassian.net/jira/software/c/projects/ATB/boards/241?modal=detail&selectedIssue=ATB-230&assignee=635679e1fc0cc7a600ae36d5)
[ATB-230]: https://govukverify.atlassian.net/browse/ATB-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATB-230]: https://govukverify.atlassian.net/browse/ATB-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ATB-230 adding default environment as dev to the environment parameters 

---

deploy/template.yaml

[ATB-145] Investigating the effects of CachedMethods when removed.
Removed CachedMethods and tested in the pipelines.
Removed CachedMethods as not required. No 502s exhibited when tested.
Not required and to avoid caching of user information.
- [ATB-145](https://govukverify.atlassian.net/jira/software/c/projects/ATB/boards/241?modal=detail&selectedIssue=ATB-145&assignee=635679e1fc0cc7a600ae36d5)
[ATB-145]: https://govukverify.atlassian.net/browse/ATB-145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATB-145]: https://govukverify.atlassian.net/browse/ATB-145?atlOrigin=eyJpIjoiN
Evidence of Tests Passing: [ATB-145.pdf](https://github.com/alphagov/di-authentication-account-management/files/10662377/ATB-145.pdf) …

ATB-145 Investigating effects of cachedMethods

---

src/assets/javascript/application.js

[ATB-206] Update the Syntax of window.addEventListener
Removed the use of the output from 'onIntNumberSelected' to remove the code smell in SonarCloud. 
Changed the syntax for triggering the window.addEventListener so that an output is not returned, and the code smell is removed in sonarcloud.
It was altered so that the output that doesn't return something was removed.
If a function does not return anything, it makes no sense to use its output. Specifically, passing it to another function, or assigning its "result" to a variable is probably a bug because such functions return undefined, which is probably not what was intended.
Remove this use of the output from "onIntNumberSelected"; "onIntNumberSelected" doesn't return anything.
- …

ATB-206 Update the Syntax of window.addEventListener

---

src/assets/javascript/application.js
src/components/delete-account/delete-account-controller.ts

Removed the duplication of ../../config as it was not needed
Deleted the additional ../config and added the same reference in the original config line.
Unnecessary duplication
- [ATB-215](https://govukverify.atlassian.net/jira/software/c/projects/ATB/boards/241?modal=detail&selectedIssue=ATB-215&assignee=635679e1fc0cc7a600ae36d5)
[ATB-215]: https://govukverify.atlassian.net/browse/ATB-215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATB-215]: https://govukverify.atlassian.net/browse/ATB-215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ATB-215: Removed duplication of ../../config

---

src/components/check-your-phone/check-your-phone-controller.ts
src/components/check-your-phone/check-your-phone-service.ts
src/components/check-your-phone/tests/check-your-phone-service.test.ts
src/components/check-your-phone/types.ts
src/utils/types.ts

Currently the checkYourPhoneService Interface describes an async function that takes in 8 parameters. This is flagged as a code smell as the cognitive complexity is too high (max number of parameters is 7). This PR changes the interface definition so that the method signature only requires 2 parameters
The CheckYourPhoneServiceInterface was updated so to take 2 objects as its parameters. Those objects represent the user's input (email, updated info, and otp code) and session details respectively. The way this information is accessed when forming the post request to the relevant API was also changed in line with this restructuring
Aim is to reduce cognitive complexity of the method
- [ATB-217](https://govukverify.atlassian.net/jira/software/c/projects/ATB/boards/241?modal=detail&selectedIss …

[ATB-217] Reduce cognitive complexity in checkYourPhoneService method

---

src/components/check-your-email/check-your-email-controller.ts
src/components/check-your-email/check-your-email-service.ts
src/components/check-your-email/tests/check-your-email-service.test.ts
src/components/check-your-email/types.ts
src/utils/types.ts

Currently the checkYourEmailService Interface describes an async function that takes in 8 parameters. This is flagged as a code smell as the cognitive complexity is too high (max number of parameters is 7). This PR changes the interface definition so that the method signature only requires 2 parameters
The CheckYourEmailServiceInterface was updated so to take 2 objects as its parameters. Those objects represent the user's input (email, updated info, and otp code) and session details respectively. The way this information is accessed when forming the post request to the relevant API was also changed in line with this restructuring
Aim is to reduce cognitive complexity of the method
- [ATB-216](https://govukverify.atlassian.net/jira/software/c/projects/ATB/boards/241?modal=detail&selectedIss …

[ATB-216] Reduce cognitive complexity in checkYourEmailService method

---

src/components/check-your-email/check-your-email-controller.ts
src/components/check-your-phone/check-your-phone-controller.ts

Changes made to check-your-email/phone controller ts file. This bag was introduced when making changes for tickets ATB-216 and ATB-217 as the way the authorisation token was access was changed. 
Accessing authorisation token from tokens field in user's session in the right way
Fixing issue introduced with merging of ATB-216 and ATB-217
- [ATB-304](https://govukverify.atlassian.net/browse/ATB-304)
[ATB-304]: https://govukverify.atlassian.net/browse/ATB-304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ATB-203: Unable to change mobileNumber or emailAddress

---

SECURITY.md
src/app.constants.ts
src/components/redirects/redirects-routes.ts
src/components/redirects/tests/redirects-integration.test.ts

Rainy day clear up ticket,
We should follow best pratices of the [GDS way](https://gds-way.cloudapps.digital/standards/vulnerability-disclosure.html#vulnerability-disclosure), and also do sensible things to help the wonderful world of internet security folk help us keep our services and users safe.

GUA-547 security.txt

---

.github/workflows/cd-only.yml

Configure pipeline to tag images with gitRef commit SHA
Pipeline was not picking up front-end changes as the ECR image being published was being tagged with the .github/workflows commit SHA, meaning if this already existed in our ECR repo, the new image would be skipped over.
- Branch ATB-305 | Branch name |  ATB-305-test  (https://github.com/alphagov/di-account-management-frontend/actions/runs/4185992979)
- Branch ATB-305 | Commit SHA |  31016dbcb23d981f938b2508669c6ebea74c52c9 (https://github.com/alphagov/di-account-management-frontend/actions/runs/4186057332)
- Branch ATB-305 | Tag | v199
Unable to test this scenario as the latest GitHub Repo tag is [v199](https://github.com/alphagov/di-account-management-frontend/releases/tag/v199) which is a commit from Feb 2022 which does not …

ATB-305 Configure pipeline to tag images with gitRef commit SHA

---

.github/workflows/main.yml

BAU: Make Publish Image & Template depend on previous step

---

src/components/your-services/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

https://govukverify.atlassian.net/browse/GUA-660
Add "Sign your mortgage deed" to the list of services on the account information box.
**DO NOT MERGE** before 8am on Monday 27th Feb which is when the service should be going live.
[Figma for reference](https://www.figma.com/file/0JbNRTnq5ibRtfg8BMxXDL/Accounts-design-thinking?node-id=1252%3A13237&t=86knNaxy6x8Yht8k-0)

[DO NOT MERGE] GUA-660: Add Sign your mortgage deed to blurb

---

package-lock.json
src/components/delete-account/delete-account-controller.ts
src/components/delete-account/index.njk
src/components/delete-account/tests/delete-account-controller.test.ts
src/components/delete-account/tests/delete-account-integration.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/utils/yourServices.ts
test/unit/utils/yourServices.test.ts
yarn.lock

Reverts alphagov/di-account-management-fronten
d#843
Reverting due to a bug

Revert "GUA - 593 Customise delete screen"

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Add ofqual to list of services on the services page and on the account blurb.
Welsh translation TBC
https://govukverify.atlassian.net/browse/GUA-694

GUA-694: Add Ofqual to list of services

---

src/components/delete-account/delete-account-controller.ts
src/components/delete-account/index.njk
src/components/delete-account/tests/delete-account-controller.test.ts
src/components/delete-account/tests/delete-account-integration.test.ts
src/locales/en/translation.json
src/utils/yourServices.ts
test/unit/utils/yourServices.test.ts

Fix for a bug on the customise delete screen .

GUA - 593 customise delete screen fix

---

LICENCE

[GUA-584] add MIT licence information
[GUA-584]: https://govukverify.atlassian.net/browse/GUA-584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GUA-584 add MIT licence information

---

src/components/your-services/index.njk
src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Add Modern slavery statement to the list of services on the account dashboard.
Add Welsh translation for Modern registry and Ofqual.

GUA-695: add Modern slavery statement registry

---

src/locales/cy/translation.json
src/locales/en/translation.json

Missing Header for Mortgage Deed.

Add missing header for mortgage deed

---

deploy/template.yaml

Update Publishing API URL to point to the correct protocol.

Update Publishing APi URL with the protocol

---

src/components/check-your-email/check-your-email-controller.ts
src/components/delete-account/delete-account-controller.ts

[GUA-670] send publicSubjectID to GOV.UK publishing not subjectID
[GUA-670]: https://govukverify.atlassian.net/browse/GUA-670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GUA-670 send publicSubjectID to GOV.UK publishing not subjectID

---

src/components/security/security-controller.ts

Phone number might not exist, we can't perform slice on undefined.
Which is leading to errors.

FIX: Phone number is not guarenteed to exist

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Apprenticeship service is onboarding on July 13th. 
This adds it to the locale files, services allow list and the list of services we display in the information box on the account.
https://govukverify.atlassian.net/browse/DOT-51
https://govukverify.atlassian.net/browse/OLH-932
Following the steps in [Adding a New client](https://docs.google.com/document/d/1qMUACpf4IuaMGEQzPFSA6ZoIkgbwMMuVk2E9qKHj1PQ/edit).
Recorded demo posted [here](https://gds.slack.com/archives/C01H13E9YP8/p1689094331301769).

OLH-932: Add apprenticeship service

---

deploy/template.yaml

Add the `https://` prefix to the imported parameter for the Account Management API stub.
This parameter is the exported domain name for the stub, but it doesn't include the protocol which the app is expecting.
This is only going to the build environment, which is where I need to test this.

OLH-875: Add protocol to stub URL

---

src/locales/cy/translation.json
src/locales/en/translation.json

Update the order in which services are presented on the your services page blurb section. 
The list should be in alphabetical order .

BAU : Update the order of the services 

---

.github/workflows/sonarcloud.yml

Update the Sonar Github action to the latest version. This commit SHA points to version v2.0.0 of the Sonar action which is the most recent release (see https://github.com/SonarSource/sonarcloud-github-action/releases/tag/v2.0.0).
We've been getting warnings that the version we were on before was using Java 11 which is very out of date (Java 17 is the current release).
This is the same change as in https://github.com/alphagov/di-account-management-backend/pull/131

BAU: Update Sonar to the latest action version

---

.github/workflows/build-test-application.yml

Update the step name in the action to remove the reference to the Node version we're using.
We're no longer using Node 16 - see #990.
This means we won't need to update this again for future upgrades.
Note this doesn't change which version of Node we're using to run any tests; it's only the step name that appears in the action logs.
#990

BAU: Update action step name

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Onboard the 'Find and apply for a grant' service following [the documentation](https://docs.google.com/document/d/1qMUACpf4IuaMGEQzPFSA6ZoIkgbwMMuVk2E9qKHj1PQ/edit).
They're going live tomorrow
This work is also tracked on [DOT-252](https://govukverify.atlassian.net/browse/DOT-252)
I've run this locally following the process in the Google doc. 
Please check the URLs and text against those on the DOT Jira ticket
[DOT-252]: https://govukverify.atlassian.net/browse/DOT-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1075: Onboard 'Find and apply for a grant' service

---

src/locales/cy/translation.json
src/locales/en/translation.json

Update the link for the 'Clain criminal injuries compensation' service. 
To use the preferred GOV.UK start page link instead of going directly from the service

BAU: Update link to CCIC

---

src/components/contact-govuk-one-login/index.njk

Correct the text for the reference code
There was a typo here which meant we repeated the content from the section above instead of displaying the content for the reference code.
Before: 
After:
Verify this against the prototype (link on the [Jira epic](https://govukverify.atlassian.net/browse/OLH-1018))

BAU: Correct the text for the reference code

---

.env.sample
deploy/template.yaml

Update triage page to a new value which has been given by Gwyn.  see comment on https://govukverify.atlassian.net/browse/OLH-1151
locally it's grand. Will be tested through to triage page in the integration environment

update triage page url

---

src/locales/cy/translation.json
src/locales/en/translation.json

OLH-1145 - Fix link to sign your mortgage deed service
The url has been corrected.
The old url was incorrect and led to a page stating the service was unavailable.
Built and tested locally.

Fix link to sign your mortgate deed.

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

[OLH-1161] PR Onboard RP: UKMCAB
Added English and Welsh content to the client registry
Deployed to dev, added the service into my user-services in dynamo and I can see the card displayed.  Screenshot uploaded as a comment
[OLH-1161]: https://govukverify.atlassian.net/browse/OLH-1161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1161 Onboard RP: UKMCAB

---

src/app.ts
src/assets/scss/application.scss
src/components/common/layout/base.njk
src/components/common/layout/languageToggle.njk
src/components/contact-govuk-one-login/contact-govuk-one-login-controller.ts
src/components/contact-govuk-one-login/index.njk
src/components/contact-govuk-one-login/tests/contact-govuk-one-login-controller.test.ts
src/config/nunjucks.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/types.ts
test/unit/config/nunjucks.test.ts
tsconfig.json

[OLH-1117] Add a Welsh language toggle to the triage page to allow users to easily switch languages.
Tested locally switching between languages by clicking on the links
Tested by landing on the page without any links
Tested by having parameters already in the URL
[OLH-1117]: https://govukverify.atlassian.net/browse/OLH-1117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1117 Build welsh language toggle

---

deploy/template.yaml

🚨 🚨 **Do not merge this PR until we've had confirmation that the contact centre is open** 🚨 🚨 
Turn on the feature flag for phone support in production only.
Putting this PR up now so we can get it approved and ready to go for tomorrow morning.

OLH-1199: Enable phone support in production

---

src/components/common/layout/base.njk

Update the beta banner feedback link. 
The link is added to base.njk.
This takes users directly to the section of the contact form for giving feedback. We don’t want users to go to the triage page because we don’t want them to use the other channels for giving feedback.
Tested in DEV.  The link works as expected opening the new feedback page in a new tab.  Observed that the back link on the new page does not work.
Its currently deployed in DEV so can be reviewed there.

OLH-1194 - Update beta banner feedback link

---

docker-compose.yml
localstack/provision.sh
src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

OLH-1203 Adding Connect Families card
OLH-1205 Manage family hubs
Usual update to add card and reworking of the provision script for docker compose.
New service being added.  Changes to docker compose to make the DynamoDB updates easier to read.
Check details on ticket have been added correctly.  Deploy to dev and ask UCD to review.

OLH-1203 - Connect family hubs home service card

---

.github/workflows/on-manual-publish-to-dev.yml
.github/workflows/validate-docker-image-dev.yml
Dockerfile
deploy/template.yaml

Add the Dynatrace agent to the frontend container and ship metrics.
Update the pipeline configuration to allow the Dynatrace agent deployed in the frontend container to ship metrics.
Update the Docker build to include the agent on the image.
Added a GitHub secret for the Dynatrace token. 
Update the SAM deployment configuration to allow the Dynatrace agent to be run correctly in all environments.
To allow metrics to be shipped to Dynatrace.
Data can be seen in Dynatrace for the dev environment.
When deployed in dev data from interactions with the Account Home page can be seen in Dynatrace.
The process to add Dynatrace is documented in this README https://github.com/govuk-one-login/observability-infrastructure/tree/main/fargate.
You also need to know about this …

OLH-11214 - Add Dynatrace sidecar to frontend container.

---

.github/workflows/on-merge-to-main.yml

Add details of Dynatrace ECR registry to github action that calls di-devplatform-upload-action-ecr.
The parameter list for the call to di-devplatform-upload-action-ecr now includes details of the Dynatrace repo.
The di-devplatform-upload-action-ecr github action rebuild the Docker image so it needs to pull an image from the Dynatrace repo.
Can only be tested when the change is merged to main.
Desk check.

OLH-1214 - Add dynatrace repo to call to di-devplatform-upload-action-ecr

---

.github/workflows/on-merge-to-main.yml

Update di-devplatform-upload-action-ecr.
New pinned version of di-devplatform-upload-action-ecr.
We need the latest version of the GitHub action to support use of the DynaTrace registry.
When merging to main.

OLH-1214 - Update version of di-devplatform-upload-action-ecr.

---

.github/workflows/on-merge-to-main.yml

Retreive di-devplatform-upload-action-ecr from govuk-onelogin
GitHib workflow now references the action from govuk-onelogin.
Couldn't resolve the correct version of the action using alphagov.
When merging to main.

OLH-1214 - Retrieve di-devplatform-upload-action-ecr from govuk-onelogin

---

package-lock.json
package.json
src/utils/logger.ts

Rename the application package to match the repository name
We renamed this repository ages ago but missed the Node package name. This hasn't mattered at all up until now, but we've just onboarded onto Dynatrace and it's picking up the service name from this app's package name.
This has the potential to be confusing when people from outside our team are looking at Dynatrace and trying to figure out who to contact if there's an incident.

BAU: Rename application

---

src/locales/cy/translation.json
src/locales/en/translation.json

The opening hours for the email route have changed now that it is managed by the supplier rather than our in house team. This updates the information on the contact page to the most up to date one. The hours changed on the 12th December so this update is overdue.
https://govukverify.atlassian.net/browse/OLH-1312  
The information is no longer up to date
Please check that the new content matches the content on the ticket

OLH-1312: update contact page email section

---

src/components/contact-govuk-one-login/index.njk

https://govukverify.atlassian.net/browse/OLH-1303 
When the webchat window is opened by clicking on "Use webchat" on the `/contact-gov-uk-one-login` page, shift focus programmatically to the webchat iframe.
This is an accessibility fix ahead of the upcoming DAC audit. 
Testing this fix unveiled other problems to do with focus on the webchat widget, but after discussing it with the accessibility specialist, some of the issues are for the supplier to fix while others would be good to explore but they can be done as part of another ticket. So in the end this ticket is concerned solely with moving focus to the iframe when "Use webchat" is clicked.
Because not shifting the focus is an accessibility and usability issue. It means that keyboard users have to tab through the entire contents of the …

OLH-1303: Shift focus to webchat window when launched via "Use webchat"

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Add AAS to available services.
Config updated.
To allow the new service to be accessed from the services list and to present a service card when the service has been visited previously.

OLH-1292 Onboard AAS.

---

deploy/template.yaml

Remove tha additional Condition checking the environment is production.
The SAM template was updated.
Additional condition is not needed or used.

BAU - remove additional isProd check from the SAM template.

---

deploy/template.yaml

ADR-0140 records the preferred way to scale a Fargate application and will be followed by Account Home.
A new step scaling policy has been added.
See the ADR for details.
[ADR-0140](https://github.com/govuk-one-login/architecture/blob/main/adr/0140-fargate-scaling.md)
Tested deployment to dev.
Desk check.

OLH-1339 - Implement step scaling policy.

---

deploy/template.yaml

Revert "OLH-1339 - Implement step scaling policy."

---

deploy/template.yaml

Remove autoscaling.
Remove the autoscaling for ECS.
To allow a new auto scaling configuration to be applied.
Deployed to dev after deploying main build.

OLH-1339 - Remove existing auto scaling config to allow new auto scaling config to be deployed.

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Add APAR to available services.
Config updated.
To allow the new service to be accessed from the services list and to present a service card when the service has been visited previously.
Currently deployed to dev or can be run locally.

OLH-1291 Onboard APAR (Provider and Assessment Register Service).

---

src/locales/cy/translation.json
src/locales/en/translation.json

Improve content on AAS service card.
English and Welsh text for service description updated.
Improvemnt.

OLH-1358 Improve content on aas service card.

---

deploy/template.yaml

Use UAT webchat in integration
Our supplier has completed their testing of the dev version of webchat and have promoted the changes to UAT.
We need to switch over to UAT for the upcoming ITHC

OLH-1440: Use UAT webchat in integration

---

src/components/activity-history/activity-history-controller.ts
src/components/report-suspicious-activity/report-suspicious-activity-controller.ts
src/utils/activityHistory.ts
src/utils/decrypt-data.ts
test/unit/utils/activityHistory.test.ts

Fix issue seen in dev where the Report suspicious activity page was not rendering correctly.
Add additional decryption when rendering the Report suspicious activity page.
Refactor to add consistency of names.
Added some additional debug logging to clearly show when the decryption is failing.
Implement required functionality of the report suspicious activity feature.
Tested in dev and locally.

Olh 1545 report suspicious activity

---

src/components/activity-history/activity-history-controller.ts
src/components/activity-history/index.njk
src/components/activity-history/tests/activity-history-controller.test.ts
src/components/common/activity-history/event.njk
src/components/common/layout/base.njk
src/components/report-suspicious-activity/index.njk
src/components/report-suspicious-activity/report-suspicious-activity-controller.ts
src/components/report-suspicious-activity/success.njk
src/locales/cy/translation.json
src/locales/en/translation.json

https://govukverify.atlassian.net/browse/OLH-1540 
Here is [the Figma](https://www.figma.com/file/0JbNRTnq5ibRtfg8BMxXDL/One-Login-Home---Design-thinking?type=design&node-id=1859-18169&mode=design) plus a summary of the notes from UCD:
Security page
- add a navigation panel for activity history to the Security page
Activity history page
- “back” button should go to Security
- “change your password” link should go to Security
- the chronologically first item in all activity logs should be the note about the date One Login started recording activity history
- each page in the history should only contain 10 entries and then paginate
Activity history log entries
- service names should be h2s but styled as h3s
- service names should be in sentence case
- events about One Login home are called …

OLH-1540: design updates on activity history and report suspicious activity

---

src/app.constants.ts
src/components/activity-history/activity-history-routes.ts
src/components/activity-history/tests/activity-history-integration.test.ts
src/components/report-suspicious-activity/report-suspicious-activity-routes.ts
src/config.ts
src/locales/en/translation.json
src/middleware/check-allowed-services-list.ts

Add additional RPs to the activity history allow list.
Updated the constants file to include a new allow list for RSA.
Introduced some constants for the RP client ids.
For go live of the RSA feature we want a selection of RPs users to be able to acces it.

OLH-1561 Add initial tranche of RPs to RSA allow list.

---

deploy/template.yaml

Release the activity log to integration.
So we can start preparing for end-to-end tests.

OLH-1582: Release the activity log to integration

---

src/components/security/security-controller.ts
src/components/security/tests/security-controller.test.ts
src/components/security/tests/security-integration.test.ts

Update the check in the security controller to look for any of the services on our allowlist, not just the HMRC ones. 
We missed this in #1192.

OLH-1582: Check against all allowed services for activity history

---

src/config.ts

Only allow HMRC and our stub services to access the activity log and report suspicious activity feature.
The RSA allow list.
To limit access to the activity log and report suspicious activity feature while logistics between teams supporting this feature are agreed,

OLH-1586 - RPs for scaled back relase of RSA.

---

src/components/report-suspicious-activity/index.njk
src/components/report-suspicious-activity/success.njk

Remove contact us route from RSA
Page and email definitions.
We can't support contact follow for RSA.
Can be deployed to dev for a UCD review.
The updated templates require logging into Notify with the correct privs.  I also have copies that I sent to myself.

OLH-1599 Update report suspicious activity content to remove contact route

---

.github/workflows/build-test-application.yml
deploy/template.yaml
docker-compose.yml
localstack/provision.sh
package.json
src/config/aws.ts
src/utils/read-envs.ts

Re-instate the alarms for report suspicious activity.
Added alarms for report suspicious activity.
Enabled all alarms in dev.
Upgrade to v3 of localstack.
Broke provision.sh down into functions.
Alarms needed to support report suspicious activity.
Upgrade to localstack to support imporved local testing.
Introduced functions to provision.sh as it is getting quite large.

OLH-1587 Add alarms for report suspicous activity.

---

deploy/template.yaml

Switch on suspicious activity in production.
Feature flag for production set to on.
Ready for report suspicious activity launch.

OLH-1570 report suspicious activity go live.

---

deploy/template.yaml
src/components/security/security-controller.ts
src/components/security/security-routes.ts
src/middleware/mfa-method-middleware.ts
src/middleware/mfa-methods-legacy.ts
src/utils/mfa/index.ts
test/unit/middleware/mfa-method-middleware.test.ts

[OLH-1669] Add MFA URL to deployment template
Added new environment variable for the method management URL
It was missed from the previous commit
https://govukverify.atlassian.net/browse/OLH-1621
Deployed and tested in dev
It can be tested locally by setting
METHOD_MANAGEMENT_BASE_URL=https://method-management-v1-stub.home.dev.account.gov.uk
SUPPORT_METHOD_MANAGEMENT=1
[OLH-1669]: https://govukverify.atlassian.net/browse/OLH-1669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1669 Add MFA URL to deployment template

---

src/components/common/layout/base.njk
src/components/contact-govuk-one-login/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

1. [Update page title on contact triage page](https://github.com/govuk-one-login/di-account-management-frontend/commit/1616b5245c15c406fb44e2da7745e49529098054) 
The title of this page is currently being re-worded in google search results: from "Contact GOV.UK One Login - GOV.UK One Login" to "Contact GOV.UK One Login - Sign in".
This might be happening because Google thinks that the title is "keyword stuffed" due to the repetition of the OL product name. Our content team have suggested removing the trailing "- GOV.UK One Login" on this page to help mitigate the problem.
The product name should remain for all other page titles. It should only be removed on the contact triage page for now.
2. [Add meta description on the triage page](https://github.com/govuk-one-login/di-account-management- …

OLH-1241: Contact triage page metadata updates

---

docs/adr/0005-csrf-prevention.md
src/app.ts
src/components/change-email/tests/change-email-integration.test.ts
src/components/change-password/tests/change-password-integration.test.ts
src/components/change-phone-number/tests/change-phone-number-integration.test.ts
src/components/check-your-email/tests/check-your-email-integration.test.ts
src/components/check-your-phone/tests/check-your-phone-integration.test.ts
src/components/delete-account/tests/delete-account-controller.test.ts
src/components/delete-account/tests/delete-account-integration.test.ts
src/components/enter-password/tests/enter-password-integration.test.ts
src/components/resend-email-code/tests/resend-email-code-integration.test.ts
src/components/resend-phone-code/tests/resend-phone-code-integration.test.ts
src/handlers/csrf-error-handler.ts
test/utils/behaviours.ts

Add a handler for CSRF failures which have been observed in production.
A new handler to deal with CSRF validation failures.  When a CSRF validation occurs the error is caught by the new handler, logged and the user is re-directed back to their Your Services page.  There are a number of integration tests that check this behaviour and they been altered to use a new test method that describes the expected behaviour when CSRF validation fails.
The order that error handlers were added in the main app file was inconsistent with the docs so I re-ordered them to remove any future confusion.
The new handler will remove the 403 error that was being detected by DynaTrace.
The existing integration tests were found to have an error in them that prevented individual scenarios being run.
I have tested …

OLH-1678 - forbidden error.

---

deploy/template.yaml

Set GA and UA environment variables for staging and integration.
Updated the SAM template.
The env vars need to be set in all envs, staging and integration were missed.

OLH-1516 - Add GA4. Update to latest version of one-login-analytics.

---

deploy/template.yaml

Switch back to UAT webchat in integration
We've finished our testing of the production chat client now, so we can load the UAT client in integration again.

OLH-1697: Use UAT webchat in integration

---

deploy/template.yaml

Update Cloudfront to add the TICF header to requests.
Added the Cloudfront function defined by the platform team to our frontend deployment.
The header will be added to the events we send to TxMA to assist in fraud analysis.
This will only work in dev and staging initially to allow the overall functionality to be tested before switching it on in production.  To test in dev I added some temporary code to the Your services controller that logged all the headers from the request. I could see the new header `txma-audit-encoded` being logged.

OLH-1736 - Call new header function from cloudfront.

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

OLH-1649 - Onboard RP: DfE Find and Use an API
Create a new entry in translation file for all environments
Add to allowed services config
So that a new RP can be onboarded.
https://govukverify.atlassian.net/browse/DOT-656
Deploy to dev environment and test

OLH-1649 Onboard RP: DfE Find and Use an API

---

deploy/template.yaml

Set up analytics in staging, update the container IDs in production and disable GA4 in production as we suspect there amy be a domain clash.
Currently neither GA4 nor UA is working in production.
See the [Slack conversation](https://gds.slack.com/archives/C04M9TM70DV/p1714570979047699) about this 
Please check the container IDs against the ones Sam provided on Slack

BAU: Debug Google Analytics

---

src/app.constants.ts
src/components/check-your-phone/check-your-phone-controller.ts
src/components/check-your-phone/check-your-phone-routes.ts
src/components/check-your-phone/check-your-phone-service.ts
src/components/check-your-phone/tests/check-your-phone-controller.test.ts
src/components/check-your-phone/tests/check-your-phone-integration.test.ts
src/components/check-your-phone/tests/check-your-phone-service.test.ts
src/components/check-your-phone/types.ts
src/components/security/security-routes.ts
src/middleware/mfa-method-middleware.ts
src/utils/mfa/index.ts
src/utils/test/mfa-test.ts
src/utils/types.ts

OLH-1744 - Call the method management API to update a user's phone number
[OLH-1744](https://govukverify.atlassian.net/browse/OLH-1744)
Feature switched implementation to point to 
So that One Login Home can call the new method management API when a user updates their phone number.
Unit and Integration Test
Deploy to dev with feature flag off, ensure all works
Deploy to dev with feature flag on, ensure all works.
Code completeness and quality
[OLH-1744]: https://govukverify.atlassian.net/browse/OLH-1744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1744 - Call the method management API to update a user's phone number

---

.github/workflows/on-merge-to-main.yml

updating devplatform-upload-action to v3.8.1

updating devplatform-upload-action to v3.8.1

---

src/locales/cy/translation.json

This section on the contact triage page has English version of the text in the Welsh locale file. Replace this with the Welsh
So we show users the correct language.

OLH-1799: Add missing translation

---

deploy/template.yaml

We need the toggle to be on in these environments for testing.

Enable welsh toggle in integration and staging

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

WIP.  There are questions about the logged in service link and the welsh translation to be answered before this PR can be completed.
Onboard Welsh Fisheries Permit Service
Added new service details to the English and Welsh localisation files.
Welsh Fisheries Service is due to onboard in May.

OLH-1648 - onboard Wales fisheries permit service.

---

deploy/template.yaml

**DO NOT MERGE** until Thursday 6th June at 10am

[DO NOT MERGE]: Enable Welsh language toggle on all environments

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

OLH-1376 - Onboard RP: Immigration Advice Authority [prev: OISC]
Update translations files and config file
So that a service card can be created for OISC on one login home
https://govukverify.atlassian.net/browse/OLH-1376
Deployed to test and do a UCD Review

OLH-1376 - Onboard RP: Immigration Advice Authority [prev: OISC]

---

.github/workflows/on-merge-to-main.yml

Reverts govuk-one-login/di-account-management-frontend#1422

Revert "OLH-1717 Set node version and index for main to merge action"

---

src/locales/cy/translation.json
src/locales/en/translation.json

OLH-1878 - Adjust RP: Immigration Advice Authority
Update RP info as per latest provided here: https://govukverify.atlassian.net/browse/OLH-1878
To ensure RP information matches the latest info the RP provided.
https://govukverify.atlassian.net/browse/OLH-1878
Deploy to dev and get a UCD review

OLH-1878 - Adjust RP: Immigration Advice Authority

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Add "Visit someone in prison" to the RP allowlist in the config, and the translation files.
This RP is due to onboard on Monday 24th.
https://govukverify.atlassian.net/browse/DOT-682
https://govukverify.atlassian.net/browse/OLH-1880
Tested locally using the provision script:
Check that the content matches the specification and test that the service card is showing up, either deploying it to dev or testing locally with the provision script.

OLH-1880: Onboard Visit someone in prison service

---

src/components/oidc-callback/call-back-controller.ts

OLH-1828 - Migrate to AWS SDK 3
Remove logging that can contain PII
The code to update to aws sdk 3 was previously merged to main with some logging to diagnose in case of unexpected errors.
Post testing in staging, we are removing the logs as it can contain PII before allowing the changes in prod environment.
https://github.com/govuk-one-login/di-account-management-frontend/pull/1479
Deploy to dev and test.

OLH-1828 - Remove logging aimed at diagnosing in case of error in staging.

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

This adds the service card for "Driving with a medical condition". This service will be under "Other services you've used".
https://govukverify.atlassian.net/browse/OLH-1975
https://github.com/govuk-one-login/di-account-management-backend/pull/297
I tested locally using the provision script
https://github.com/user-attachments/assets/c4f6b5d1-f40b-48d4-8c00-01f3c8b434d1

OLH-1975: Driving with a medical condition RP

---

Dockerfile
deploy/template.yaml

[OLH-1893] Enabled Canary Deployment for Frontend Repo
Template Changes:
- Migrated from External Deployment type to ECS to Code Deploy
- Added configuration to enable canary deployment
- Enabled HealthChecks on containers 
- Removed unused variables and resources in the cloud formation template
- Ensured there are no cfn-lint errors
- Added additional tags to resources
Other Changes:
- Added curl to image
- Fixed a bug with LOCAL_KEY_ID when it wasn't present
Inline with Canary Deployment initiative
Deployed to Dev
- Double check removed resources are not required
[OLH-1893]: https://govukverify.atlassian.net/browse/OLH-1893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1893-set-up-canary-deployments-for-the-frontend-deploy-pipeline

---

@types/express/index.d.ts
src/app.constants.ts
src/app.ts
src/components/change-default-method/change-default-method-controller.ts
src/components/change-default-method/change-default-method-routes.ts
src/components/change-default-method/index.njk
src/components/change-default-method/tests/change-default-method-controller.test.ts
src/components/common/confirmation-page/confirmation.njk
src/components/enter-password/enter-password-controller.ts
src/components/security/index.njk
src/components/update-confirmation/update-confirmation-controller.ts
src/components/update-confirmation/update-confirmation-routes.ts
src/locales/en/translation.json
src/utils/mfa/index.ts
src/utils/state-machine.ts

- Add flow to allow users to change their default MFA method
To support the required functionality

OLH-1941 Allow users to change their default MFA method

---

src/components/change-email/change-email-routes.ts
src/components/change-password/change-password-routes.ts
src/components/check-your-email/check-your-email-routes.ts

Please see [JIRA ticket](https://govukverify.atlassian.net/browse/OLH-1999)

OLH-1999 Validate State

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

OLH-1963 - Onboard RP: Use (& View) an LPA
Update Locale files to include the new RP
Onboarding the use and view a lasting power of attorney RP
Deploy to dev and sign off by UCD.

OLH-1963 - Onboard RP: Use (& View) an LPA

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Add service card for the PDP connect account.
The service is supposed to onboard on 5th August (initially in private beta)
https://govukverify.atlassian.net/browse/OLH-2002
Tested manually using the provision script and checking against the translations provided by the onboarding team.

OLH-2002: Onboard PDP connect RP

---

deploy/template.yaml

[OLH-2043] Stage 1 - Deploy ECS Canary Stack 
CF requires task definition to deploy ECS Canary Stack otherwise it fails. Another deployment is required post this to enable canary deployment.
Failed deployment in production and integration due to missing resources. 
https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3821732161/ECS+-+Canary+Deployments+Migration+Guidance#Step-6%3A-Deploy-newly-added-resources
N/A - CF will fail to deploy if this causes issues.

OLH-2043-stage-1-canary-deployment-for-production-integration

---

deploy/template.yaml

[OLH-2044] Enable Canary Deployment in Production + Integration
Following stage 1 which deployed necessary resources, this will actually enable Canary Deployment's in the environment. 
Enablement of canary deployment unexpectedly required 2 stage commit. This is the part 2.
https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3821732161/ECS+-+Canary+Deployments+Migration+Guidance#Step-6%3A-Deploy-newly-added-resources

OLH-2044-stage-2-canary-deployment-for-production-integration

---

src/locales/cy/translation.json
src/locales/en/translation.json

[OLH-1965] Rework ATE capital schemes
Updated Card text in english and welsh.
Updated by service.
[OLH-1965]: https://govukverify.atlassian.net/browse/OLH-1965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1965-rework-rp-ate-capital-schemes-pb

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

[OLH-2111] Onboard RP DFE Claim additional Payments for Teaching
Addition of onboarding parameters.
https://govukverify.atlassian.net/browse/DIOT-394
Content review by Mel, deployed to Dev.
[OLH-2111]: https://govukverify.atlassian.net/browse/OLH-2111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2111-onboard-rp-df-e-claim-additional-payments-for-teaching

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

OLH-2118 - Onboard RP: Companies House - Accounts
Add translation definitions for new service card for company house accounts
So that service cards can be produced correctly for company house accounts users
Deploy to dev and get UCD review
Design updates should be signed off by a UCD person prior to the PR being open for dev review

OLH-2118 - Onboard RP: Companies House - Accounts

---

src/locales/cy/translation.json
src/locales/en/translation.json

[OLH-2152] Update companies house signed in state url
Replaced link href due to request from companies house
Requested to change link.
Deployed to dev and verified link works as expected
[OLH-2152]: https://govukverify.atlassian.net/browse/OLH-2152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updated sign in state url for companies house

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

OLH-2150 - Add Welsh translations for DWP's integration clients
https://govukverify.atlassian.net/browse/OLH-2150
Update existing integration translations to include welsh and added new lower environment integrations for the same services.
So that DWP can end to end test their one login service card in welsh language
Deploy to dev and test presence of card.

OLH-2150 - Add Welsh translations for DWP's integration clients

---

localstack/provision.sh
src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Add the details for the "Confirm my apprenticeship details" service
https://govukverify.atlassian.net/browse/OLH-2169
Tested locally using provision script.

OLH-2169: Add service card for CMAD service

---

.github/PULL_REQUEST_TEMPLATE.md

Update PR template with a reminder to obtain approval for any new dependencies. Only once approved can we use the library in our product.
It is rare that there is a need to add a new dependency.
So when we do need to add one, we might forget that there is an approval process. 
The approval process exists to ensure new dependencies meet certain [criteria](https://github.com/govuk-one-login/architecture/blob/main/adr/0037-nodejs-npm-production-dependencies.md#approval-of-dependencies). 
https://github.com/govuk-one-login/architecture/blob/main/adr/0037-nodejs-npm-production-dependencies.md#approval-of-dependencies
https://govukverify.atlassian.net/wiki/spaces/DIWAY/pages/4335697997/Library+approval+process

BAU: Add library approval to list of signoffs

---

deploy/template.yaml

[OLH-2216] Adjust scaling policy to follow ADR 0140
To follow fargate performance improvement guide.
https://github.com/govuk-one-login/architecture/blob/913c04af8b57e2cdce07c4b242a409690852d527/rfc/0083-express-on-ecs.md 
[
](https://github.com/govuk-one-login/architecture/blob/913c04af8b57e2cdce07c4b242a409690852d527/rfc/0083-express-on-ecs.md)
Tested in Dev
[OLH-2216]: https://govukverify.atlassian.net/browse/OLH-2216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adjust scaling policy to follow ADR 0140

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

OLH-2119 - Onboard RP: DWP - Repay and manage benefit money you owe (production client)
https://govukverify.atlassian.net/browse/OLH-2119
Add new RP to translation files
Include RP as part of configuration
Onboard DWP 
Deploy to dev environment and get UCD sign-off.
[ ] Design updates have been signed off by a member of the UCD team
UCD team to check the change in the dev environment and approve the change.

OLH-2119 - Onboard RP: DWP - Repay and manage benefit money you owe (production client)

---

src/utils/strings.ts

[OLH-2250] Reverted Async changes in OLH-2232
Reverted changes made in OLH-2232
Prod incident
[OLH-2250]: https://govukverify.atlassian.net/browse/OLH-2250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

reverted OLH-2232

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

[OLH-2120] Onboard RP Ofgem Local Authority Flexibility eligibility
Onboarded RP
Deployed to Dev
[OLH-2120]: https://govukverify.atlassian.net/browse/OLH-2120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2120-onboard-rp-ofgem-la-flexible-eligibility

---

src/locales/cy/translation.json
src/locales/en/translation.json

OLH-2297 - Repay my debt: revert one more non-production client service card URL
https://govukverify.atlassian.net/browse/OLH-2297
Fix incorrect URL for service
As its a non dev service id, can test post merge to main in integration environment
Confirm only change to URL and matches value in ticket.

OLH-2297 - Repay my debt: revert one more non-production client service

---

.env.sample
deploy/template.yaml
src/app.constants.ts
src/app.ts
src/assets/scss/application.scss
src/components/search-services/index.njk
src/components/search-services/search-services-controller.ts
src/components/search-services/search-services-routes.ts
src/components/search-services/tests/search-services-controller.test.ts
src/config.ts
src/locales/en/translation.json

- Add a new route and controller for the searchable list
- Hide it behind a feature flag
- Set new feature flag environment variable
- Show a list of services in the list
So that we have a place to build out the functionality

OLH-2308 Add routes and controllers for searchable list

---

deploy/template.yaml

- Add the SUPPORTSEARCHABLELIST parameter to the template in integration
It was missing, which caused the deploy to fail on int

Add missing environment variable:

---

deploy/template.yaml

Adjust evaluation period for API gateway 4xx Alarm
Reduced false alarms by api 4xx alarm
alarm was triggering due to bot traffic causing 404s

Adjust evaluation period for API gateway 4xx Alarm

---

src/assets/scss/application.scss
src/components/search-services/index.njk
src/components/search-services/search-services-controller.ts
src/components/search-services/tests/search-services-controller.test.ts
src/config.ts
src/locales/en/translation.json

- Add a search field to the services page
- Perform basic text filtering to filter only items that the search matches
- Add tests
- Switch from using a `table` to using `li` for the search results
This is the first iteration for search.

Olh 2311 Add a basic search function to the searchable list

---

src/components/search-services/search-services-controller.ts
src/components/search-services/tests/search-services-controller.test.ts

- Sort the search results alphabetically
- Update tests to check this

OLH-2330 Sort Results Alphabetically

---

src/utils/sns.ts

sns sqs singleton

---

src/utils/kms.ts
src/utils/oidc.ts

kms singleton

---

.github/workflows/build-test-application.yml
.github/workflows/sonarcloud.yml
src/components/track-and-redirect/track-and-redirect-controller.ts
src/middleware/mfa-method-middleware.ts

[OLH-2205] URL singleton
- Moved get env var to global so it only happens once
- Minor refactor for performance
- Deployed to Dev
- Ran performance tests
[OLH-2205]: https://govukverify.atlassian.net/browse/OLH-2205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

url singleton

---

src/utils/yourServices.ts

[OLH-2205] Refactor Your Services
- Refactored Your Services page logic
- Removed initialisation of Pino
- Performance improvements
- Deployed to Dev
- Tested against performance test
[OLH-2205]: https://govukverify.atlassian.net/browse/OLH-2205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2205-performance-testing-implementation-of-overload-protection-library-causing-http-503-errors-refactor-yourservices

---

src/locales/cy/translation.json
src/locales/en/translation.json

Updates the wording for the "Apply for qualified teacher status" service 
Changes the strings for the link text in English and Welsh
Request from content

OLH-2360 Update QTS wording

---

localstack/provision.sh
src/components/activity-history/activity-history-controller.ts
src/components/activity-history/index.njk
src/components/activity-history/tests/activity-history-controller.test.ts
src/locales/en/translation.json

Adds this explinaton notes...
Since we are launching activity history without the ability to report activity as suspect.

OLH-2377 code in the content explaining what users should do if they see suspicious activity

---

.env.sample
deploy/template.yaml
src/components/contact-govuk-one-login/index.njk
src/config.ts
src/config/helmet.ts
src/middleware/set-local-vars-middleware.ts

OLH-2327 - Address outstanding security risk in CSP
Update our web chat helmet in line with the recommendations as per recommendations here: https://docs.google.com/document/d/1D36eqQA9ZaN70SJOetbl18O6voAT0BPqhIbwzVpB4EY/edit?tab=t.0#bookmark=id.q4slt233xksh
https://govukverify.atlassian.net/browse/OLH-2343
https://docs.google.com/document/d/1D36eqQA9ZaN70SJOetbl18O6voAT0BPqhIbwzVpB4EY/edit?tab=t.0#bookmark=id.q4slt233xksh
Deploy to test and ensure web chat is not broken
Review by @Ca1umA1ford or 
Confirm the generated CSP looks right

OLH-2327 - Address outstanding security risk in CSP

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

OLH-2231 Onboard RP Home Office Standard and Enhanced DBS Check

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

OLH-2386 - Onboard RP: Intellectual Property Office: Manage Intellectual property
Updated client registry to include new RP
Align Welsh and English translations by adding missing RP in welsh for non prod environments.
Onboard new RP
https://govukverify.atlassian.net/browse/OLH-2386
https://govukverify.atlassian.net/browse/DIOT-472
Deploy to dev and do UCD review

OLH-2386 - Onboard RP: Intellectual Property Office: Manage Intellectual property

---

src/locales/cy/translation.json

OLH-2386 - Change welsh signed-in link.
Change welsh signed-in link.
COnfirmed post merge to main that the link should be slightly different

OLH-2386 - Change welsh signed-in link.

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

OLH-2389 - Onboard RP: DESNZ - Heat Network Zoning
Added new RP
Onboarding RP
https://govukverify.atlassian.net/browse/OLH-2389
https://govukverify.atlassian.net/browse/DIOT-549
Deploy to dev and do a UCD review

OLH-2389 - Onboard RP: DESNZ - Heat Network Zoning

---

src/components/activity-history/activity-history-controller.ts
src/components/report-suspicious-activity/report-suspicious-activity-controller.ts
src/components/your-services/your-services-controller.ts
src/utils/activityHistory.ts
src/utils/errors.ts
src/utils/http.ts
src/utils/mfa/index.ts
src/utils/redact.ts
src/utils/referenceCode.ts
src/utils/types.ts

Apply fixes for minor and low severity code smells flagged up by sonar on the main branch.
While I was looking to find a solution that'd automatically fix the issues flagged up on sonarqube (I still haven't found anything that will apply fixed across a whole repo as opposed to when a file is opened as per the "Clean as you code" approach), I went through the repository with SonarLint on VSCode and applied some of the changes that were suggested.
I figured I might as well commit them.
This doesn't fix all the issues flagged up on sonarcloud. 
But it fixes quite a handful, so our stats should hopefully improve. 
We can log a ticket to address the remainder. Some of the outstanding issues are not quite as straightforward to address.
There are all largely syntactic and …

BAU: some sonar fixes

---

package-lock.json
package.json
src/app.ts

[OLH-2317] Upgrade to express version 5.0.1
Wildcards no longer supported, replaced santizeMiddleware with "/*splat" from "*"
Major version upgrade.
https://expressjs.com/en/guide/migrating-5.html
- Unit tests all passing
- Integration tests all passing
- Performance test results same as express 4.x.x branch
[OLH-2317]: https://govukverify.atlassian.net/browse/OLH-2317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update express package to v5.0.1

---

src/locales/cy/translation.json
src/locales/en/translation.json

OLH-2378 - Update the service card: HO - IAA Home Service Card
Update the IAA Home Service card
Update the IAA Home Service card

OLH-2378 - Update the service card: HO - IAA Home Service Card

---

src/assets/scss/application.scss
src/components/search-services/index.njk
src/locales/en/translation.json

Update style of search box to bring it more in line with the styling of similar search components in GOV (namely the GOVUK one).
Shamelessly ~stole~ adapted the GOVUK search box CSS as well as (most of) the markup, where applicable. 
Additionally, updated the style of the page overall, to closer match the latest [figma designs](https://www.figma.com/design/0JbNRTnq5ibRtfg8BMxXDL/One-Login-Home---Design-thinking?node-id=11059-3384&t=R90sI46CpjLcDc9N-0).
| Before (search query "support")  | After (search query "support") |
| ------------- | ------------- |
|![home dev account gov uk_search-services_q=support](https://github.com/user-attachments/assets/de9575d8-56fb-45f8-84c3-66d4a0b2b8eb) | ![localhost_6001_search-services_q=support](https://github.com/user-attachments/assets/a60a5e11-5477-4 …

OLH-2381: Update services search page

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

OLH-2391 - 02/25 Onboard RP: Welsh Gov - Rural Payment Wales
Add new RP Rural Payment Wales
Onboard new RP Rural Payment Wales
https://govukverify.atlassian.net/browse/OLH-2391
Deploy to dev and carry out UCD review
Signed off by a member of the UCD team

OLH-2391 - 02/25 Onboard RP: Welsh Gov - Rural Payment Wales

---

src/locales/cy/translation.json
src/locales/en/translation.json

[OLH-2393] Update URL for Find a Tender
URL Updated as RP has left private beta.
[OLH-2393]: https://govukverify.atlassian.net/browse/OLH-2393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2393: Update URL for Find a Tender

---

package-lock.json
src/utils/yourServices.ts
test/unit/utils/yourServices.test.ts

OLH-2462 Update Frontend to use Library for Activity History

---

package-lock.json
sonar-project.properties
src/config.ts

Use the client registry to generate the activity history lists (behind a feature flag)
To support migration to the client registry library

OLH-2489 Sse client registry for activity history

---

src/components/search-services/search-services-controller.ts
src/components/search-services/tests/search-services-controller.test.ts
src/config.ts
src/utils/yourServices.ts

Update the searchable list page to use the client registry library (behind a feature flag)

OLH-2463 Update search to use client library

---

package-lock.json
package.json
src/app.ts
src/config.ts
src/utils/yourServices.ts

Use the new repo name for the client registry
The avoid confusion with [The Client Registry](https://govukverify.atlassian.net/wiki/spaces/Architecture/pages/3777790146/The+client+registry)

OLH-2471 use new name for client registry repo

---

deploy/template.yaml

[OLH-2520] Create DeploymentStratergy Parameter
Added Parameter
Allows for Skip Canary to work
Follow up work will require enabling linear deployment on Production and Integration
[OLH-2520]: https://govukverify.atlassian.net/browse/OLH-2520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Created DeploymentStratergy parameter to allow sip canary

---

src/app.constants.ts

[OLH-2405] Update the url for searchable list
Updated URL
Content community recommended changing search-services to services-using-one-login 
[OLH-2405]: https://govukverify.atlassian.net/browse/OLH-2405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OLH-2405] Update the url for searchable list

---

src/app.ts

Define the static and healthcheck routes as soon as possible in `app.js`.
The order of routes and middleware in `app.js` matters. Incoming requests are matched and middleware is run in the order in which it's initialised [^1]. We need the middleware, i18n, local variables etc. to be available for requests to our application pages but we don't need any of that for the healthcheck or our static CSS & JS.
Notably this moves the static route definitions before we initialise our session store client. I'm not sure if creating the client involves a call to DynamoDB but it's still a lot of setup we don't need for static asset requests.
There are between 5 and 10 requests for static assets per page load, so reducing the amount of work we do for each of those should mean the app can handle high …

OLH-2543: Define static routes first

---

src/components/change-phone-number/tests/change-phone-number-integration.test.ts
src/components/check-your-phone/check-your-phone-controller.ts
src/components/check-your-phone/tests/check-your-phone-controller.test.ts
src/components/security/security-controller.ts
src/components/security/tests/security-controller.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

[OLH-2139] Change Phone Number Journey, update messaging and add backlinks
- Removed full stop at the end of a error message as it was not to design
- Added backlinks for the check your phone using change phone, add mfa and change default as valid intents
UCD review
[OLH-2139]: https://govukverify.atlassian.net/browse/OLH-2139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Olh 2139 ucd fixes change phone number journey journey 3

---

package-lock.json
test/unit/utils/yourServices.test.ts

Update to the latest version of the RP registry.
This marks all the English only RPs as such. See https://github.com/govuk-one-login/di-account-management-rp-registry/pull/44

OLH-2542: Update to the latest client registry

---

package-lock.json

[BAU] Update RP Registry to the latest version

Bau update rp registry

---

src/locales/en/translation.json

Fixes a small spelling mistake

Fix spelling mistake

---

src/components/check-your-phone/check-your-phone-controller.ts
src/components/check-your-phone/check-your-phone-service.ts
src/components/check-your-phone/tests/check-your-phone-controller.test.ts
src/components/check-your-phone/tests/check-your-phone-integration.test.ts
src/components/check-your-phone/tests/check-your-phone-service.test.ts
src/components/check-your-phone/types.ts
src/utils/mfa/index.ts
src/utils/mfaClient/index.ts
src/utils/mfaClient/types.ts
src/utils/mfaClient/validate.ts
test/unit/utils/mfaClient.test.ts

Use the MFA API client in all remaining journeys that go through the 'check your phone' controller. These are:
- Update your phone number on an existing method
- Switch your default method from auth app -> SMS
There's a couple of things to note in these changes. I'll put a summary here but please see the individual commit messages for the details and the context of code changes.
1. We can now pass an SMS OTP to the client when we call `.update()`. This is required when changing a phone number or switching from auth app to SMS, but not when we make other changes eg. switching backup to primary.
2. The API spec doesn't currently include the OTP in the update call, but I've spoken to Auth and they've confirmed this is an oversight and that we should include it in the same way as when we …

OLH-2534: Use the MFA API client when a user updates their SMS methods

---

.github/workflows/validate-sam-template-dev.yml
.github/workflows/validate-sam-template.yml

There's a new(ish) option to `sam validate` which calls out to `cfn-lint` to actually check the structure of the template and all the resources, rather than the basic checks you get without the option.
We want to catch any errors early, before we deploy, and this is another tool to help us do that.
I've run the command locally against `main` to check it passes:
```bash
frontend (BAU-sam-validate-with-lint) 4f376eac $ sam validate -t deploy/template.yaml --lint
/Users/alexsmith/di/frontend/deploy/template.yaml is a valid SAM Template
```

BAU: Do linting validation on the Cloudformation template

---

package-lock.json

Bump RP registry version so that the frontend can receive newest updates including Welsh language translations missing for the Rural Payment Wales RP.

OLH-2581: Bump rp registry to latest version

---

package-lock.json

[OLH-2533] Update RP Registry: Welsh Government Childcare Offers
RP registry has been updated with welsh government childcare providers.
Following a RP Onboarding.
[OLH-2533]: https://govukverify.atlassian.net/browse/OLH-2533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OLH-2533] Update RP Registry: Welsh Government Childcare Offers

---

package-lock.json

BAU - update rp registry which includes hoDors

Update di-account-management-rp-registry for hoDors

---

src/app.constants.ts
src/components/add-mfa-method-app/add-mfa-method-app-routes.ts
src/components/change-authenticator-app/change-authenticator-app-routes.ts
src/components/change-phone-number/change-phone-number-routes.ts
src/components/check-your-phone/check-your-phone-routes.ts
src/components/choose-backup/choose-backup-routes.ts
src/components/resend-phone-code/resend-phone-code-routes.ts

I've added the the state validation middleware to various MFA routes where it was missing and added the necessary attributes to the path objects where they were missing too.
To ensure that users can only access certain screens when they are going through particular journeys.

OLH-2600: Added state validation middleware to MFA routes

---

post-deploy-tests/tests/features/@contact-govuk-one-login.feature

Disables post-deploy tests which are passing locally but failing in the pipeline. I will investigate why they are failing later.

Disable failing post-deploy tests

---

src/components/common/mfa/index.ts
src/components/logout/tests/logout-controller.test.ts
src/components/update-confirmation/update-confirmation-controller.ts
src/config/nunjucks.ts
src/middleware/mfa-method-middleware.ts
src/utils/activityHistory.ts
src/utils/sqs.ts
src/utils/state-machine.ts

Address most of the code smells [Sonar is currently reporting](https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&types=CODE_SMELL&sinceLeakPeriod=true&id=di-account-management-frontend) on `main`.
I've split each type of change out into a separate commit to make it easier to follow.
The remaining 3 are more complex - I'll tackle those in a follow up PR.
To get the big green ✅ in Sonar ahead of our next pod check in 🤞🏻 .

BAU: Address most Sonar code smells

---

src/components/enter-password/tests/enter-password-integration.test.ts

Add tests to check that every route which uses the state machine is correctly configured to not allow users to see data without entering their password
Part of the data integriryt work

OLH-2676 check that routes are protected from direct access

---

src/components/contact-govuk-one-login/tests/contact-govuk-one-login-controller.test.ts

Fix empty assert in contact test.
This addresses a [code smell in Sonar](https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&types=CODE_SMELL&id=di-account-management-frontend&open=AYxd3f2YF4MDWr1eKmFW).
`expect(...)` doesn't assert anything on its own - it always needs to be chained with one of the comparator functions.

OLH-2672: Fix empty assert in contact test

---

package-lock.json

OLH-2654 - Onboard RP: HO: Online APIS
Added new RP - Home Office Online APIS
So that we can onboard Home Office Online APIS replying party

OLH-2654 - Onboard RP: HO: Online APIS

---

.gitlint
.husky/_/commit-msg
.pre-commit-config.yaml
package-lock.json
package.json

https://govukverify.atlassian.net/browse/OLH-2643
Added gitlint repository to our precommit stage with a few rules that ensures amongst other things, commit messages includes the ticket numbers
As part of standardizing commit through pre-commit checks, by ensuring ticket numbers are added, JIRA will link the PR to the correct ticket.
A developer checks out from the branch, makes a change and attempts to commit. The pre-commit check should trigger and flag if the commit messages does not match expected criteria
Run the testing process above and check code cleaniness and quality

OLH-2643 - Standardise commit messages through pre-commit checks

---

deploy/template.yaml

Enable intervention handling in integration.
This is also the first commit in this file since enabling the new git hooks, so I'va also had to allow all the false positives found by detect secrets.
So we can do some end to end testing in integration before we release this.

OLH-2750: Enable intervention handling in integration

---

src/app.constants.ts
src/components/activity-history/activity-history-controller.ts
src/components/activity-history/tests/activity-history-controller.test.ts
src/components/common/layout/base.njk
src/components/contact-govuk-one-login/index.njk
src/config/nunjucks.ts
src/locales/cy/translation.json
src/locales/en/translation.json
test/unit/config/nunjucks.test.ts

**DO NOT MERGE** until 9th June
- add link to support guidance for new app (launching 9th June)
- remove accessibility warning (webchat accessibility has been improved in the meantime and there is evidence to suggest the message is putting people off)
- update link to privacy notice page
Recording of the Welsh and English versions of the page below (note the links to the new guidance page are not working yet as the guidance is due to go live on the 9th) 
https://github.com/user-attachments/assets/2f468624-7796-44fc-bba9-b435deefd22f
1 - adding links to self-help guides ready for the new app launch
2 - webchat accessibility has been significantly improved and this message is putting users off
3 - we are moving the privacy notice URL and should update this link
Mel has checked this against …

OLH-2656: Contact page content updates

---

package-lock.json

Update RP registry to include DfT Connectivity Tool

OLH-2765: update RP registry to include DfT Connectivity Tool

---

package-lock.json

Update RP registry to update start page description for Connectivity Tool from the Department for Transport

OLH-2765: update RP registry

---

src/components/permanently-suspended/index.njk
src/components/permanently-suspended/permanently-suspended-controller.ts
src/components/your-services/index.njk
src/components/your-services/tests/your-services-controller.test.ts
src/components/your-services/your-services-controller.ts

When the feature flag is enabled, use the "service search" page instead of the external services link.
So that we show users the correct list of services they can use with One Login

OLH-2821 link to searchable list

---

src/app.constants.ts
src/services/event-service.test.ts
src/services/event-service.ts
src/services/types.ts

The PR updates some audit events, in order to send the extra data required by the spec.

OLH-2871 add fields to MFA delete audit event

---

src/components/add-mfa-method-sms/add-mfa-method-sms-controller.ts
src/components/check-your-phone/check-your-phone-controller.ts

Fixes debug logging for https://govukverify.atlassian.net/browse/OLH-2896. The debug logging I added last week made it look like the issue was fixed but it was actually just causing a different error message which I wasn't looking for. This should fix this issue so that I can see if the original error is still occurring, although I think it is.

OLH-2896: fix debug logging

---

deploy/template.yaml

[OLH-2902] Disable Splunk logs in staging
Disable splunk logs in staging 
Reduce number of logs sent to Splunk
[OLH-2902]: https://govukverify.atlassian.net/browse/OLH-2902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2902: Disable splunk logs in staging

---

src/components/add-mfa-method-sms/add-mfa-method-sms-controller.ts
src/components/check-your-phone/check-your-phone-controller.ts

Restores logging to try and understand the undefined phone number bug which we thought was fixed but has since occurred again.

OLH-2896: restore phone number logging

---

package-lock.json
package.json

Updates the RP registry to the latest version

BAU: update RP registry

---

src/app.constants.ts
src/components/global-logout/global-logout-controller.ts
src/components/global-logout/tests/global-logout-controller.test.ts
src/components/logout-redirect/logout-redirect-controller.ts
src/components/logout-redirect/tests/logout-redirect-controller.test.ts

Redirect the user to sign in after global logout

OLH-2787: global logout redirect to sign in

---

deploy/template.yaml

Enables global logout in build and staging

OLH-2968: enable global logout in build and staging

---

package-lock.json

Update the RP registry to the latest version

OLH-2660: update RP registry [skip canary]

---

src/components/search-services/search-services-controller.ts
src/components/search-services/tests/search-services-controller.test.ts

This implements a hacky solution to check the translations to see if this client has any additional search terms first, then only doing the translation if they do which will prevent the errors.
I've put the translations object at the base level of the file so it's only created once on the first page load per container. This is the 'least bad' solution I could come up with on short notice (as we need to release this feature). A better and (probably) more performant fix would be to add a method to the registry package that exposes information about a single client's translations. I'll write up a ticket to investigate that option for later.
We got loads of `safeTranslate` errors when we tried to release this feature because the previous logic was always trying to translate the additional …

OLH-3072: Check for search terms before translating

---

package-lock.json

Includes searchable list text update for **Find teacher training courses**.

OLH-2660: Bump rp registry to latest version

---

src/components/activity-history/index.njk
src/components/change-email/index.njk
src/components/change-password/index.njk
src/components/check-your-email/index.njk
src/components/check-your-phone/index.njk
src/components/choose-backup/index.njk
src/components/common/errors/404.njk
src/components/common/errors/500.njk
src/components/common/layout/banner.njk
src/components/common/layout/base-page.njk
src/components/common/layout/base.njk
src/components/common/mfa/add-auth-app.njk
src/components/common/mfa/add-phone-number.njk
src/components/delete-account/index.njk
src/components/delete-mfa-method/index.njk
src/components/enter-password/index.njk
src/components/permanently-suspended/index.njk
src/components/report-suspicious-activity/index.njk
src/components/resend-email-code/index.njk
src/components/resend-phone-code/index.njk
src/components/search-services/index.njk
src/components/security/index.njk
src/components/session-expired/index.njk
src/components/signed-out/index.njk
src/components/switch-backup-method/index.njk
src/components/temporarily-suspended/index.njk
src/components/update-confirmation/index.njk
src/components/your-services/index.njk

I changed the spacing/indentation on a few templates which makes the changes in this PR look more extensive than they actually are.
There are 3 main categories of changes:
The `base-page.njk` template extends the main `base.njk` template and ensures a two-thirds layout is applied across all pages. A number of templates were extending  `base.njk` and applying the two-third layout manually using `govuk-grid-column-two-thirds`. This reduces some of that repetition and ensures all pages are using the correct layout. 
I noticed instances of `.govuk-heading-l` usually had the `.govuk-!-margin-top-0` override class. But this was redundant, as this style of heading [already has margin-top:0 as defined in govuk-frontend](https://github.com/alphagov/govuk-frontend/blob/88f8b7a1780caf63e0d9fb43c46cef …

BAU: template refactoring

---

package-lock.json

Bump RP registry package to latest version which includes the DWP Find Your Pensions client.

OLH-2884: Bump RP registry to newest version

---

src/assets/scss/application.scss

Tweak account nav css to ensure height of links is appropriate in the scenario where there is no active/selected item. 
Currently, when there is no `activeNav` in the account secondary navigation header, the height of the header is not correct. The correct height is applied when items are interacted with, which leads to a “jump”:
https://github.com/user-attachments/assets/8e036d19-13e8-45f1-b2da-e7794a75d000
This is an edge case as it seems the only page which uses the nav without either "Security" or "Your services being selected is the 500 error page 🤔  
Even then I suppose there's a question to be raised as to whether the nav should exist on that page to begin with. For the time being, I've fixed this but it might be worth revisiting which pages should have the nav switched on. …

OLH-3105: CSS tweaks

---

.github/workflows/sonarcloud.yml

Bump the Sonar GitHub Action version to address the vulnerability described at https://community.sonarsource.com/t/security-advisory-sonarqube-scanner-github-action/147696/15

BAU: bump Sonar action version to address vulnerability

---

package-lock.json

Update the RP registry to the latest version

OLH-3060: update to latest RP registry version
