govuk-one-login/di-account-management-frontend

manifest.yml

Add gtm id to manifest.
As it is blank when deployed.

Add missing value in manifest

---

ci/terraform/production.tfvars

- Add missing values for `cf_domain` and `redis_service_plan`
Deploy is failing because of missing variables.

GOVSI-822: Add missing production tfvars

---

ci/terraform/production.tfvars

- Update `production.tfvars` to include renamed sub-domain.
We have renamed the production sub-domain.
https://github.com/alphagov/di-infrastructure/pull/56

GOVSI-822: Rename `prod` to `production` sub-domain

---

ci/tasks/generate-account-management-deployment-variables.yml
manifest.yml

- Set the number of app instances as a variable
- Default to 1 in the generate-account-management-deployment-variables.yml and we can then override it in the pipeline
- So we can prevent any downtime when deploying the account management frontend
https://github.com/alphagov/di-infrastructure/pull/60

GOVSI-854 - Set the number of app instances as a variable

---

ci/terraform/account-management-client.tf

- Set the IsInternalService attribute to true
- So that Account management is registered as an Internal Service

BAU - Set the IsInternalService attribute to true

---

src/assets/javascript/cookies.js

Check cookie consent before clearing.
To avoid clearing existing cookie preferences cookie.

Check cookie consent before clearing cookie

---

src/components/start/start-controller.ts
src/components/start/tests/start-controller.test.ts

Add in cookie consent to authorize request.
To enable sharing of cookie consent across apps.

Add in cookie consent to authorize request

---

src/components/logout/logout-routes.ts

Add requires auth middleware to logout route.
To fix a 502 bad gateway issue when user already logged out.

Add requires auth flag to logout

---

src/assets/javascript/cookies.js

Add missing user journey to data layer for journey tracking.
Missed a required user session to track when users load up the account management page.

Add missing user journey to data layer

---

ci/tasks/generate-account-management-deployment-variables.yml
ci/terraform/account-management-client.tf
ci/terraform/build.tfvars
ci/terraform/cf-data.tf
ci/terraform/integration.tfvars
ci/terraform/outputs.tf
ci/terraform/production.tfvars
ci/terraform/sandpit.tfvars
ci/terraform/site.tf
ci/terraform/variables.tf

- Extract the service_domain from the domain outputs
- Run terraform fmt
- So account management can set the ANALYTICS_COOKIE_DOMAIN
- So terraform is formatted

BAU - Extract service domain to set ANALYTICS_COOKIE_DOMAIN

---

src/assets/javascript/cookies.js

Push the session journey information to the data layer before the gtm.start tag is pushed to ensure the session journey is available before the google analytics is triggered.
Ensure the user journey information is available from the data layer at the correct point.

Add the session journey to the data layer before the gtm container is created

---

.github/workflows/analyse-on-merge.yml
package.json
sonar-project.properties

- Add a `sonar-project.properties` file
- Add `yarn test:coverage` task to GitHub Actions
- Add an analysis on merge to give coverage stats for `main`
Analysis is being performed, but no coverage stats are being collected, we need to resolve this.

GOVSI-1053: Add Sonar coverage collection

---

src/app.ts

Reorder middleware.
To allow the _ga tag to be read from the  cookie.

Reorder middleware so GA value can be read from cookie

---

src/app.constants.ts
src/components/change-password/change-password-controller.ts
src/components/change-password/change-password-service.ts
src/components/change-password/tests/change-password-controller.test.ts
src/components/change-password/tests/change-password-integration.test.ts
src/components/change-password/types.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/utils/errors.ts
src/utils/http.ts
src/utils/types.ts

- When a user tries attempts to change their password using their existing password the api will return an error code. When this error code is returned to the user we need to present the correct error message to the user.
- Because a user shouldn't be able to change their password to their existing password.

GOVSI-1100 - Handle error when user changes password to current password

---

.github/dependabot.yml

Remove dependabot open-pull-requests-limit.
Ability to choose from all available upgrades.

BAU: remove dependabot open-pull-requests-limit

---

docker-compose.yml
src/components/change-email/change-email-controller.ts
src/components/change-email/types.ts
src/components/change-password/change-password-controller.ts
src/components/change-password/change-password-service.ts
src/components/change-password/types.ts
src/components/change-phone-number/change-phone-number-controller.ts
src/components/change-phone-number/change-phone-number-service.ts
src/components/change-phone-number/types.ts
src/components/check-your-email/check-your-email-controller.ts
src/components/check-your-email/check-your-email-service.ts
src/components/check-your-email/types.ts
src/components/check-your-phone/check-your-phone-controller.ts
src/components/check-your-phone/check-your-phone-service.ts
src/components/check-your-phone/types.ts
src/components/delete-account/delete-account-controller.ts
src/components/delete-account/delete-account-service.ts
src/components/delete-account/types.ts
src/components/enter-password/enter-password-controller.ts
src/components/enter-password/enter-password-service.ts
src/components/enter-password/types.ts
src/middleware/set-local-vars-middleware.ts
src/utils/http.ts
src/utils/logger.ts
test/utils/logger.test.ts

- Log session id on am frontend and pass to apis.
- Tweak am frontend response logging to remove unavailable fields.
- Add 'from' field to request logging to bring into line with frontend.
- Change local node debug port to stop clash with frontend.
- Ability to view a single session across both frontend and account management.
- Some fields being logged in the am frontend response were not actually available so were never being logged.
Please include links to PRs in other repositories relevant to this PR.
Delete this section if not needed.

GOVSI-1141: log session id on am frontend and pass to apis

---

src/components/change-email/change-email-service.ts
src/components/change-password/change-password-service.ts
src/components/change-phone-number/change-phone-number-service.ts
src/components/check-your-email/check-your-email-service.ts
src/components/check-your-phone/check-your-phone-service.ts
src/components/delete-account/delete-account-service.ts
src/components/enter-password/enter-password-service.ts

- In a number of places the session ID and persistent session ID were being passed to the service in the wrong order, lets fix this.
Whilst this wasn't causing a functional problem it will cause audit issues.

BAU: Fix incorrectly ordered session/persistent id parameters

---

manifest.yml
src/components/delete-account/delete-account-controller.ts
src/config.ts
src/config/aws.ts
src/config/oidc.ts
src/config/session.ts

Update Account Management to support running under Fargate.
- Redis config.
- KMS config. 
Configuration and accessing AWS is different under Fargate compared to Paas.

AUTH-1273: update config for redis and kms to run on fargate

---

Dockerfile
docker-compose.yml
local.Dockerfile
package.json

Create separate docker image for fargate.
- Rename existing local image and update docker-compose.yml to use it.
- Add a new dockerfile to run the application in fargate.  This image needs all files locally as it cannot rely on a mounted volume.
- Use 'cp' instead of 'copyfiles' in one place in package.json as copyfiles was hanging when building and/or running the docker image.
A separate image is needed to run in fargate as we are currently using a CF node buildpack rather than a docker image.  The existing local image could not be run in fargate as-is.

AUTH-1273: create separate docker image for fargate

---

ci/terraform/account-management-client.tf

- Explicitly set ConsentRequired to false for Account Management
- Although by default ConsentRequired would be false we should be explicit where possible. 
- Account Management users do not require to view the consent page. We were previously using the InternalService flag for this but we are now transitioning to a broader named flag to manage this as it will not just be internal service users who should not see the consent page.

AUTH-1168 - Set ConsentRequired to false for Account Management

---

README.md
ci/terraform/account-management-client.tf

- Remove the InternalService attribute
- The InternalService was previously used to calculate whether consent should be shown to the users or not. This has now been replaced with the ConsentRequired attribute.

AUTH-1168 - Remove the InternalService attribute

---

Dockerfile

- Use Multistage docker builds to reduce fargate docker image size
- By using multistage docker builds we can reduce the size of the docker image in ECR from 179mb to 61mb.

BAU - Use Multistage docker builds to reduce fargate docker image size

---

src/app.constants.ts
src/app.ts
src/components/healthcheck/healthcheck-controller.ts
src/components/healthcheck/healthcheck-routes.ts
src/components/healthcheck/tests/healthcheck-controller.test.ts
src/components/healthcheck/tests/healthcheck-integration.test.ts

Add healthcheck endpoint to account management application.
The endpoint returns a simple '200 OK'
ALB and Fargate requires a healthcheck endpoint to know whether the app has started.

AUTH-1277: add healthcheck endpoint to account management application

---

Dockerfile

Update dockerfile to use yarn build rather than production
Build is currently being used in PaaS rather than production so this reflects the live application.
Further configuration tweaks will be needed to make the production config work.

AUTH-1277: update dockerfile to use yarn build rather than production

---

ci/terraform/account-management-kms.tf
ci/terraform/alerts.tf
ci/terraform/build.tfvars
ci/terraform/core.tf
ci/terraform/integration.tfvars
ci/terraform/production.tfvars
ci/terraform/redis.tf
ci/terraform/sandpit.tfvars
ci/terraform/security-groups.tf
ci/terraform/site.tf
ci/terraform/variables.tf

- Add the Terraform to create a new Elasticache Redis cluster for use by the account management application when it migrates to Fargate.
- Swap the AWS provider default tags to using a `local.default_tags` variable as the former doesn't work well all resource types.
We are migrating the account management application to Fargate

AUTH-1276: Create frontend Redis for Fargate

---

src/app.ts
src/components/change-email/tests/change-email-integration.test.ts
src/components/change-password/change-password-routes.ts
src/components/change-password/tests/change-password-integration.test.ts
src/components/change-phone-number/tests/change-phone-number-integration.test.ts
src/components/check-your-email/tests/check-your-email-integration.test.ts
src/components/check-your-phone/tests/check-your-phone-integration.test.ts
src/components/delete-account/tests/delete-account-integration.test.ts
src/components/enter-password/tests/enter-password-integration.test.ts
src/components/healthcheck/tests/healthcheck-integration.test.ts
src/components/manage-your-account/tests/manage-your-account-integration.test.ts
src/config.ts
src/config/session.ts
src/server.ts
src/types.ts
src/utils/ssm.ts

Read Redis configuration from SSM for ECS Fargate.
AM currently runs on PaaS and retrieves Redis connection details from PaaS services.  This option is not available when running on ECS Fargate.
Some Redis connection details are secret so we decided to put them in AWS SSM Parameter store.  This PR reads these parameters from SSM when running under Fargate so that the app can connect to Redis.

AUTH-1273: read redis configuration from ssm for ecs fargate

---

src/app.ts
src/config.ts

- Fix the parameter names for port and password (remove the `master-` portion)
- Use APP_ENV rather than NODE_ENV to construct parameter names
- The return type from `getParameters` is a list not map, iterate  appropriately
When running in Fargate the app was unable to fetch or parse the parameters.

AUTH-1273: Fix fetching of Redis parameters from SSM

---

src/components/common/layout/base.njk

Fix gov.uk links in header.
This is breaking cross domain tracking.

Fix gov.uk links for cross domain tracking

---

ci/tasks/deploy-account-management.yml

- Remove trailing whitespace in deployment task
It seems the trailing whitespace (after the `\`) is being interpreted as an additional parameter. Remove it.
#321

AUTH-1273: Remove trailing whitespace

---

ci/terraform/alb.tf

- Use a shorter name for the ALB. In our production and integration environments, the previous name was exceeding the 32 character limit.
- Use a nicer name for the ALB target group that is inline with the ALB name
Deployment to production and integration is failing due to the length limit.
On reflection, the target group name was previously a little cryptic so bring it in line with the ALB name.

AUTH-1273: Use shorter name for ALB

---

ci/tasks/deploy-account-management.yml
ci/terraform/alb.tf
ci/terraform/build.tfvars
ci/terraform/integration.tfvars
ci/terraform/production.tfvars
ci/terraform/sandpit.tfvars
ci/terraform/security-groups.tf
ci/terraform/variables.tf

- Use the image metadata (repo, tag, digest) provided by the image resource to inject these details into the Terraform deploy.
- Remove default values from environment files.
- Add the listener to production but restrict access in prod by using the security group (required as deployment fails in production with out a listener).
We are now building a new image on merge, we need to ensure the details of the new image are passed to Terraform to be deployed to ECS.
We also need to fix the production deploy, previous attempt to secure production by not deploying the listener did not work as a listener needs to be present for the service to deploy successfully.

AUTH-1278: Deploy to fargate in pipeline

---

ci/terraform/cloudwatch.tf
ci/terraform/waf.tf

- Add a WebACL to the account management ALB (use same rules as we currently use on API)
- Add logging of blocked requests to a new log group
- Drain log groups to Splunk
To secure the ALB we will be using to host the account management frontend

AUTH-1321: Add a WAF to the account managemnt ALB

---

ci/terraform/ecs.tf
ci/terraform/production.tfvars
ci/terraform/variables.tf

- Set instances to 2 for non-prod and 4 prod
- Set deployment strategy as 50% minimum and 100% maximum
To ensure the Fargate allocations are similar to that of PaaS.
The deployment strategy was set using Verify Hub as a reference to ensure old versions of tasks don't lurk around after a deployment.

AUTH-1316: Bring ECS sizing in line with PaaS deployment

---

ci/terraform/cloudwatch.tf
ci/terraform/ecs.tf

- Rename the ECS service log group to be prefixed with `/ecs/`
This will group all the ECS related logs together (alphabetically) in Cloudwatch and make it easier to pick out the log groups in the Splunk processor.
https://github.com/alphagov/di-infrastructure/pull/158
https://github.com/alphagov/di-authentication-frontend/pull/484
https://github.com/alphagov/centralised-security-logging-service/pull/797

AUTH-1369: Rename ECS service log group

---

ci/terraform/ecs.tf

- In previous PR, we introduced a naming conflict through a copy/paste error.
Pipeline is failing due to naming conflict.
#333

AUTH-1369: Fix naming of service and container

---

package.json
yarn.lock

- Bump the Axios version to 1.25.0 (which in-turn bumps the follow-redirects version to 1.14.7)
The follow-redirects upgrade addresses CVE-2022-0155

BAU: Bump Axios version to 1.25.0

---

ci/terraform/route53.tf

- In preparation for the migration lets change the hostname on the ALB TLS certificate to that of the real DNS name of the service.
We will pointing the real DNS records at the ALBs in the near future, so let's get the certificates ready.

AUTH-1388: Change the hostname on the ALB certs

---

ci/terraform/route53.tf

- Revert previous cert rename from #348 
- Create a new resources for the new certificates.
Sadly renaming the certificate did not work, as the original is in use. We want the new certificates ready for the rollout.

AUTH-1388: Create new certifcates as new resources

---

ci/terraform/alb.tf

- Add HTTP listener to ALB. Default action is to redirect request to HTTPS
To redirect non-secure traffic.

AUTH-1388: Add HTTP listener that redirects to HTTPS

---

ci/tasks/deploy-account-management.yml

- We have the number of instances being overridden in both in the environment specific `.tfvars` file and in the pipeline deploy task, lets remove the variable from the task and rely on the `.tfvars`
Injected variables from the deploy task should be reserved for secrets only.
https://github.com/alphagov/di-authentication-frontend/pull/502
https://github.com/alphagov/di-infrastructure/pull/165

AUTH-1388: Use tfvars for number of instances

---

ci/tasks/deploy-account-management.yml
ci/terraform/.terraform.lock.hcl
ci/terraform/sandpit.tfvars
ci/terraform/site.tf
ci/terraform/variables.tf

- Remove the, now unused, Cloudfoundry provider from Terraform
- Remove related variables used for Cloudfoundry authentication
- Update deploy task to reflect above changes
We no longer have any managed PaaS (Cloudfoundry) resources.

AUTH-1389: Remove Cloudfoundry provider from Terraform

---

ci/terraform/account-management-client.tf
ci/terraform/alb.tf
ci/terraform/route53.tf

- Remove the route53 resource `acc-mgmt-fg.<domain>`
- Remove the ACM resources for generating a certificate for the above domain name.
The `acc-mgmt-fg.<domain>` was a testing hostname during the migration from PaaS to ECS.

AUTH-1839: Remove the generation of the acc-mgmt-fg DNS and cert

---

src/components/change-phone-number/change-phone-number-controller.ts

- Default to null if supportInternationalNumbers is set to false
- So it correctly renders the correct content when there has been a validation failure

AUTH-1446 - Default to null if supportInternationalNumbers is set to false

---

package.json
yarn.lock

Force minimist to 1.2.6.
Minimist is a dev-only dependency.
Fix advisory on 1.2.5
https://github.com/advisories/GHSA-xvch-5gv4-984h

BAU: force minimist to 1.2.6

---

ci/tasks/deploy-account-management.yml
ci/terraform/security-groups.tf
ci/terraform/variables.tf

- Make the CIDR block used for to match incoming traffic to the ALB parameterised. The default should be anywhere (`["0.0.0.0/0"]`)
This will allow us to override in the pipeline for staging and other environments.
https://github.com/alphagov/di-authentication-frontend/pull/560

AUTH-1427: Parameterise ALB allowlist

---

ci/terraform/cloudwatch.tf

- Add the `kms:ReEncrypt*` and `kms:GenerateDataKey*` actions to the cloudwatch policy.
It seems these are now required to create encrypted log groups.
https://github.com/alphagov/di-authentication-frontend/pull/561

AUTH-1427: Add missing permissions for Cloudwatch

---

@types/express/index.d.ts
ci/terraform/account-management-client.tf
src/app.constants.ts
src/app.ts
src/components/change-email/tests/change-email-integration.test.ts
src/components/change-password/tests/change-password-integration.test.ts
src/components/change-phone-number/tests/change-phone-number-integration.test.ts
src/components/check-your-email/tests/check-your-email-integration.test.ts
src/components/check-your-phone/tests/check-your-phone-integration.test.ts
src/components/delete-account/tests/delete-account-integration.test.ts
src/components/enter-password/tests/enter-password-integration.test.ts
src/components/global-logout/global-logout-controller.ts
src/components/global-logout/global-logout-routes.ts
src/components/global-logout/global-logout-service.ts
src/components/global-logout/tests/global-logout-controller.test.ts
src/components/global-logout/types.ts
src/components/manage-your-account/tests/manage-your-account-integration.test.ts
src/config.ts
src/middleware/auth-middleware.ts
src/utils/oidc.ts

- Add a `/global-logout` route that accepts a `POST` request
- Validate that the `POST` request contains a valid logout request JWT
- Pull in issuer JWKS to validate JWT signature
This sets up the route for the back channel global logout functionality. This PR does not actually do the logout but the endpoint will provide the correct responses. Logout functionality to follow.

AUT-252: Back channel logout route and validation

---

src/components/global-logout/global-logout-controller.ts
src/components/global-logout/tests/global-logout-controller.test.ts

- Use `res.send()` rather `res.status()` in global logout. 
`res.send()` results in the endpoint "hanging"
#422

AUT-252: Use `res.send()` rather `res.status()` in global logout

---

ci/terraform/account-management-client.tf

- Set ClientType to web
- A new field has been added to the ClientRegistry to support app clients. Explicitly set the AM RP ClientType to `web`

AUT-294 -  Set ClientType to web for AM client

---

ci/terraform/alb.tf
ci/terraform/build.tfvars
ci/terraform/ecs.tf
ci/terraform/integration.tfvars
ci/terraform/variables.tf

ECS rollout configuration tweaks in build and integration only.
- Set health_check_grace_period_seconds to 15s.  Current default is 0.
- Set ALB deregistration_delay to 30s.  Current default is 300s.
Changes to be extended to staging and prod after checks in build and integration.
We currently have these two configuration values set to their defaults.
Currently waiting 300s for the apps to drain during a rollout as the deregistration delay is set to the default.  Frontend transactions complete in a matter of seconds so there is no reason to wait for 5 mins.  This will reduce rollout timeout.
See the ECS service event log when a rollout happens, it takes 5 mins between deregistration (when the ALB stops sending traffice to the app) and finally stopping the app.  Nothing happens during this …

AUT-212: ECS rollout configuration tweaks in build and integration only

---

ci/terraform/build.tfvars
ci/terraform/integration.tfvars
ci/terraform/staging.tfvars

Rollout auto scaling to int and staging.
We should be able to reduce both CPU and memory down further later on and scale out instead given the existing headroom.
Scaling up and down has been proven in build using the performance tests.
#463 
#461

AUT-213: rollout auto scaling to int and staging

---

ci/terraform/account-management-client.tf

- Set IdentityVerificationSupported to false in the Client Registry 
- AM doesn't support identity, so set the new field 'IdentityVerificationSupported' in the client registry to false

AUT-381 - Set IdentityVerificationSupported to false in the Client Registry 

---

src/locales/cy/translation.json
src/locales/en/translation.json

Update content for session timeout to 2hrs.
Session timeout is being increased to 2hrs to cater for long-running identity flows.
https://github.com/alphagov/di-authentication-api/pull/1919
https://github.com/alphagov/di-authentication-frontend/pull/598

AUT-401: update content for session timeout to 2hrs

---

src/components/change-password/change-password-validation.ts
src/utils/strings.ts
test/unit/utils/strings.test.ts

- Remove check to see if string contains letter
- We already do this by checking whether the string contains a number so we can remove this redundant validation

AUT-302 - Remove check to see if string contains letter

---

ci/terraform/alb.tf

Ensure TLS >=1.2 and disallow CBC ciphers
Currently we allow TLS 1.0 and 1.1. We should not allow that.
We also allow CBC-mode ciphers.  We should not allow that, preferring
GCM (or ChaCha20, but I don't think ELBs support that).
Amazon load balancer security policies are documented here:
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#describe-ssl-policies
This configuration is (roughly) equivalent to mozilla's "intermediate"
recommendation here:
https://wiki.mozilla.org/Security/Server_Side_TLS
It should support Firefox 27, Android 4.4.2, Chrome 31, Edge 12, IE 11
(on Win7), Java 8u31, OpenSSL 1.0.1, Opera 20 and Safari 9.
Please include reason for the change and any other relevant context. …

DCP-157: Ensure TLS >=1.2 and disallow CBC ciphers

---

local.Dockerfile
package.json
yarn.lock

Use node-dev instead of nodemon.
There is a vulnerability in a nodemon transitive dependency, though this is dev only and is not deployed in any environment so cannot be exploited.
https://github.com/advisories/GHSA-pfrx-2q88-qq97

BAU: Use node-dev instead of nodemon

---

src/locales/cy/translation.json
src/locales/en/translation.json

- Update feedback link
- Make it clear that this link opens in a new tab as users of screen reading assistive technologies need to be provided with this information prior to activating the link.

AUT-462 - Update feedback link

---

src/components/change-phone-number/change-phone-number-validation.ts
src/components/change-phone-number/tests/change-phone-number-integration.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/utils/phone-number.ts
test/unit/utils/phone-number.test.ts

- Provide option to enter 44 or +44 before UK number
- Some users use +44 or 44 when entering their phone numbers. Adapt the validation to allow this.
- Add regex to the phone-number validation for checking a UK number. This is because relying on isValidPhoneNumber allowed some numbers which were not UK numbers through. Such as +33.
- Change the validation text to represent the changes made.
- Previously users could enter a UK number such as 07738393990. Allow users to enter their UK numbers in one of the following formats in addition to what we currently allow +447738393990, +4407738393990, 447738393990, 4407738393990.

AUT-474 - Provide option to enter 44 or +44 before UK number

---

src/components/manage-your-account/index.njk

- Remove incorrectly added `#` from element ID
The `#` should be there as creates an invalid ID name.
#522 
https://github.com/alphagov/di-authentication-smoke-tests/pull/47

BAU: Remove # from ID name

---

src/components/common/layout/base.njk

Do not open all footer links in a new tab
These links will now open in the same tab:
- Accessibility statement
- Cookies
- Terms and conditions
- Privacy notice
Please include a summary of the change.
f a link opens in a new tab users of screen reading assistive technologies need to be provided with this information prior to activating the link. Either we update the link text to say that a new tab will open, or stop opening links in a new tab.
Four links will now open in the same tab as they lead to simple, more or less static pages, so using the back button will not cause any issues. The 'Support' link leads to a more complex page with more steps so it's best to keep this opening in a new tab, in this case the link text has been updated. …

AUT-473: Do not open all footer links in a new tab

---

src/app.constants.ts
src/app.ts
src/components/logout/logout-controller.ts
src/components/logout/tests/logout-controller.test.ts
src/components/signed-out/index.njk
src/components/signed-out/signed-out-controller.ts
src/components/signed-out/signed-out-routes.ts
src/components/signed-out/tests/signed-out-controller.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/middleware/requires-auth-middleware.ts
test/unit/middleware/requires-auth-middleware.test.ts

- Add cookie called `lo` (short for logged_out -> used abbreviation for consistency with other cookie names) to logout controller
- Read the status of that cookie in requires auth middleware
- Change the logic in that middleware so that instead of always either passing to `next()` or routing to session expired, we can now also direct to a new signed out page, based on the ability the `lo` cookie gives to distinguish between the two situations in which there is not a valid session
- PR includes creation of that new `/signed-out` page - which is very similar to the sign-in journey's `/signed-out` page, but differs lightly (see below) hence the need for a new route/view rather than reusing the same URL as initially implemented:
**Existing signed-out page for frontend:**
**New proposed …

AUT-198: Add cookie which tracks manual logout

---

src/components/common/layout/banner.njk
src/components/common/layout/base.njk

- Change footer cookie href from generic gov.uk cookies to signin custom cookies page
- Change cookie banner 'view cookies' href from generic gov.uk cookies to signin custom cookies page
- So that user has correct set of cookie information

AUT-557: change footer cookie href

---

src/components/delete-account/delete-account-controller.ts
src/components/delete-account/index.njk
src/components/manage-your-account/index.njk
src/components/manage-your-account/manage-your-account-controller.ts
src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

~**This can be reviewed but please do not merge yet, we will deploy this once we hear from LITE regarding the exact date/time they are going live (due to onboard 25 July, but there’s a chance there might be delays).**~
LITE have gone live with GOV.UK Sign In so we can go ahead. 🚀 
Update content of 'Are you sure you want to delete your account' screen ahead of LITE service onboarding.
Design is here: https://www.figma.com/file/tepd26ZAc8QhiLJlxYN1wR/Data-management-and-Navigation?node-id=1522%3A3976
The purpose of these updates is so that the page more clearly explains the consequences of deleting your account.

GUA-226: Update content on delete account page

---

src/components/manage-your-account/index.njk
src/components/manage-your-account/manage-your-account-controller.ts
src/components/manage-your-account/tests/manage-your-account-integration.test.ts
src/components/oidc-callback/call-back-controller.ts

- Refactor callback controller to save `phone_number_verified` field of UserInfo response to the session user data
- Use this new field in the session user data as the basis for conditional display logic to either show or not show a phone number in account management screen
- Note: This conditional display logic was previously being done on the basis of simple existence of a phone number. However, that meant the row would be displayed even if not verified.
Screen when phone number IS verified:
Screen when phone number IS NOT verified:
Unverified phone numbers were previously being displayed. This was particularly undesirable when a user saved a phone number record during account creation, then changed mind on MFA method to use auth app instead. In this case, we would not want the phone …

AUT-588: Display only verified phone numbers in account management

---

docker-compose.yml

Add `container_name` to docker-compose.yml
Allows `docker exec` to run against container name rather than ID as is shown in the "Running the tests" section of README.md

Add container_name to docker-compose.yml

---

src/components/check-your-email/index.njk
src/components/check-your-phone/index.njk

- Add fields to all govukInput elements which take an OTP code
- Make input mode numeric and pattern match for "[0-9]*"
- This is instead of <input type="number"> which can be increased accidentally with keyboard arrows or scroll wheel
- So that users are less likely to submit an incorrect OTP code simply by having knocked their mouse or keyboard and therefore changing their input without noticing
Same thing for frontend: https://github.com/alphagov/di-authentication-frontend/pull/723

AUT-554: Make govukInput elements numeric for OTP code

---

package.json
yarn.lock

- Bump govuk-frontend from 4.0.1 to 4.3.1
- Will allow copyright statement to be translated into Welsh (see release notes: https://github.com/alphagov/govuk-frontend/releases/tag/v4.3.0)

BAU: Bump govuk-frontend from 4.0.1 to 4.3.1

---

src/app.constants.ts
src/app.ts
src/components/check-your-phone/check-your-phone-controller.ts
src/components/check-your-phone/check-your-phone-service.ts
src/components/check-your-phone/tests/check-your-phone-controller.test.ts
src/components/check-your-phone/tests/check-your-phone-integration.test.ts
src/components/check-your-phone/types.ts
src/components/security-code-error/index.njk
src/components/security-code-error/security-code-error-controller.ts
src/components/security-code-error/security-code-error-routes.ts
src/components/security-code-error/tests/security-code-error-controller.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Build new security code error page to display error message when SMS OTP attempts limits are exceeded.
Limit SMS OTP attempts for users when changing a phone number
[Backend changes](https://github.com/alphagov/di-authentication-account-management/pull/561)

AUT-607: Limit SMS OTP attempts, frontend changes

---

src/components/check-your-email/index.njk
src/components/check-your-phone/index.njk

Remove pattern attribute from numeric inputs
This update reflects a recent change to GOV.UK Design System recommendations for using pattern attributes on number inputs. The Design System update is described at: https://github.com/alphagov/govuk-design-system/pull/2323
Similar PR raised in `di-authentication-frontend` here: https://github.com/alphagov/di-authentication-frontend/pull/740

AUT-669: Remove pattern attribute from numeric inputs

---

src/components/security-code-error/security-code-error-controller.ts

Use `/request-new-opt-code` url for `newCodeLink` when OTP limit exceeded changing phone number
User is unable to redirect to request a new OTP code when limit has exceeded
[Limit SMS OTP attempts, frontend changes](https://github.com/alphagov/di-authentication-account-management/pull/577)

AUT-607: Get new code href link bug fix 

---

src/components/delete-account/tests/delete-account-integration.test.ts

Update delete account integration test to use baseUrl
Test had been failing locally due to a port mismatch (`6000` specified in the test while `process.env.PORT` is `6001`). All tests are now passing.

FIX: Update delete account integration test to use baseUrl

---

ci/terraform/build.tfvars

Switch on Welsh in build.
Make Welsh available so that accpetance tests can be built against it.
https://github.com/alphagov/di-authentication-frontend/pull/744

BAU: Switch on Welsh in build

---

src/components/check-your-email/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json
src/utils/state-machine.ts

* Updates the "Check your email" page to reflect content and design shown in the [Figma wireframe](https://www.figma.com/file/aVqNC4pKaebZchIU691f31/DI-Authentication?node-id=4194%3A17683) for Account Management. 
* Improves code formatting in `index.njk`
* Updates state machine to permit progression from `VERIFY_CODE` to `CHANGE_VALUE`
This change is part of the AUT-599 ticket. 
Similar changes have been made in the `di-authentication-frontend` [#729](https://github.com/alphagov/di-authentication-frontend/pull/729), [#722](https://github.com/alphagov/di-authentication-frontend/pull/722), [#717](https://github.com/alphagov/di-authentication-frontend/pull/717), [#715](https://github.com/alphagov/di-authentication-frontend/pull/715)

AUT-599: update "Check your email" to reflect Figma

---

src/components/check-your-email/index.njk
src/components/check-your-phone/index.njk

- We need to ensure that an incorrect OTP entered for change phone number and change email address clears.
- So as to reduce the likelihood of a user trying to continue the journey using the same incorrect code

AUT-678: Clear Incorrect OTP

---

.eslintrc.js
package.json
src/components/manage-your-account/tests/manage-your-account-controller.test.ts
src/components/signed-out/tests/signed-out-controller.test.ts
test/unit/utils/state-machine.test.ts
yarn.lock

BAU: Remove 'it.only' test and add linting to prevent usage.
Fix failing tests.
'it.only' stops other tests from running so it shouldn't be committed.

BAU: Remove 'it.only' test and add linting to prevent usage

---

src/components/change-email/change-email-controller.ts
src/components/change-email/change-email-service.ts
src/components/change-email/tests/change-email-controller.test.ts
src/components/change-email/types.ts
src/components/change-password/change-password-controller.ts
src/components/change-password/change-password-service.ts
src/components/change-password/tests/change-password-controller.test.ts
src/components/change-password/types.ts
src/components/change-phone-number/change-phone-number-controller.ts
src/components/change-phone-number/change-phone-number-service.ts
src/components/change-phone-number/tests/change-phone-number-controller.test.ts
src/components/change-phone-number/types.ts
src/components/check-your-email/check-your-email-controller.ts
src/components/check-your-email/check-your-email-service.ts
src/components/check-your-email/tests/check-your-email-controller.test.ts
src/components/check-your-email/types.ts
src/components/check-your-phone/check-your-phone-controller.ts
src/components/check-your-phone/check-your-phone-service.ts
src/components/check-your-phone/tests/check-your-phone-controller.test.ts
src/components/check-your-phone/tests/check-your-phone-integration.test.ts
src/components/check-your-phone/types.ts
src/components/delete-account/delete-account-controller.ts
src/components/manage-your-account/tests/manage-your-account-controller.test.ts
src/utils/http.ts

Pass user language as header to services sending notifications so that the Notify messages can be in both English and Welsh
Makes use of existing dormant changes to the account managemnt api.
Some unrelated tests have been formatted due to running 'pretty' on the codebase.
Enable the Account Management backend to choose Notify template by language.
https://github.com/alphagov/di-authentication-api/pull/2324
https://github.com/alphagov/di-authentication-frontend/pull/749
https://github.com/alphagov/di-authentication-frontend/pull/750

AUT-639: Pass User-Language header to services sending notifications.

---

src/components/change-email/index.njk
src/components/change-password/index.njk
src/components/check-your-email/index.njk
src/components/check-your-phone/index.njk

Replaces hard-coded "Continue" with references to the translation values.
So that buttons reflect the language choices of users.

AUT-690 Localisation for "continue" and "back" 

---

src/config/i18next.ts

i18next cookie tweaks.
- Remove use of SameSite for the lng cookie.
- Remove lng parameter from configuration.
Fixes an issue where the lng cookie set by the backend in /authorize was not being respected by the frontend, so service language preferences were not being followed.
- lng parameter overrides language detection and is not required when detection is in use. The fallback language (en) still applies if no language is set.
https://github.com/alphagov/di-authentication-frontend/pull/765
https://github.com/alphagov/di-authentication-frontend/pull/763
https://github.com/alphagov/di-authentication-account-management/pull/602

AUT-691: Tweak i18next cookie config

---

src/assets/scss/application.scss
src/components/change-password/index.njk
src/components/common/show-password/macro.njk
src/components/enter-password/_change-email.njk
src/components/enter-password/_change-password.njk
src/components/enter-password/_change-phone-number.njk
src/components/enter-password/_delete-account.njk
src/locales/cy/translation.json
src/locales/en/translation.json

This commit updates the two show password macros and all their implementations to:
1. Remove the unused 'hint' parameter that was causing an unnecessary element to be included in the HTML payload
2. Support translations via a new `showSettings` config object
Please include a summary of the change.
So that users viewing the page in Welsh have the component translated correctly.

AUT-714: Update "show password" component to support translations

---

src/components/common/layout/banner.njk
src/components/common/layout/base.njk
src/locales/cy/translation.json
src/locales/en/translation.json

~**DO NOT MERGE:** it has not yet been confirmed that our Welsh translations for the copyright and content licence paragraphs in the footer are correct.~
-----
- localise copyright and content licence strings in the footer
- remove duplicate html block from the cookie banner partial
- use curly quotes throughout the Welsh translation file instead of straight apostrophes

GUA-366: Welsh translation updates

---

ci/terraform/redis.tf

- Change elasticcache maitenance window
- Make the maintenance window earlier so that it still avoids high periods of traffic but so that it is not in the middle of the night should elasticcache maintenance caus e an incident.

BAU - Change elasticcache maitenance window

---

ci/terraform/cloudwatch.tf

We were routing two sets of subscriptions to the WAF log group

BAU: Route correct logs to correct subscription

---

ci/terraform/.terraform.lock.hcl
ci/terraform/site.tf

- Bump the random provider to the latest version
It looks Terraform has been run on some environments with a later version of the provider, as we're now getting errors in the pipeline.

BAU: Bump Terraform random provider

---

ci/terraform/integration.tfvars

Enable Welsh Language in Integration
Part of the current push to enable Welsh within digital Identity
Once merged and tested to satisfaction please follow up with the prod PR:
https://github.com/alphagov/di-authentication-account-management/compare/DCP-88-WelshInProd?expand=1

DCP-88 - Enable Welsh locale in the integration Environment

---

src/app.constants.ts
src/app.ts
src/components/resend-email-code/index.njk
src/components/resend-email-code/resend-email-code-controller.ts
src/components/resend-email-code/resend-email-code-routes.ts
src/components/resend-email-code/tests/resend-email-code-controller.test.ts
src/components/resend-email-code/tests/resend-email-code-integration.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/utils/state-machine.ts
test/unit/utils/state-machine.test.ts

- Create a “Get security code” page within the Account Management app that reflects what is shown in Figma
- Users clicking “send the code again” on the “Check your email” page are presented with the “Get security code” page
- Users clicking “Get security code” (on the “Get security code” page) results in:
- a security code being sent to the email address
- the user being directed to the “Check your email” page
To provide an equivalent experience when requesting a new security code email during registration and managing an account.

ACI-78: Create new Get Security Code page

---

ci/terraform/production.tfvars

Enable Welsh Language in Production
Part of the current push to enable Welsh within digital Identity
Please only merge after we've merged integration and are satisfied the change has appeared there correctly
https://github.com/alphagov/di-authentication-account-management/pull/640

DCP-88: Enable Welsh language in production

---

CODEOWNERS

Codeowners were incorrect so I couldn't merge

BAU: Add alpha and bravo teams to codeowners

---

src/utils/phone-number.ts
test/unit/utils/phone-number.test.ts

- Regex had previously accepted any phone number where first two numbers were 0 or 7.
- This includes many common international phone number formats e.h. 0033 for France.
- We are now relying on functions from our supporting library instead of regex to determine if a phone number is a UK one
- Note that we use country code rather than specifying country as GB, so as not to exclude Isle of Man and similar.
- Whilst support international phone numbers feature flag is toggled to off ("0"), we do not wish to allow users to register with international phone numbers.

AUT-824: Fix international phone number validation rule

---

ci/terraform/build.tfvars
ci/terraform/integration.tfvars
ci/terraform/production.tfvars
ci/terraform/sandpit.tfvars

The old endpoint has been deprecated

BAU: Stop writing to old logging endpoint

---

src/utils/oidc.ts

- Fix global logout for account management by setting the user-agent header in the request to the JWKs endpoint
- The global logout for account management was failing because of the following error 'Unable to validate logout_token. Error: Expected 200 OK from the JSON Web Key Set HTTP response'
- The reason for this was that the request was being blocked by the OIDC WAF for not having the user-header set. Set the user-header in the request to the jwks endpoint so that account management can retrieve the JWKs and validate the logout token

AUT-848 - Fix global logout for account management

---

src/components/global-logout/global-logout-controller.ts
src/components/global-logout/tests/global-logout-controller.test.ts

- Set logout cookie to true when global logout is successful
- When there has been a successful global logout, we need to ensure that we set the `lo` cookie to true to imply the user is logged out.
- This cookie is checked in the `requires-auth-middleware.ts` to see if the user is still logged in or not. If this cookie value is set to true, then the user will be redirected to the signed out page.

AUT-848 - Set logout cookie when global logout is successful

---

src/components/global-logout/global-logout-controller.ts
src/components/global-logout/tests/global-logout-controller.test.ts

Reverts alphagov/di-authentication-account-management#667
- Reverting this PR as it did not solve the issue. This will also not work because this lambda only receives backchannel requests and therefore does not get redirected to the browser, so the browser will never know the LO cookie has been updated.

Revert "AUT-848 - Set logout cookie when global logout is successful"

---

src/components/global-logout/global-logout-controller.ts
src/components/global-logout/tests/global-logout-controller.test.ts
src/utils/subject-session-index.ts
src/utils/types.ts

- Implement getSessions as an asynchronously const
- Previously the getSessions const was implemented as an synchronously call but the response from the redisClient when calling ZRANGE was returned in an asynchronous callback. This meant when the globol-logout-controller called the getSessions method, nothing was being returned immediately and therefore no sessions were received.
- By making the getSessions an async call and also the call to getSessions in the global-logout-controller, we ensure that we wait for any results to be returned from redis before moving on.

AUT-848 - Implement getSessions as an asynchronously const

---

src/components/delete-account/delete-account-controller.ts
src/components/delete-account/tests/delete-account-controller.test.ts

- When a user has deleted their account we should remove all sessions assoicated with that user.
- Otherwise a user can still have an open session within account management and then when the user goes to perform an action the system will throw an error.

AUT-879 - Delete all sessions when account is deleted

---

.github/workflows/cd-only.yml
deploy/template.yaml

Previously this action would tag the Docker image as 'latest'. ECR handles this ok by saving the newly uploaded image as 'latest' and untagging the image that was previously 'latest'.
However when the CloudFormation template is applied, the running image in ECS isn't updated. I think this is for one of two reasons:
1. CloudFormation sees that ECS is already running an image tagged 'latest' and decides not to update it
2. ECS caches images and when the new task definition is started it uses the already cached 'latest' image, which isn't what we want.
Both of these can be prevented by tagging each image with a unique ID.
This PR changes the action to tag the image with the commit SHA in the same way as the action which uploads an image for the secure pipeline.
This means we no longer need …

BAU: Tag images for the dev environment with the commit SHA

---

ci/terraform/account-management-client.tf

Add new flag `OneLoginService` flag to client
- Amend the client registration to set the new `OneLoginService` flag to `true`
We have a variation of the "account not found" page which needs to be displayed for when the RP is Account Management or other internal One Login services
- [ACI-11](https://govukverify.atlassian.net/browse/ACI-11)

ACI-11: Add new flag `OneLoginService` flag to client

---

package.json
yarn.lock

BAU: Upgrade mocha to 10.0.1
Dev dependency 'mocha' upgraded to version 10.0.1, with corresponding transitive dependencies.
Remove dependency on vulnerable minimatch version.
https://security.snyk.io/package/npm/minimatch/3.0.4

BAU: Upgrade mocha to 10.0.1

---

ci/tasks/deploy-account-management.yml
ci/terraform/alb.tf
ci/terraform/redirect-lambda.tf

Fixes to the old deployment task and Terraform
- Fix the path to the lambda ZIP file in the Concourse deployment task
- Always create the redirect lambda resources
- Add an optional rule to the load balancer rather than changing the default rule
To remove the deployment errors being experienced into the staging environment, plus any future errors between the time the re-direct is switched on and the old infrastructure being retired.

AUT-895: Redirect Deployment Fixes

---

ci/terraform/redirect-lambda.tf

Minor fixes to Terraform
- Target group didn't include environment name
- Correct name of target group attachment
Deployment failed in build due to shared name

AUT-895: Make target group name environment specific

---

.gitignore
docker-compose.yml

We're going to be adding a bunch more localstack services.
the version we were on was 16 months old and a major version behind.
Let's make sure if we're looking at docs we're looking at the latest ones.
Pull this and with no other docker running do:
`docker compose up -d && docker compose logs -f`
visit localhost:6001, progress through sign in, and follow the redirects.
If you see the manage your account page, we're golden.
When you don't have a LOCALSTACK_VOLUME_DIR env var, a gitignored volumes directory appears in the repo
When you do, it appears instead at your env var location.

BAU: Upgrade localstack 1.2.0

---

ci/terraform/staging.tfvars

Update the CSLS endpoint in staging.
- Change the CSLS endpoint to the new `python` variant.
This should have changed a while ago, but seems to have been missed and has been highlighted by trying to deploy a new log group to staging.

AUT-895: Use correct CSLS in staging AM

---

src/components/resend-email-code/resend-email-code-controller.ts
src/components/resend-email-code/tests/resend-email-code-controller.test.ts

Show the user's new email address when sending a new verification code.
Note - this doesn't change any behaviour about which email we send the code to. That's already working as intended - it already correctly goes to their new email address.
This change only switches the email displayed to the user to the right one.
The only way a user can get a verification code sent to their email address by this app is while they're going through the journey to change their email address. The other credential and delete journeys require them to re-enter their password, but we never send a code to their email.
That means the only way a user can end up resending an email code is if they're trying to send a code to their new email address while they're in the process of switching. We should display their …

GUA-503: Show the user's new email when sending a new code

---

ci/terraform/production.tfvars

Switch production to redirect to the new infrastructure
- Set the override URL in `production.tfvars`
We are ready to switch over

AUT-895: Switch on redirect in production

---

src/assets/scss/application.scss
src/components/common/layout/base.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Implement changes after a UCD review of the new account navigation: 
- [add "Account" product name to header](https://github.com/alphagov/di-authentication-account-management/commit/7520b4a3a0dbc7e51471da6a6dc536a360fe1bcb)
- [update nav link hover state styles](https://github.com/alphagov/di-authentication-account-management/commit/8cd3b735ac8e0e06964b0e9d6f87d5f00e3098ce) 
- also adds the `$govuk-new-link-styles: true;` flag to the `application.scss` file. This enables the new DS link style with a thicker underline on hover, ensuring that the look of links is consistent across the account management app
https://user-images.githubusercontent.com/7116819/203791438-1db2e73f-d1f2-434b-be35-aea423ede0e1.mov

GUA-473: new header frontend tweaks

---

ci/terraform/route53.tf

Add weighting to the Route53 record for the `account.gov.uk` domain.
- Add the maximum weight to the DNS record for the apex domain `A` record.
To provide zero downtime as we move the apex domain to a new home, we are creating a second version of this record in a different repo, with a different weight. Once this is in place, we shall reduce the weighting in this repo to `0` and then destroy it, as a first step to decommissioning the old infrastructure.
- [AUT-909](https://govukverify.atlassian.net/browse/AUT-909)

AUT-909: Add weight to apex domain DNS record

---

deploy/template.yaml

Update the SAM Template and ensure the CloudFront Distribution, called CloudFrontDistribution using the CachingDisabled managed cache policy and removed unnecessary Checkov exclusion 
[ATB-141](https://govukverify.atlassian.net/browse/ATB-141)
Update the SAM template, specifically the CloudFront Distributions's Cache Policy Id, to use the managed `CachingDisabled` cache policy.
[INCIDENT-67](https://govukverify.atlassian.net/browse/INCIDENT-67)
[INCIDENT-67](https://govukverify.atlassian.net/browse/INCIDENT-67)

ATB-141: Using managed cache policy to disable distribution's cache

---

src/components/check-your-email/check-your-email-controller.ts
src/components/common/gov-uk-publishing/gov-uk-publishing-service.ts
src/components/common/gov-uk-publishing/types.ts
src/components/delete-account/delete-account-controller.ts
src/components/oidc-callback/call-back-controller.ts

Update the calls to GOV.UK's Account API to use the public subject ID. This is a new field returned in the userinfo response for this application. The public subject ID is the user ID the app currently gets as the subjectID, and it's also the user ID the GOV.UK relying party gets.
We want to change the subject ID for this app to the DI internal sector pairwise ID, but we also need the public subject ID so we can send notifications to GOV.UK when someone updates or deletes their account.
This PR stores the public subject ID in the user's session and updates all the calls we make to GOV.UK to use this ID.
Once this PR is merged we can safely change the subject ID returned to this app.

GUA-514: Send public subject ID to GOV.UK RP 

---

ci/terraform/production.tfvars

Reverts alphagov/di-authentication-account-management#728
We've fixed the issue that meant we needed to rollback to the old infrastructure, so we can safely restore the redirect and start serving production traffic again.

Revert "BAU: Switch off account management redirect"

---

src/assets/scss/application.scss
src/components/manage-your-account/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Implement updates to the account management area (renamed to "settings") to reflect the new One Login brand name as well as updates based on the [newest designs for the account](https://www.figma.com/file/Q6n44LmHFsCOGzZ44QTW4U/Account-home?node-id=2666%3A17539) which include a new services page.
https://github.com/alphagov/di-authentication-account-management/pull/662

GUA-462: Implement changes to manage your account area

---

src/components/delete-account/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Update content on the Delete your account page to bring it in line with the [latest Figma design](https://www.figma.com/file/Q6n44LmHFsCOGzZ44QTW4U/Account-home?node-id=3433%3A21903&t=fr9jXe6SJaPcSpo4-0). This is part of a series of changes to support the launch of the service dashboard.
~**WELSH content to be added as soon as we get back translations**~ Done
------

GUA-568: Implement content updates for delete page

---

.github/workflows/validate-sam-template.yml

Limit the python cryptography dependancy to version 38.0.4.
Build is pulling the latest python cryptography version 39.0.0 and this version no longer supports openssl version 1.1.0 or older.
[GitHub issue](https://github.com/aws/aws-sam-cli/issues/4527)
[Jira issue](https://govukverify.atlassian.net/browse/ATB-163)
[Successful build](https://github.com/alphagov/di-authentication-account-management/actions/runs/3829416921)

[ATB-163] Fix SAM Validate issue by using python cryptography dependancy version 38.0.4

---

src/assets/javascript/cookies.js

Push language and language code to the data layer as per PA request. This is so Performance Analysts have access to information on the currently selected language in GA.
I shamelessly copied the [current implementation](https://github.com/alphagov/di-authentication-frontend/blob/main/src/assets/javascript/cookies.js#L113) on `di-authentication-frontend` as we want our implementation of this to work exactly the same.

GUA-522: Update dataLayer push with language

---

src/assets/scss/application.scss
src/components/common/layout/base.njk

Firefox doesn't like the double negative margins between the DS header and the new account nav which is leading to some bizzare behaviour when zooming in and out where the nav links are jumping to the left/right at different zoom levels on Firefox.
This implements an alternative solution which instead of hiding the blue border at the bottom of the black bar by adding negative margins to the account nav, uses a modifier class which removes the bar and negative margins at the bottom of the header.
Also makes the container for the GOVUK logo and Account product name take up 100% of the width of the containing element. It was spotted that the "Account" product name collapses below the logo on certain breakpoints. Increasing the width of the container ensures this will not happen. …

BAU: fix header/nav issues

---

src/components/your-services/index.njk
src/utils/prettifyDate.ts
src/utils/types.ts
src/utils/yourServices.ts
test/unit/utils/prettifyDate.test.ts
test/unit/utils/yourServices.test.ts
yarn.lock

…
[GUA-615] convert epoch date to readable format for service cards
Instead of using the pretty date from the DB,  the service now ignores that value and instead converts the epoch date into a user readable format
- Added a prettifyDate util function
- Added last_accessed_readable_format field to Service interface
1. Pretty dates in the DB are wrong (see ticket for details)
2. Need to be able to display dates in welsh depending on user's language choice 
Testing with the service dashboards
[GUA-615]: https://govukverify.atlassian.net/browse/GUA-615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GUA-615: convert epoch date to readable format for service cards

---

src/components/session-expired/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Update the content on the "You have been signed out" page to provide more clarity as to the reasons the session might have ended.
It would be cool to show different content depending on why the user’s been signed out, but that would be more work than this really justifies at the moment. So instead we are listing all the reasons the user might have been signed out:
- have not used your account for more than 2 hours 
- signed out of your account while using another service

GUA-549: Content update on /session-expired

---

src/locales/cy/translation.json
src/locales/en/translation.json

The title of this page seems to have reverted back to "Your GOV.UK account" although it was definitely "Settings" when we tested it previously.
This changes the name of the page back to what it should be.

BAU: Fix page heading/title on Settings page

---

src/assets/scss/application.scss

The yellow background/outline of the link slightly overflows the boundaries of its container when the link is in focus. This is not necessarily on purpose and doesn't necessarily look great.
This fixes the issue, also replacing some hard coded values in the code with SASS variables.
https://govukverify.atlassian.net/browse/GUA-624

BAU: minor tweak to nav link focus state

---

ci/terraform/build.tfvars
ci/terraform/integration.tfvars
ci/terraform/staging.tfvars

Shutdown Auth AM instances in build, integration and staging.
Set the ECS desired count to 0.
Switch off autoscaling so the min and max counts do not override the desired count.
These have been replaced by Accounts team instances and there are no longer any dependencies on them in the Auth acceptance tests.
https://govukverify.atlassian.net/browse/AUT-911

[AUT-911]: Shutdown Auth AM instances in build, integration and staging.

---

src/app.constants.ts
src/app.ts
src/components/change-phone-number/index.njk
src/components/check-your-phone/check-your-phone-controller.ts
src/components/check-your-phone/index.njk
src/components/resend-phone-code/index.njk
src/components/resend-phone-code/resend-phone-code-controller.ts
src/components/resend-phone-code/resend-phone-code-routes.ts
src/components/resend-phone-code/tests/resend-phone-code-controller.test.ts
src/components/resend-phone-code/tests/resend-phone-code-integration.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Implement content updates on the Change phone number journey. These are from designs from Auth which are on their Figma (journeys we inherited)
One of the things missing was an entire page (the resend phone code page). In addition to the content changes to bring us in line with Auth's figma, this also adds the missing page to the journey.
Ticket and figma for more details on what has been added:
https://govukverify.atlassian.net/browse/GUA-612 
https://www.figma.com/file/0JbNRTnq5ibRtfg8BMxXDL/Accounts-design-thinking?node-id=293%3A5816&t=YPbBpFCcTxj4eZrt-0

GUA-612: change phone number journey content updates

---

.github/workflows/build-test-application.yml
.github/workflows/cd-only.yml
.github/workflows/main.yml
.github/workflows/pre-merge-checks-terraform.yml
.github/workflows/validate-docker-image.yml
.github/workflows/validate-sam-template.yml

Updating github workflow actions to versions written in Node 16.
Github is deprecating Node12 and for security deprecating the set-output function.
Checked workflows that are triggered when branch is pushed, when deploying to dev, and when raising PR. 
Workflows triggered on merge to main can only be confirmed when this PR is merged.

GUA-524 update github actions to versions that use node16

---

.github/workflows/build-test-application.yml
.github/workflows/sonarcloud.yml
package.json
sonar-project.properties

Changes to include Sonar cloud analysis and test coverage 
Addded a new github actions for dealing with sonarcloud
https://sonarcloud.io/summary/new_code?id=alphagov_di-account-management-frontend&pullRequest=805
Shows the coverage to be 79.3% after merge.
Needed Sonar to report on the coverage
Note:
I have moved the sonar related checks as another github action. If it makes sense to who is reviewing I can move them to build-test-application action.

GUA-618: Add sonarcloud analysis and coverage action

---

src/server.ts

Matched the Amazon Load Balancer configurations of the keepAliveTimeout values to the nodejs timeout values.
Adding configurations for keepAliveTimeout value and headersTimeout value to match ALB configurations of:
server.keepAliveTimeout = 61 * 1000;
server.headersTimeout = 91 * 1000;
The default of the nodeJS keepAliveTimeout is set at 5 seconds, but this needs to be extended in order to stop random 5XX and 4XX errors being emitted from the load balancers in front of the nodeJS ECS fargate containers. 
(https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3409903626/Load+Balancer+Errors) details the issue further.
The relevant ticket:  [[ATB-162]](https://govukverify.atlassian.net/jira/software/c/projects/ATB/boards/241?modal=detail&selectedIssue=ATB-162&assignee=635679e1fc0cc7a600ae …

ATB-162 Setting nodejs timeout values to match ALB config 

---

src/components/oidc-callback/call-back-controller.ts

we use the stringify method of querystring to stringify an object and form a URL to redirect the user to. This module (querystring) is deprecated, so we are substituting it with [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams).
We are only using querystring in src/components/oidc-callback/call-back-controller.ts, as such this is the only file changed. A new URLSearchParams object is instantiated passing the object with the query param in it. The direct URL is then formed in the same way as before but we append the output of URLSearchParams.toString() method
Because querystring module became deprecated
- [ATB-211](https://govukverify.atlassian.net/browse/ATB-211)
App deployed in local docker container. Run all tests successfully 
Also inserted log line to …

[ATB-211] - Fix 'querystring' as it is deprecated

---

src/locales/cy/translation.json

Somehow while implementing the updates renaming the account to One Login, the product name in the header was not updated for the Welsh language version of the content. This corrects the issue.

BAU: Correct product name in Welsh

---

src/components/change-phone-number/change-phone-number-controller.ts
src/components/change-phone-number/index.njk
src/components/change-phone-number/tests/change-phone-number-controller.test.ts
src/components/change-phone-number/tests/change-phone-number-integration.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

[GUA-629] update international phone number content
- correct content to match designs 
- fix bug with "same number" error showing on the UK phone field when user enters current number into international number field
- Content in Translations file 
- update template to remove lines 
- fix the href for same-number error to handle international phone number field 
Updated designs and bug fixes. 
Welsh content will be updated in a later ticket. 
Content is OK to merge to production as IPN content is hidden by feature switch. 
[GUA-629]: https://govukverify.atlassian.net/browse/GUA-629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GUA-629 update international phone number content

---

src/assets/scss/application.scss
src/components/manage-your-account/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Add new "How you get security codes" section to the settings page.
The ability to set up an account using an authenticator app for 2fa has existed for a while. 
This displays the user's current 2fa method on their account, as well as allowing the option to change the phone number if their current 2fa method is SMS. There isn't currently an option to change auth app since that functionality does not exist on the account yet. This is something we will have to iterate on in the future.
| Text  | App |
| ------------- | ------------- |
| ![Screenshot 2023-02-15 at 10 23 02](https://user-images.githubusercontent.com/7116819/219107935-588fa53f-f402-4205-a144-7be6f233b5ad.png)  | ![Screenshot 2023-02-15 at 10 22 28](https://user-images.githubusercontent.com/7116819/219107930-d8f967c1-51ff-48ed-8d …

GUA-517: add "How you get security codes" section

---

src/components/change-phone-number/change-phone-number-controller.ts
src/components/change-phone-number/tests/change-phone-number-integration.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

[GUA-630] welsh translation for international phone number
also tidy english translation 
- update welsh translations to match new english 
- adding full stop to english error message as requested by Mel 
- removed unnecessary repeat line in the english translation file 
The samePhoneNumber error is read by the controller. It only needs to appear once in the translation file for both UK and International number fields. So i've switched it to read from the UK array and removed the duplication from international errors array.    This is how it was originally set up so matches the welsh file. 
[GUA-630]: https://govukverify.atlassian.net/browse/GUA-630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GUA-630 welsh translation for international phone number

---

deploy/template.yaml

Defined the following Metric Filter and Alarm for both the API Gateway Access CloudWatch logs:
- API Gateway 4xx status errors in /apigateway/account-mgmt-frontend/access
- API Gateway 5xx status errors in /apigateway/account-mgmt-frontend/access
- API Gateway latency threshold in /apigateway/account-mgmt-frontend/access
I have enabled alarm actions to publish to our alerting SNS topics which in turn will send notifications to our `govuk-accounts-notifications` slack channel so we can monitor the sensitivity of the new defined alarms. Our PagerDuty endpoint has not yet been configured and therefore no notifications will be sent there yet. I recommend we hold off with PagerDuty integration until we are happy with the initial alarm thresholds.
**NOTE:** This PR should not be merged before …

ATB-113 Define Metrics and Alarms for API Gateway Access logs

---

package.json
src/assets/scss/application.scss

1. Optimise scss imports from the DS npm module so that only styles for components being used in the application are imported. Previously we were indiscriminately importing all styles including for components which are not currently used in the account management app.
2. Add load path to sass so that DS `scss` imports automatically resolve to their location in `node_modules`.
- [GUA-687](https://govukverify.atlassian.net/browse/GUA-687)
1. reduces unused CSS (128 kB -> 89.8 kB) and should marginally improve our performance score
2. makes our code nicer
[GUA-687]: https://govukverify.atlassian.net/browse/GUA-687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GUA-687: Adjustments to SCSS imports

---

deploy/template.yaml

Remove the actions to execute when API Gateway 5xx, 4xx, and Latency alarms transition to the OK state from any other state. We will now only receive slack notifications when the above alarms transition into an in `Alarm` state. 
This has been flooding our slack notifications channel and does not provide much value.
- [ATB-342](https://govukverify.atlassian.net/browse/ATB-342)
[ATB-342]: https://govukverify.atlassian.net/browse/ATB-342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ATB-342 Remove the actions to execute when alarm transitions to the OK state from any other state

---

deploy/template.yaml

Created a Dashboard titled AMFCloudWatchDashboard that includes metric graphs for ECS, ELB, and DynamoDB. 
Each Metric Graph: 
- 'API Gateway 4xx, 5xx Errors and Total Invocations' illustrates an overview of the amount of 4xx and 5xx errors in comparison to the total number of API Gateway invocations. A surge in either 4xx and 5xx errors for a set amount of time is a cause for concern to be investigated. Experiencing more requests than usual could indicate an endpoint returning an error message causing multiple re-entries on client side or if there are also less requests than usual, there could be a permissions issues withholding API calls. 
- 'API Gateway Latency' illustrates the maximum latency measured in milliseconds . This is important to track to ensure there is no significant lack …

ATB-65 Define and create CloudWatch dashboard

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

https://govukverify.atlassian.net/browse/GUA-660
Add the capability to have the "Sign your mortgage deed" card under "Other services you've used" on the "Your services" page.
This new card would not actually appear until the service has been onboarded (due to happen Monday morning 8am).
Content (such as updates to the account blurb) will be added in a separate PR. This PR can go forward at any point, whereas other content should probably go live at the same time as the service (or roughly at the same time)
[Figma for reference](https://www.figma.com/file/0JbNRTnq5ibRtfg8BMxXDL/Accounts-design-thinking?node-id=1252%3A13237&t=86knNaxy6x8Yht8k-0)

GUA-660: Add mortgage deed to service list

---

deploy/template.yaml

This PR disables all actions triggered by CloudWatch alarms until new thresholds are defined and tested.
Our first iteration of API Gateway alarms seem to be too sensitive and as a result have flooded our slack notifications channel.
Alarm actions have been disabled.
- [ATB-353](https://govukverify.atlassian.net/browse/ATB-353)
[ATB-353]: https://govukverify.atlassian.net/browse/ATB-353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ATB-353 Disable CloudWatch alarm actions until new thresholds are defined

---

package-lock.json
src/components/delete-account/delete-account-controller.ts
src/components/delete-account/index.njk
src/components/delete-account/tests/delete-account-controller.test.ts
src/components/delete-account/tests/delete-account-integration.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/utils/yourServices.ts
test/unit/utils/yourServices.test.ts
yarn.lock

re-merge (revert the revert) for [GUA-593] Customise Delete Screen 
(original PR https://github.com/alphagov/di-account-management-frontend/pull/851)
Also contains a fix for accounts and services being displayed that were not on the lists of allowed services. 
Change between this PR and the original PR can be seen in the commits. Now services retrieved from the DB are filtered and must be present in the hard-coded lists of services and accounts. -  See new function in YourServices and how getServices is no longer exported so can't be called outside of the YourServices.ts file. 
[GUA-593]: https://govukverify.atlassian.net/browse/GUA-593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Look at the second commit on this PR (4cd6e)
- Start by …

Gua 593 customise delete screen fix rebased

---

.github/workflows/dev-instance.yml
.github/workflows/validate-sam-template-dev.yml
.github/workflows/validate-sam-template.yml

Updated workflow features that are soon to be deprecated to the most recent versions as per [documentation](https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3353378864/GitHub+Actions+deprecation+alerts), this includes:
- Updating to aws-actions/configure-aws-credentials@v1-node16
- Deprecating the sam fix https://github.com/aws/aws-sam-cli/issues/4527 step as this is no longer required as a workaround as part of latest version of sam-cli 
All other features listed in documentation have already been updated.
Workflow features as specified in documentation above are to be deprecated and have therefore been updated to most recent versions.
- [ATB-198](https://govukverify.atlassian.net/browse/ATB-198)
[ATB-198]: https://govukverify.atlassian.net/browse/ATB-198?atlOrigin=eyJpIjoiNWRkNTl …

ATB-198 Update to-be deprecated workflow features to the most recent versions

---

src/components/your-services/index.njk
src/components/your-services/tests/your-services-integration.test.ts

A google lighthouse report I ran on the service dashboard has highlighted that on the services dashboard heading levels are not in a sequential order when the user only has accounts/services due to the fact that heading hierarchy skips from `h1` to `h3`  ( the `h2`s “Your accounts“/“Your services“ are not displayed unless the user has both accounts and services on their dashboard).
This introduces some simple logic which changes the heading level depending on context.
It also adds an integration test for **Your services** as the test was missing before.

GUA-696: tweak header hierarchy and add tests

---

.github/workflows/build-test-application.yml
.github/workflows/dev-instance.yml
.github/workflows/on-manual-publish-to-dev.yml
.github/workflows/on-merge-to-main.yml

Why? https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
But I agree with this:
https://michaelheap.com/improve-your-github-actions-security/
> I agree with Julien that using arbitary actions is a risk, but as
always it’s a compromise between security and making life easy for ourselves. Specifying a commit hash each time we want to upgrade could become painful very quickly, especially if you’re using a large number of actions.
With that in mind, I thought about how we could solve the problem with automation and came up with the following solution.
> TL;DR: Using GitHub actions with branch names or tags is unsafe.
Use commit hash instead
Runs the pin-github-action[2] tool across all our workflows to pin the new versions in this workflow
[2]: …

BAU pin action versions

---

src/components/your-services/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

As the list of services onboarded with One Login is becoming longer, it is also becoming less manageable.
This updates the list to a drop down design where the list of services is hidden by default.
Design in Figma: https://www.figma.com/file/0JbNRTnq5ibRtfg8BMxXDL/Accounts-design-thinking?node-id=1494-14364&t=ki5KV1a2TUjCVKwz-4
Also corrects the Welsh language version of the DBS link –  it should be linking to the Welsh version of the service, not the English one.

GUA-723: move to drop down version of service list

---

package-lock.json
package.json
yarn.lock

Seems the breaking change here was about typescript definitions.
But seems internal to them 🤔 
So if this compiles then OK:
See here: https://github.com/i18next/i18next/releases/tag/v22.0.0

BAU: Update i18next to v22.4.13

---

.github/workflows/require-pinned-github-actions.yml
.github/workflows/sonarcloud.yml
.github/workflows/validate-docker-image-dev.yml
.github/workflows/validate-docker-image.yml
.github/workflows/validate-sam-template-dev.yml
.github/workflows/validate-sam-template.yml

Why? https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
But I agree with this:
https://michaelheap.com/improve-your-github-actions-security/
> I agree with Julien that using arbitary actions is a risk, but as
always it’s a compromise between security and making life easy for ourselves. Specifying a commit hash each time we want to upgrade could become painful very quickly, especially if you’re using a large number of actions.
With that in mind, I thought about how we could solve the problem with automation and came up with the following solution.
> TL;DR: Using GitHub actions with branch names or tags is unsafe.
Use commit hash instead
So let's add checks to pin github action versions to ones we trust enough to use, and then run the pin-github-action[2] tool to pin the new …

BAU: Check for pinned versions by SHA when running github actions

---

.github/dependabot.yml

We're not ready to make that leap yet and it adds PR noise
see here: https://github.com/alphagov/di-account-management-frontend/pull/870

BAU: Stop depbot suggesting alpine 19 node version

---

src/components/change-email/index.njk
src/components/change-email/tests/change-email-integration.test.ts
src/components/change-password/tests/change-password-integration.test.ts
src/components/change-phone-number/index.njk
src/components/change-phone-number/tests/change-phone-number-integration.test.ts
src/components/check-your-email/index.njk
src/components/check-your-phone/index.njk
src/components/check-your-phone/tests/check-your-phone-integration.test.ts
src/components/common/errors/500.njk
src/components/common/show-password/macro.njk
src/components/delete-account/index.njk
src/components/delete-account/tests/delete-account-integration.test.ts
src/components/enter-password/tests/enter-password-integration.test.ts
src/components/manage-your-account/index.njk
src/components/manage-your-account/tests/manage-your-account-integration.test.ts
src/components/your-services/tests/your-services-integration.test.ts
test/utils/helpers.ts

Update integration tests to use data attribute selectors instead of IDs. 
Remove string checking unless it's relevant to the test (for instance I've left them on the tests dedicated to checking that the specific error messages displayed are correct in different circumstances)
Nothing should change and all the tests should still pass.
https://govukverify.atlassian.net/browse/GUA-760

GUA-760: Refactor integration tests

---

src/components/change-password/index.njk
src/components/common/show-password/macro.njk
src/components/enter-password/_change-email.njk
src/components/enter-password/_change-password.njk
src/components/enter-password/_change-phone-number.njk
src/components/enter-password/_delete-account.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Tweak content on the "Enter your new password" screen to be more in line with the changes auth have implemented. 
The content is more or less the same as before, except now it is delivered as hint text before the input field.
Change the way the ShowPassword component works so that it accepts named parameters instead of nameless ones, for improved readability.
https://govukverify.atlassian.net/browse/GUA-848

GUA-848: update hint text on Enter new password

---

deploy/template.yaml

Switch conditionals on autoscaling infrastructure from IsProduction to IsNotDevelopment. THus enabling autoscaling in build, staging and integration. 
Remove IsProduction parameter as nolonger needed. 
So performance tests can get realistic production-like behaviour in the test environments. 
[GUA-864]
[GUA-864]: https://govukverify.atlassian.net/browse/GUA-864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GUA-864 autoscale all environments except dev

---

src/components/delete-account/delete-account-controller.ts
src/components/delete-account/delete-account-service.ts
src/components/delete-account/tests/delete-account-controller.test.ts
src/components/delete-account/tests/delete-account-service.test.ts
src/components/delete-account/types.ts

Update AM to send the public subject id on the SNS topic . Which will be then consumed by the delete-email-subscriptions lambda on the backend .
Remove the call to the publishing API from the delete controller 
The backend changes to add a new lambda went live a while back and this change is to make sure the front-end is using the backend lambda to delete the email subscriptions instead of calling the publishing API directly .

OLH-890 : Refactor the way Deletion happens for publishing service

---

.github/PULL_REQUEST_TEMPLATE.md

Our team's Jira prefix is now OLH.
We don't need to put a link to the Jira ticket in the PR description - as long as the branch, commit or PR title starts with the ticket ID (eg. OLH-1234) then Jira will pick it up and link them automatically.
Remove the TODO link for application configuration.
Remove the requirement to tell the tech lead if the Dockerfile changes. I don't think we've ever done that or need to.
Add a new testing section to describe any manual testing that's been done.
Remove the other considerations section. If we think any of these are necessary they should be part of the acceptance criteria on the Jira ticket.
Add a new how to review section to explain any non-standard steps or areas the author isn't sure about eg. asking for clarification on a language feature or …

BAU: Update pull request template

---

src/components/change-password/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Add distinct programmatic labels for the Show Password component on the second password field on the "Enter your new password" page.
The first password component is still using the default labels while the Show Password component associated with the "confirm password" field is using different labels/hidden text to reflect that this is a retyped password.
No visible change will occur as a result of this update.
This is so that screen reader users can more clearly discern which of the Show/Hide buttons is associated with each password field.
Some context for this update https://github.com/alphagov/govuk-design-system/issues/2795 
- [OLH-869](https://govukverify.atlassian.net/browse/OLH-869)
[OLH-869]: https://govukverify.atlassian.net/browse/OLH-869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlh …

OLH-869: Change show password component hidden labels on the "Enter your new password" page

---

src/locales/cy/translation.json
src/locales/en/translation.json

Update the URL shown in service cards for the apprenticeships service
The previous URL was sending users to the service start page in production only, which wasn't signing users in by default. This new URL will do that and give a seamless experience for our users
[Onboarding ticket](https://govukverify.atlassian.net/browse/OLH-932)

OLH-932: Update Apprenticeship service URL

---

src/config/helmet.ts

It was reported that when the `/delete-account` form was submitted, the page would hang instead of redirecting to the confirmation page.
The POST request showed up in the network tab with the correct location and status code, and the account deletion was performed correctly so we narrowed down the issue as being a CSP one.
The issue came from a helmet upgrade where the `form-action` directive is now set to `self` by default meaning that redirects to the oidc subdomain were blocked.
https://github.com/helmetjs/helmet/blob/main/CHANGELOG.md#500---2022-01-02
This adds subdomains of account.gov.uk to the `form-action` directive which should fix the issue.
I have tested this manually in dev by checking the CSP in the network tab, and completing the journey of deleting my account.

BAU: Update form-action directive in CSP

---

deploy/template.yaml

Use the SSM parameter to connect to the OIDC stub for dev and build .

Update API_BASE_URL to use the OIDC stub in Dev and Build

---

src/locales/cy/translation.json
src/locales/en/translation.json

The link in the account blurb for Apprenticeship service was pointing to incorrect location.
This link was updated from https://employerprofiles.manage-apprenticeships.service.gov.uk/user/add-user-details?_ga=&_gl=&utm_source=&utm_campaign=&utm_medium=&utm_keywords=&utm_content= to https://www.gov.uk/sign-in-apprenticeship-service-account

Update link to Manage apprencetiship in the account blurb

---

src/locales/cy/translation.json
src/locales/en/translation.json

Add a URL parameter to all links to GOV.UK email subscriptions.
Also correct the environments - GOV.UK's integration environment uses our staging one, and their staging uses our integration. 
The GOV.UK email subscriptions service currently has two ways to authenticate a user. Adding this URL parameter to links from the GOV.UK One Login home allows the email service to know that that user should be authenticated through GOV.UK One Login.
This means the user can skip a step when signing into the email service as it no longer needs to work out which authentication method to use.
I've run the app locally and checked the URL parameter was present.

OLH-950: Update link to GOV.UK email subscriptions

---

.github/dependabot.yml

Use the new ['groups' feature]([1]) from Dependabot to group together minor and patch updates. I've put the development and production dependencies in separate groups. This means we'll get one PR with all the development updates and a second with all the production ones.
Any library update which is a major change as indicated by semver will still get its own PR.
This should mean we have fewer PRs from dependabot to manage while still being able to tackle the major version upgrades easily.
Github has syntax checking built in for Dependabot config files, so if that's happy this is probably a valid config. Please check against the documentation to be sure though!
[1]: https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/

BAU: Group minor and patch upgrades

---

sonar-project.properties

Use Sonar's analysis scope feature[^1] to exclude the test files from the source code analysis, and include them for test code analysis.
Sonar is currently reporting 28% code coverage from our tests, but mocha reports ~80% live coverage. This is because Sonar is including the `*.test.ts` files as source code, not test code.
Check that the latest Sonar run for this branch is happy. We only run coverage tests against the `main` branch, so we'll need to wait until this PR is merged to see if this has helped.
[^1]: https://docs.sonarsource.com/sonarqube/latest/project-administration/analysis-scope/

BAU: Exclude tests from Sonar analysis

---

deploy/template.yaml

Enable the API Gateway 5XX error alarm
This alarm triggers when more than 1% of responses from API Gateway are a 5XX status code, as long as there have been a minimum of 10 responses in two out of the last 5 minutes.
The most likely reason for this alarm to trigger is the frontend either being down completely or having some other problem that needs attention.
This closes a gap in our monitoring of the frontend to provide a proactive notification to us if there's a problem.
In its current configuration, this alarm sends a slack message to the `#govuk-accounts-notifications` channel. In the future we should update it to also send alarms in production to `#di-2nd-line`. 
This PR partially addresses [risk OLH-900](https://govukverify.atlassian.net/browse/OLH-900)
We've had this alarm set up …

BAU: Enable the API Gateway 5XX error alarm

---

.env.sample
README.md

Update the instructions for running the app locally. See each commit for details on all the changes.
We have some new people joining the team soon and the instructions here were written when we needed to register an actual OIDC client to use in the frontend. Now we have the stub OIDC services it's a lot simpler so we can also simplify the documentation.
Note there may still be some changes needed to the local DynamoDB / service cards documentation. I've intentionally not changed that here as I need to do some more thinking as to how we handle user IDs via the stubs. 
I have also been updating the tech team manual - https://github.com/alphagov/digital-identity-team-manual/pull/327
N/A - no application changes.
Check the changes make sense and there aren't any typos or other mistakes.

OLH-1139: Update instructions for running the app locally

---

.env.sample
deploy/template.yaml
src/app.ts
src/components/webchat-demo/index.njk
src/components/webchat-demo/webchat-demo-controller.ts
src/config.ts
src/config/helmet.ts

Use the supplier's dev webchat environment for local testing and in our dev environment. I also had to make some further CSP changes to allow it to inject more scripts and styles. These include the `'unsafe-inline'` directive which I don't want to allow in production as it makes us much more vulnerable to attacks like XSS [^1]. 
We can hopefully work with the supplier to use hashes or nonces to secure the scripts they load for production. In the meantime, I've put the CSP changes for webchat behind the feature flag so we can deploy this change and still use the stricter CSP.
They've added our dev domain to their allowlist so we can start testing how the webchat will work.
I've run the app locally, gone to `/webchat-demo` and checked the console for errors.
[^1]: …

BAU: Use the dev environment for webchat

---

src/components/contact-govuk-one-login/contact-govuk-one-login-controller.ts
src/components/contact-govuk-one-login/tests/contact-govuk-one-login-controller.test.ts
src/utils/strings.ts
test/unit/utils/strings.test.ts

[OLH-1153] append contact centre params from mobile to session data so they can be used in the contact form link 
- Made generic function getValueFromRequestOrSession for extracting fields from the request query or the session
- this validates the request param with a simple saftey regex before including in the session or page data 
- added the mobile specific fields appSessionId, appErrorCode, & theme
unit tests and deployed to dev to confirm FE is accepting the query params and adding them to the session
[OLH-1153]: https://govukverify.atlassian.net/browse/OLH-1153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1153 append contact centre params from mobile to session data

---

src/components/contact-govuk-one-login/contact-govuk-one-login-controller.ts
src/components/contact-govuk-one-login/tests/contact-govuk-one-login-controller.test.ts
src/utils/strings.ts
test/unit/utils/strings.test.ts

`[OLH-1114] Extract fromUrl from request param or session for Contact Centre Page`
Check query param and session for a valil fromUrl. If not present then return an error page and log the error. 
- [/] No environment variables or secrets were added or changed
Unit tests. 
Deployed to dev and saw page loading in all scenarios. Can't yet test the link to contact form because the link will be created on a different ticket.
[OLH-1114]: https://govukverify.atlassian.net/browse/OLH-1114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1114 Extract fromUrl from request param or session for Contact Centre Page

---

src/components/contact-govuk-one-login/contact-govuk-one-login-controller.ts
src/components/contact-govuk-one-login/index.njk
src/components/contact-govuk-one-login/tests/contact-govuk-one-login-controller.test.ts
src/utils/referenceCode.ts
src/utils/strings.ts
test/unit/utils/referenceCode.test.ts
test/unit/utils/strings.test.ts

When a user visits the triage page, generate them a reference code and display it on the page. This code is saved to the user's session so they don't get multiple codes if they open several tabs or navigate away from the page and then return.
We also log this code along with information from the user's session. 
When a user calls our contact centre we need a way to link their phone call to a web or app session. The agent will ask them to read out the reference code and will note it on the support ticket. Logging this code along with the session IDs means someone on 2nd line support can search for the code on a support ticket, find the session IDs and then use those to search for the rest of the user's journey in GOV.UK One Login. 
Note we don't log the user's user ID - we consider this …

OLH-1115: Generate and log phone reference code

---

src/app.constants.ts

Change the triage page URL from `/contact-govuk-one-login` to `/contact-gov-uk-one-login` (note the `govuk`).
We intended to put a hyphen in the URL here, and have told other teams that the URL will be `...gov-uk...`. It's easier for us to update the URL here rather than getting all the other teams to make another change.
This page isn't live yet so we don't need a redirect from the old to new URL.
I've run the app locally to check for syntax errors in the config.

BAU: Update triage page URL

---

src/components/contact-govuk-one-login/contact-govuk-one-login-controller.ts
src/components/contact-govuk-one-login/tests/contact-govuk-one-login-controller.test.ts

[OLH-1151] capitalise fromULR in contact email link param
Parameter name is case sensetive and isn't getting picked up by the email contact page as it's lower case
locally
[OLH-1151]: https://govukverify.atlassian.net/browse/OLH-1151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

capitalise fromULR in contact email link param

---

deploy/template.yaml
src/components/contact-govuk-one-login/contact-govuk-one-login-controller.ts
src/components/contact-govuk-one-login/index.njk
src/components/contact-govuk-one-login/tests/contact-govuk-one-login-controller.test.ts

Put the webchat widget on the triage page behind the existing feature flag. The supplier's docs for the webchat ask us to put it in the `<head>` section, but this is the same implementation as on the previous webchat demo page - it works fine in the `<body>` and is much easier to implement in our templates.
See #1052 and #1056 for the implementation of the webchat demo page.
I've run this locally and verified the webchat opens when I click the widget. ~~Note that the supplier hasn't added any of our domains to their allowlist yet, so this will only work when running the app locally.~~ They've now added our domains to the allowlist so this will work up to staging.

OLH-1168: Put the webchat widget on the triage page

---

package.json
src/assets/javascript/tests/cookies.test.js

Add an example test for client side JS.
There's a new npm script (`npm run test:js`) that runs mocha looking for *.test.js files in the assets directory.
The example tests use the same `chai` and `mocha` runner and framework that the Typescript tests use. We need to use CommonJS syntax rather than the `import {expect} from "chai"` ES6 syntax, but that's a difference we can manage.
I've not yet added this script to the list of ones which are run in `npm run test` - we can do that once we have some more substantial tests.
We need to have unit tests for our client side JS before we do any significant work on either the webchat or GA4.
Run the new tests with `npm run test:js`
I've done very little work with client side JS. This looks sensible to me and the [Chai …

OLH-1165: Add an example client side JS test

---

src/app.ts
src/components/common/layout/base.njk
src/locales/cy/translation.json
src/locales/en/translation.json
src/middleware/outbound-contact-us-links-middleware.ts
test/unit/middleware/outbound-contact-us-links-middleware.test.ts
test/unit/utils/strings.test.ts

OLH-1154 - Add a link to support from the home.account footer
User Story: https://govukverify.atlassian.net/browse/OLH-1154
Change in English and Welsh translation.js to accommodate internationalisation.
Add new element in Nunjuck to include the support link
Images of the before and after can be seen in https://govukverify.atlassian.net/browse/OLH-1154
So users who are signed in and who need help have somewhere to go.
N/A
I viewed the home account in English and Welsh translation and verified new link is added successfully and clickthrough goes to the correct page.
Deployed to Dev environment and demoed with Ben Mortimer (Product Owner).
The new support link in the footer should be clicked, open in a new tab and ensure it goes to the one login contact page.
Verify the URL contains the …

OLH-1154 - Add a link to support from the home.account footer

---

deploy/template.yaml
src/components/contact-govuk-one-login/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Adds links to the newly published Whitehall guidance to the new contact triage page.
Enables the guidance section in all environments. 
Ensures that privacy notice is only displayed when webchat and/or phone are enabled.
https://govukverify.atlassian.net/browse/OLH-1191 
The contact triage page went live yesterday with contact form only and without the guidance links, as guidance had not been published yet.
Now that guidance has been published, this section can be switched on. 
- checked that the English language links all lead to the English language versions of the Whitehall guidance
- checked that the Welsh links lead to the Welsh version of the guidance
- checked that the privacy notice section only displays when phone or webchat are enabled
Perhaps double check all the above

OLH-1191: add guidance links to contact triage page

---

docker-compose.yml
localstack/provision.sh
package-lock.json
package.json
src/components/contact-govuk-one-login/contact-govuk-one-login-controller.ts
src/components/contact-govuk-one-login/event-service.ts
src/components/contact-govuk-one-login/tests/contact-govuk-one-login-controller.test.ts
src/components/contact-govuk-one-login/types.ts
src/config/aws.ts
src/utils/sqs.ts
src/utils/types.ts
test/utils/sqs.test.ts

Send an Audit Event via SQS to TxMA.  The audit event is emitted whenever someone visits the contact page.  
The controller now calls out to a new EventService which sends messages via SQS.  The controller has been refactored and had some clarifying functions added.
Testing the controller has been done by creating a stub for the SQSClient.  This means the controller test knows too much about the way the EventService works but we will address this when we review the over all design with @alex9smith as a number of other areas where we can improve have been identified.
To support the requirement to record an audit event with TxMA.  The interface to TxMA is via SQS.
This has been tested in the DEV environment.  The logs from the ECS service show when the message is sent to TxMA.  The SQS …

Olh 1122 emit an audit event when a user visits the triage page

---

src/components/contact-govuk-one-login/contact-govuk-one-login-controller.ts
src/components/contact-govuk-one-login/tests/contact-govuk-one-login-controller.test.ts

Switch to getting the session IDs from the response locals instead of the session data.
This PR also includes some automated linting changes. I've put these in a separate commit to make it easier to see the change of logic.
The session ID and persistent session ID are stored in the response locals, not the user's session data.
This means that we were always sending an empty string for these values in the audit and log events.
I've run the app locally and verified I can see the session IDs in the log events: 
```
account-management-frontend  | [Node] [14:42:54.456] INFO (di-auth-account-management/662): User visited triage page
account-management-frontend  | [Node]     referenceCode: "905380"
account-management-frontend  | [Node]     appSessionId: ""
account-management-frontend  | [Node] …
```

OLH-1200: Get session IDs from locals

---

src/components/contact-govuk-one-login/contact-govuk-one-login-controller.ts
src/components/contact-govuk-one-login/tests/contact-govuk-one-login-controller.test.ts

Add timestamp to audit event.
The audit event being sent to TxMA now creates a timestamp rather than trying to retrieve one from the session.
The timestamp is a mandatory field that causes TxMA to send event to the DLQ if missing.  The session did not contain a timestamp so we have changed to generating one at the time the event is created.
I tested in DEV.  I could see the new audit event had a timestamp.  I did not see the event on the DLQ.

OLH-1122 - add missing timestamp to audit event.

---

src/assets/scss/application.scss
src/components/contact-govuk-one-login/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

JIRA for more detail: https://govukverify.atlassian.net/browse/OLH-1169
[OLH-1169: Launch webchat from "Use webchat" link](https://github.com/alphagov/di-account-management-frontend/commit/f0828e5fb304c15c8d8b5779c84b5c18862159ba) 
Enable launching the webchat from the "Use webchat" link on the page.
Even though the element looks like a link, the markup for `<button>` has been used in order to make it semantically correct. 
The reason it should be a <button> instead of an <a> even though it looks link like is that its purpose is not navigational – it has no `href`
https://github.com/alphagov/di-account-management-frontend/assets/7116819/45659b5b-2be9-44e0-8153-b33f69ad48ec
[OLH-1169: \</br> should be \<br>](https://github.com/alphagov/di-account-management-frontend/commit/2c08344d93a857a34 …

OLH-1169: launch webchat from link on triage page

---

src/app.constants.ts
src/components/oidc-callback/call-back-controller.ts
src/components/oidc-callback/tests/callback-controller.test.ts

When an access denied error is sent from auth-frontend, rather than handling the error, we let it propagate which triggers another error and causes a 500 error to be thrown rather than the workflow for handling access denied errors.
JIRA Ticket: https://govukverify.atlassian.net/browse/OLH-1123
In auth-callback controller, we check the query params for access denied error, if founds, we will then update the response status to 403.  This triggers the internal-error-handler and redirects to the configured session expired page.
Also this will stop the triggering of the [CloudWatch Alarm | account-mgmt-frontend-ApiGateway5xxStatusAlarm | eu-west-2 | Account: 026991849909](https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#alarm:name=account-mgmt-frontend-ApiGateway5xxSta …

OLH-1123 - Return a 403 error when a user fails to sign in

---

src/components/change-email/change-email-validation.ts
src/components/change-email/tests/change-email-integration.test.ts

[OLH-1155] Email update journey strips fullstops from gmail addresses
Update to the options for normalizeEmail validator
Full stops were being removed from email addresses
Added unit tests to cover those scenarios
[OLH-1155]: https://govukverify.atlassian.net/browse/OLH-1155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1155 Email update journey strips fullstops from gmail addresses

---

src/assets/scss/application.scss
src/components/contact-govuk-one-login/index.njk

Display the "Use webchat" link only once Webchat is actually available
to use.
There are a number of things that could potentially go wrong: poor
network conditions meaning that the chat is slow to load, JS disabled in
the browser, or a breaking error with the chat preventing it from
loading for instance. In all of these instances, displaying the "Use
webchat" link unconditionally could result in users attempting to
interact with it and having a frustrating experience when clicking it
does not produce any outcome.
To display the link conditionally, I listened for the `CHAT_LOADED` event
dispatched by the webchat script. Seeing as the webchat script loads
somewhat asynchronously however, that means that the `SaEvents` object
is not immediately available to subscribe to. The way I got …

OLH-1209: "Use webchat" conditional display

---

src/components/common/layout/base.njk
src/components/contact-govuk-one-login/contact-govuk-one-login-controller.ts
src/components/contact-govuk-one-login/index.njk
src/components/contact-govuk-one-login/tests/contact-govuk-one-login-controller.test.ts
src/config/helmet.ts

[OLH-1184] - Try strict-dynamic directive for the web chat 
Change our  Content Security Policy (CSP) to **_strict dynamic_** to prevent cross site scripting. 
This change will NOT support older browser versions that does not support strict dynamic. As that will mean the site is still susceptible to CSS attack with older versions.
JIRA Ticket: https://govukverify.atlassian.net/browse/OLH-1184
- Make nonce available to frontend
- Include a nonce in the <script> tags that load the initial webchat script
- Switch the webchat from using the ‘unsafe-inline' Content Security Policy (CSP) directive for scripts to 'strict-dynamic'.
- Test to ensure all required scripts are still loading  even with **_strict dynamic_** configured
Using 'unsafe-inline' for scripts in the CSP is an unacceptable …

OLH-1184 - Try strict-dynamic directive for the webchat

---

deploy/template.yaml

Enable webchat in integration
We thought our suppliers had access to the GDS VPN and therefore could access the webchat in our IP-restricted staging environment. That's turned out not to be true.
We could gather their IP ranges and add them to the allowlist, but it's easier to simply enable the webchat in integration where we don't restrict by IP address.
N/A

BAU: Enable webchat in integration

---

src/locales/cy/translation.json
src/locales/en/translation.json

Remove LITE from the services you can use list on the Your services page
Removed the link to the LITE service from the translations object for English and Welsh
The LITE link on this list links into the authenticated part of their service which means a user who clicks on this link gets signed in to LITE and gets a service card for them, which may be accidental.
LITE are still in private beta so don’t have a start page we can link to from this list. Their being in private beta also means we probably shouldn’t be linking to them from this list anyway.
[
](https://govukverify.atlassian.net/browse/OLH-1219)
Navigate to 
1. https://home.staging.account.gov.uk//your-services?lng=cy
2. https://home.staging.account.gov.uk//your-services?lng=en
In both pages, you should not see the LITE service …

OLH-1219: Remove LITE from Services you can use list

---

deploy/template.yaml

Set up a new [condition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html) to track which environments we want to send logs to Splunk via the CSLS, and apply it to the task and API Gateway log groups. This condition is only true in staging, integration and production, so now we won't send logs to Splunk in our dev or build environments.
We run our performance (load) tests in build and these generate several GB of logs each run. We share the daily Splunk ingest quota with all of Cabinet Office and we're regularly hitting that quota which means we've been asked to stop sending logs to Splunk when we run performance tests.
It's much simpler to simply not send logs to Splunk in build at all. If we need to look at application logs for any reason …

OLH-1190: Don't export logs to Splunk in build

---

.github/workflows/build-test-application.yml

Use localstack v3.0.0 in the Github actions pipeline.
This is required because we use the `ubuntu-latest` action runner which has just switched over to a new version of Ubuntu. The new version has a boto that's incompatible with the old version of localstack we were using previously.
Note this doesn't change the version of localstack we use for local development. This version works in the pipeline, and the main priority is getting that unblocked. We can come back and upgrade the version in `docker-compose.yml` later.
See @andrew-moores work on https://github.com/alphagov/di-account-management-frontend/pull/1108
If the tests pass, this is a success.

OLH-1261: Use the latest version of localstack in the Github actions pipeline.

---

src/app.constants.ts
src/components/contact-govuk-one-login/tests/contact-govuk-one-login-controller.test.ts
src/services/event-service.ts
src/services/types.ts
test/unit/services/event-service.test.ts

Add two new fields to the audit events emitted by the triage page - `user.user_id` and `extensions.is_signed_in`.
This also changes the string we send for session etc. IDs when a user is signed out. This will make it more obvious to TSD if the session is missing because of a bug when sending the event, or if the user is signed out.
The Technical Service Desk have requested we add the user ID to help them match events between sessions / users. The user ID will be hashed by TxMA, so we also add a new field to the unhashed `extensions` object that will tell TSD if a user is signed in when we sent the event.
I have deployed this branch to dev and
1. Signed in, then visited the triage page
2. Verified the event is still sent to the audit queue
3. Read the contents of the event and verified it …

OLH-1262: Include user IDs in triage page audit events

---

CODEOWNERS
README.md
deploy/template.yaml
docs/adr/0001-record-adrs.md
sonar-project.properties

As part of transferring ownership of repo from alphagov to govuk-one-login (a trust initiative) this PR has updated any old package references to point to new location.
A Trust Initiative
[OLH-1128](https://govukverify.atlassian.net/browse/OLH-1128)
Github actions, templates, references and repo
N/A
[OLH-1128]: https://govukverify.atlassian.net/browse/OLH-1128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1128: updated from alphagov to govuk-one-login

---

src/components/track-and-redirect/tests/tract-and-redirect-route.test.ts
src/components/track-and-redirect/track-and-redirect-route.ts
test/utils/helpers.ts

Updates to track-and-redirect-controller to include error checking for undefined session or queryParameters. Corresponding tests have also been updated to check this new error handling behaviour. The changes help prevent potential crashes due to undefined values and will redirect users if page is trying to be accessed directly.
Dynatrace has picked up some 500 status codes on the frontend for the /track-and-redirect route. 
Tested locally
When user navigates to /track-and-redirect page directly it will be redirected to /contact-gov-uk-one-login

OLH-1294 Add error handling for undefined session or queryParameters

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

OLH-1293 - Onboard RP: GBIS (Great British Insulation Scheme)
Config updated, English and Welsh translations updated to include new RP
So that the new GBIS is present as a service card when the service has been visited previously.
https://govukverify.atlassian.net/browse/DOT-433
Currently deployed to dev or can be run locally.

OLH-1293 - Onboard RP: GBIS (Great British Insulation Scheme)

---

src/assets/scss/application.scss

When browser zoom is applied, the chat button takes up a very large proportion of the viewport, obfuscating content and making the page difficult to navigate. 
There is also a separate issue when text zoom is applied where the text inside the notification counter becomes hard to read. 
This is an attempt to fix both those issues and making the button scale better by using relative units to set max and min dimensions on the relevant elements.
Ideally this type of issue should be addressed on the vendor's side. It's a brittle solution as these fixes could stop working or break the chat button (worst case scenario)  if class names of the elements are updated, or the approach to CSS changes on the vendor's side of things which we have zero control over. This is an interim attempt to address …

OLH-1304: Ensure chat icon scales better on zoom

---

src/config/aws.ts
src/utils/sqs.ts

Change the frontend so that it doesn't create a new SQS client every time it needs to publish an event.
Introduced a new singleton SQS client object.
In prod we are seeing CredentialsProviderError which we think is due to the existing pattern of creating a new SQS client every time an event is published.  
It is deployed in dev.  I have visited the triage page several times and seen audit events published each time.  I visited the page over a period greater than an hour to check that the temporary creds that the client obtains are refreshed.
The error was seen in the build environment when running a performance test against the triage page.  To gain confidence this fixes the issue we could run the perf test over a longer period than previously run.

OLH-1336 Use a singleton for the SQS client.

---

src/utils/logger.ts

This adds the /healthcheck route to the list of paths for the logger to ignore.
The log message does not add any real value and clutters up the logs.
I have run this locally; and verified that without the change, a log item appears when the endpoint is hit. And with the change, the log item does not appear.

[OLH-1317] Reduce number of logging messages by excluding the healthcheck

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

[OLD-1368] Add support for HM Armed Forces Veteran Card
- Add `veteransCard` as an allowed clientID
- Show a link to the veterans card page when the user has that in their recent activity
- Display veterans card link in the "Services you can use with GOV.UK One Login" List
- Add Welsh translation
The Veterans Card service is going live soon, and we need to support it
Verified that the link shows when the activity is present, and that the links work

OLH-1368 - Onboard Veterans Card.

---

.env.sample
deploy/template.yaml
src/assets/scss/application.scss
src/components/contact-govuk-one-login/contact-govuk-one-login-controller.ts
src/components/contact-govuk-one-login/index.njk
src/components/contact-govuk-one-login/tests/contact-govuk-one-login-controller.test.ts
src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

We have been asked to publish "emergency messaging" on the contact
triage page in the event that the contact centre is overwhelmed by
calls.
This is a preemptive measure ahead of the Veterans ID card service, a
high profile service, onboarding with OL soon.
Welsh language version still TBD. This adds the English language version
of the content in the Design System "warning text" style.
The warning is behind a flag which is currently switched off in all envs except dev. 
https://govukverify.atlassian.net/browse/OLH-1375
Done manual testing locally checking the content and visual appearance against the mockup provided. 
Please sense check the feature flag and confirm that the content is correct.

OLH-1375: Emergency messaging

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

**DO NOT MERGE (YET)**: The Early Years Child Development Training has a target go-live date of ~31st January 2024~ February 5th 2024.
This adds the Early Years Child Development Training service card to the account dashboard, and to the list of services that can be used with OL. 
This service is onboarding on the ~31st~ 5th of February. 
https://govukverify.atlassian.net/browse/OLH-1378
https://govukverify.atlassian.net/browse/DOT-478 
Check the content being added against the information in the JIRA ticket.

OLH-1378: Add Early Years Child Development card

---

src/assets/scss/application.scss
src/components/common/layout/base.njk
src/components/common/layout/header.njk
src/components/common/layout/navigation.njk
src/components/logout/logout-controller.ts
src/components/logout/logout-routes.ts
src/components/logout/tests/logout-controller.test.ts

Change sign-out link from GET to POST request
There were two sign-out links, one inside the header and another one on the navigation. Both links were changed to buttons
The use of POST for a logout feature is strongly recommended to enhance security, adhere to web standards and HTTP specifications, and ensure a better user experience. It mitigates the risk of CSRF attacks, keeps user actions intentional, and aligns with the principles of safe web navigation.
Tested locally for both signed in and not signed in users to make sure the link only appears on logged in users only.
/sign-out path does not work any more unless it's a valid POST request
Replicate the testing above in different environments

OLH-1224 Sign out link as POST request

---

localstack/provision.sh
src/components/your-services/index.njk
src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/utils/types.ts
src/utils/yourServices.ts

Add content for the HMRC service card on the service dashboard. The card will live under "Other services you've used" as opposed to "Your accounts".
It has a different design from the other services on the service dashboard due to the requirement to have more content to explain to users what the card is about. For the time being I handled this by adding an "isHMRC" flag which is true if the id of a service matches one of the HMRC client IDs.
For now we should not add this service to the "Services you can use" list as they'll be in private beta initially.
HMRC is onboarding with OL at the end of Feb (initially as private beta) so they need a service card. 
Tested locally and in dev, in isolation and with other service cards, in English and Welsh

OLH-1456: Add HMRC card to the service dashboard

---

src/app.constants.ts
src/components/sign-in-history/sign-in-history-controller.ts
src/components/sign-in-history/tests/sign-in-history-controller.test.ts
src/components/your-services/tests/your-services-controller.test.ts
src/components/your-services/your-services-controller.ts
src/utils/prettifyDate.ts
src/utils/signInHistory.ts
src/utils/yourServices.ts
test/unit/utils/prettifyDate.test.ts
test/unit/utils/signInHistory.test.ts
test/unit/utils/yourServices.test.ts

The `prettifyDate` util was hard coded to return dates in `en-GB`. There is a need to display dates in Welsh when the user is viewing their OL home in Welsh.
This refactors the formatter to allow an additional locale parameter to be passed in, to display dates in Welsh when the language has been set to Welsh.
Extend `prettifyDate` to accept a language parameter which should be one of 'en' or 'cy'. 
If language is not specified, or the parameter has a value other than 'en' or 'cy', default to returning dates in English. 
Refactor the parts of the code which rely on `prettifyDate`, ensuring a language parameter is passed.
`prettifyDate` now accepts named parameters.
Welsh language support is a requirement.
https://govukverify.atlassian.net/browse/OLH-1505
Automated testing and manual …

OLH-1505: Refactor date formatting function

---

src/components/report-suspicious-activity/report-suspicious-activity-controller.ts
src/components/report-suspicious-activity/report-suspicious-activity-routes.ts
src/components/report-suspicious-activity/tests/report-suspicious-activity-controller.test.ts
src/utils/activityHistory.ts

Add a redirect to the POST handler for suspicious activity, to redirect the user to the confirmation page.
- Add a new GET handler for the `report-activity/done` route
- In the POST handler, redirect the user to the GET handler.
- Ensure the `page` parameter is added to the handler correctly.
During testing, we discovered an issue where if a user reports activity, then clicks on the browser's back button; they would see a "Confirmation of resubmitting form" message. This stops that from happening. By using a 302 redirect, the POST page is not included in the history, so it wont be resubmitted when the user goes back.
I have tested this locally, and on dev.

OLH-1565 Redirect the user after submitting a suspicious activity report.

---

src/components/activity-history/activity-history-routes.ts
src/components/activity-history/tests/activity-history-integration.test.ts
src/components/report-suspicious-activity/report-suspicious-activity-routes.ts
src/components/security/security-controller.ts
src/components/security/tests/security-controller.test.ts
src/components/security/tests/security-integration.test.ts
src/components/your-services/your-services-controller.ts
src/middleware/check-allowed-services-list.ts
src/utils/yourServices.ts

[OLH-1521] Make activity log and RSA available only if the user has certain service cards
Only users with HMRC service in their list would be able to access the activity history page and report suspicious activity page
Added checks to verify if the user has HMRC services in their list
To reduce the risk of overwhelming TICF.
Unit, integration and local testing
[OLH-1521]: https://govukverify.atlassian.net/browse/OLH-1521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1521 Make activity log and RSA available only if the user has certain service cards

---

src/components/report-suspicious-activity/report-suspicious-activity-routes.ts

- Adds middleware to the report confirmation page, to check that the user is able to access the activity log
This route was added at the same time that the middleware was being created, so it wasn't available at the time of creating the route.
https://github.com/govuk-one-login/di-account-management-frontend/pull/1187

OLH-1575 use checkAllowedServicesList middleware in router

---

src/locales/cy/translation.json
src/locales/en/translation.json

Add today's date to the translation files for English and Welsh where we display the "GOV.UK One Login started recording..." message.
We released the backend to production this morning and are now storing data. This will explain to users why they don't see history before today. 
I've tested this in dev in both English and Welsh

OLH-1559: Add activity log start date

---

src/components/activity-history/activity-history-controller.ts
src/components/activity-history/tests/activity-history-controller.test.ts
src/components/common/activity-history/event.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Update the check in the activity history template to use the same test ID as the backend is expecting (see https://github.com/govuk-one-login/di-account-management-backend/pull/208), or against the Home app's client ID.
We don't currently show sign ins to One Login Home in the history because there's no content for the client ID in the translation files. This is intentional because we don't want to show a service card for Home.
https://github.com/govuk-one-login/di-account-management-backend/pull/208
I've run this locally and tested that events with client IDs of both `oneLoginHome` and the local dev ID show up and are rendered correctly.

OLH-1562: Show One Login Home in activity history

---

src/config.ts

Auth run stub RP clients in all environments to allow testing of the One Login journey in all permutations. This PR adds the client IDs for these to our allow list of services that can see the activity log.
This will give us an easy way of adding an allowed service to the history of our users in non-production environments for testing.

OLH-1583 Add the Stub RPs to the activity log allowlist

---

deploy/template.yaml

Rename the activity log table parameter
We renamed the table in the backend and updated the default parameter value, but this doesn't update the value on stacks that are already deployed.
Force the new value through by renaming the parameter.
I've deployed this to dev to make sure it still works (it does!)

OLH-1588: Rename the activity log table parameter

---

src/components/activity-history/activity-history-controller.ts
src/components/activity-history/tests/activity-history-controller.test.ts
src/components/activity-history/tests/activity-history-integration.test.ts
src/utils/activityHistory.ts
src/utils/present-activity-history.ts
test/unit/utils/present-activity-history.test.ts

Sort the activity history with the newest entry first.
We can't do this in the DynamoDB query because it only supports sorting using the sort key, and our sort key has to be the event ID because timestamp may not be unique. This means the entries come back from DynamoDB in an effectively random order.
The presenter is called before we do pagination, so sorting here means the order stays consistent across all the displayed pages.
This PR also moves the presenter into a separate file. This is so we can use `sinon` to stub the call to `getActivityLogEntry` and control the 
Currently the activity history displays items in a random order.
I've run this locally and checked the order is correct and consistent across pages (see below)
I've put the refactor as its own commit to make it easier to …

OLH-1580: Sort activity history to display newest items first

---

src/components/activity-history/tests/activity-history-integration.test.ts
src/config.ts
src/utils/activityHistory.ts
test/unit/utils/activityHistory.test.ts

Filters the activity log down to items which either have a service card, appear on the 'services you can use' list or are for the One Login Home RP.
Filtering happens before we decrypt, sort and paginate so this should also reduce our use of KMS which is likely the slowest part of rendering the page.
This is needed because the activity log database includes items from RPs which don't have content eg. the programme's stub RPs. We need to exclude these to prevent errors when rendering the page. This also protects us against a new RP onboarding before we've added content for their service card and activity log. Now if that happens, the activity log won't display items for that new RP until we have content.
I've deployed this into dev and added an item to the activity log with a client ID …

OLH-1588: Filter activity log to items which have content

---

src/components/report-suspicious-activity/report-suspicious-activity-controller.ts

Pass the Home Login OIDC to the template when rendering the report acitivty page
So that when a user is reporting the One Login Home login itself, we render it correctly.

OLH-1591 Render One Login Home activity correctly 

---

@types/express/index.d.ts
src/app.constants.ts

- Create a MFA Method type (based on [this](https://github.com/govuk-one-login/openapi-specs/blob/main/auth/method-management-api.yaml#L169-L193))
- Add an array of the new type that to session type definition
We will need this data available in the session object in order display the MFA methods to the user.

OLH-1623 Add a type definition for users' MFA methods to the frontend session

---

src/components/your-services/index.njk
src/components/your-services/tests/your-services-integration.test.ts
src/utils/types.ts
src/utils/yourServices.ts
test/unit/utils/yourServices.test.ts

Address the comments on [this PR](https://github.com/govuk-one-login/di-account-management-frontend/pull/1179).
The points that were left unaddressed: 
1.  enquiring whether the conditional rendering of the longer service card design with `{% if service.isHMRC %}` can be made more semantic by checking whether a `paragraph1` field exists instead.
2. adding tests for the longer service card design
In this PR I addressed question 2. 
I attempted to address question 1, however I could not find a good way to conditionally display pieces of UI if a translation exists, or to determine whether a translation exists from the template layer in general. 
This doesn't seem to be something that we are currently doing anywhere else, and it doesn't seem straightforward to do, so I'm not sure whether it …

OLH-1525: add tests for HMRC card

---

src/config.ts

Update stub RP client IDs. This fixes the issue we're having where people can't view the activity history in production.
The client IDs for all the stub RPs recently changed due to Orchestration changing the way they're provisioned. See https://github.com/govuk-one-login/relying-party-stub/pull/105 for more details and to verify the new IDs.
After this change we don't expect any further changes to the IDs.

BAU: Update stub RP client IDs

---

src/assets/scss/application.scss
src/components/common/layout/header.njk

Some inline CSS was applied to the header component. There was a CSP error relating to this. 
There is no reason this CSS would need to be inline. This removes the inline CSS and applies the same rule in our application css sheet.
Verify that the CSP error is gone and the styling is still applied on the `.govuk-header__link--homepage` element

BAU: inline style causing CSP error

---

src/components/report-suspicious-activity/report-suspicious-activity-routes.ts

OLH-1636 - Error Recording Activity history
Remove refreshMiddlewareToken from RSA route.
We discovered the refreshMiddlewareToken potentially always fails. 
https://govukverify.atlassian.net/browse/OLH-1636
Deploy to dev and ensure RSA journey is not broken

OLH-1636 - Error Recording Activity history

---

src/config.ts
test/unit/config.test.ts

The 'Find and apply for a grant' service was wrongly in both the list of account services and standalone services. This meant that if a user had the service card they'd see it under both 'Your accounts' and 'Other services you've used'.
We missed this duplication when we changed these lists in #1192. I've checked all the other IDs in the lists and there's no other duplicate entries so this is the only service we need to check.
I've run this locally and given myself a card for this service. I can see it now only appears once in the correct section:

OLH-1670: Remove 'Find a grant' from services list

---

src/components/contact-govuk-one-login/index.njk

[OLH-1316: Fix webchat focus order issue](https://github.com/govuk-one-login/di-account-management-frontend/commit/7c374d75e1cb6d27496c5c673091b7f8865ea747) 
The purpose of these changes is to address an issue as described in the DAC audit report ([link in JIRA](https://govukverify.atlassian.net/browse/OLH-1316)). The issue is that focus order does not follow logically when the Webchat is activated using the "Use webchat" button in the content of the page (WCAG 2.4.3 Focus Order (Level A))
When navigating by keyboard or screen reader software, the following should happen:
- when the webchat is opened using the "Use webchat" button, focus should move to the webchat window (whereas currently users have to tab through the entire content of the page to reach the webchat window)
- when the …

OLH-1316: focus order fix for accessibility

---

deploy/template.yaml

Reduce the interval between healthcheck requests from our load balancer to every 15 seconds.
Currently the healthchecks are every 30 seconds and we wait for 2 consecutive failed checks before we mark an instance as unhealthy. This means that if a container does crash we're waiting for 60 seconds before starting a new one.
This may be one of the reasons why we're seeing so many failed requests under load in the performance tests. Making the requests more frequently means we'll detect crashed containers sooner.
I've deployed this to dev to make sure the containers can start up successfully with this new timing.

OLH-1616: Increase frequency of application healthchecks

---

src/middleware/refresh-token-middleware.ts

OLH-1636 - Refresh Token Middleware Error
Bind the OIDC object to the retryable method call because we observed this is returning as null when called.
Prod error when refreshing access token
https://govukverify.atlassian.net/browse/OLH-1636
Deployed up to a tested in staging
Code completeness and test

OLH-1636 - Refresh Token Middleware Error

---

src/components/contact-govuk-one-login/index.njk

Add support for Welsh version of Webchat by replacing the `data-brand` attribute with a `facia` attribute whose values should be: 
- "hgsgds" when the language of the page is English
-  "welsh" when the language of the page is Welsh.
Webchat must support Welsh. These are the updates we were instructed to make, in order to support it. 
Switched language to Welsh, checked the attribute was correct and that Welsh chat was loading.
Switched back to English, checked that English chat was loading.

OLH-1409: Support Welsh webchat

---

.pre-commit-config.yaml
README.md

This will run prettier on all staged files before a new commit is created. If any files are modified, the hook will fail and we'll need to check and stage the changes.
To keep our formatting consistent and reduce the number of linting changes / commits we need to review.
I ran the new install commands from the README before committing the changes in this PR to test the hook behaviour.

BAU: Add pre-commit config to run prettier

---

deploy/template.yaml

Point our integration environment at our supplier's production webchat instance. See [Ben's message in Slack](https://gds.slack.com/archives/C012GEZBZM0/p1712591841543219) confirming the production URL.
This is a temporary measure to allow us to test the English and Welsh flows & configuration before we try to go live on Monday.

OLH-1695: Load production webchat in integration

---

src/components/contact-govuk-one-login/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Add a link to guidance for helpers to the contact triage page.
Link added after the links in the ‘Before you contact us’ section of the contact triage page.
So people who help users with setting up their one login or proving their ID can find the guidance.
Can be deployed to dev.
Check links and welsh displaying correctly.

OLH-1653 - Add link to guidance for helpers from contact triage page.

---

src/config/helmet.ts

Add the domain the webchat loads font styles from to our content security policy.
We already have the nonce in this `<style>` tag, but that only permits inline styles. We also need to add the domain to the `style-src` in our CSP to permit loading the font.
I've run this locally and checked the CSP error is gone and that the stylesheet loads:

BAU: Add webchat font style to CSP

---

package-lock.json
package.json
src/components/common/layout/languageToggle.njk
src/components/security/tests/security-integration.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/middleware/update-session-middleware.ts
src/utils/strings.ts
test/unit/middleware/update-session-middleware.test.ts
test/unit/utils/strings.test.ts

[0LH-1472] Investigate Multiple FROM URL on request path
Refactored isValidURL to use URL API instead of regex which is built to parse according to the URL standard, handling a wider variety of URL formats, better error handling and support for internationalised domains.
"nofollow" attributes were added as well to avoid robot crawling and recursively adding fromURL 
Because there were multiple URL's reported in splunk
Unit test and local testing

OLH-1472 Investigate Multiple FROM URL on request path

---

src/utils/test/txma-header.test.ts
src/utils/txma-header.ts

Add a helper function to get the value of the TxMA device information header.
I considered extending the set-local-vars middleware to put this value in `res.locals` instead, but it's possible that in the future we'll send audit events in a context that doesn't have clean access to the `Response` object. I thought it'd be a nicer pattern to call this function in the controller and pass the result down to the service that's making the API call or sending the audit event.
There's also a tiny amount of logic here, so a separate function is easier to unit test.
This function isn't called anywhere yet - we have other tickets to deal with including the value in our audit events.
We'll need to use this value everywhere we send audit events so we want to have one place we deal with fetching it.

OLH-1709: Add helper function for TxMA header

---

deploy/template.yaml

Setting all log retention to 30 days.
See [SW-249](https://govukverify.atlassian.net/browse/SW-249) and associated epic [SW-241](https://govukverify.atlassian.net/browse/SW-241)
What changed
Log retention for deploy CFN template log groups set to 30 days
Why did it change
LZA will set any log retention below 30 days to 30 days. This PR supports remediation for [INCIDEN-627](https://govukverify.atlassian.net/browse/INCIDEN-627?focusedCommentId=125675)
[SW-249]: https://govukverify.atlassian.net/browse/SW-249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SW-241]: https://govukverify.atlassian.net/browse/SW-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INCIDEN-627]: …

Set all log retention to 30 days

---

localstack/provision.sh
src/app.constants.ts
src/app.ts
src/components/add-mfa-method-app/add-mfa-method-app-controller.ts
src/components/add-mfa-method-app/add-mfa-method-app-routes.ts
src/components/add-mfa-method-app/index.njk
src/components/add-mfa-method-app/tests/add-mfa-methods-app-controller.test.ts
src/components/add-mfa-method/add-mfa-methods-controller.ts
src/components/add-mfa-method/index.njk
src/components/add-mfa-method/tests/add-mfa-methods-controller.test.ts
src/components/common/confirmation-page/confirmation.njk
src/components/update-confirmation/tests/update-confirmation-controller.test.ts
src/components/update-confirmation/update-confirmation-controller.ts
src/components/update-confirmation/update-confirmation-routes.ts
src/locales/en/translation.json
src/middleware/validate-state-middleware.ts
src/utils/state-machine.ts
test/unit/middleware/validate-state-middleware.test.ts
test/unit/utils/state-machine.test.ts

OLH-1663 - Update the frontend state machine for adding an authenticator app
- Update the state machine to include states and events for adding MFA method
- Add the validator to MFA pages to ensure state transitions are as expected
- Test additional state transitions works as expected
So that we can use state engine to manage/validate user interactions with our platform and handle errors appropriately
Integration test
Local Test
Test in dev environment
Code completeness and tests

OLH-1663 - Update the frontend state machine for adding an authenticator app

---

src/components/report-suspicious-activity/report-suspicious-activity-controller.ts
src/components/report-suspicious-activity/tests/report-suspicious-activity-controller.test.ts

OLH-1712 - Send the TxMA header value in the SNS message when a user reports activity
Add device information to the SNS message sent as part of report suspicious activity the header key/value pair for `"txma-audit-encoded"` exists.
So that we can capture the device and submit as part of Audit Event to TxMA when a suspicious activity is reported.
https://govukverify.atlassian.net/browse/OLH-1712
Deploy to dev
1. Add the `txma-audit-encoded` header and ensure it does not break report suspicious ativity process
2. Do not add the `txma-audit-encoded` and ensure it does not break the report suspiciouus activity process
3. Publish an RSA SNS message directly to SNS topic with and without the `txma-audit-encoded` and ensure it does not break the report suspicious activity process
Code …

OLH-1712 - Send the TxMA header value in the SNS message when a user reports activity

---

src/app.constants.ts
src/components/delete-account/delete-account-controller.ts
src/components/delete-account/tests/delete-account-controller.test.ts
src/components/global-logout/global-logout-controller.ts
src/components/global-logout/tests/global-logout-controller.test.ts
src/components/logout/logout-controller.ts
src/components/logout/tests/logout-controller.test.ts
src/utils/session-store.ts

When a user deletes their account or logs out via the global logout also delete the Express session.
The destroyUserSessions function and its callers.
The destroyUserSessions function in the session-store module attempts to delete all entries in the user sessions table.  However, it did not destroy the Express session which resulted in the session persisting after the user thought they were logged out.  Adding a final call to delete the Express session ensured everything was removed.  The session-store destroyUserSessions function was refactored to highlight the two distinct actions that it takes, firstly to find all the users records in the session store and delete them and secondly to destroy the Express session.

OLH-1724 Delete account and backchannel logout journeys don't delete user's sessions

---

src/locales/cy/translation.json
src/locales/en/translation.json

OLH-1649 - Onboard RP: Find and use a DfE API
Make corrections to link text and service description
Found this as part of UCD review
Fix on top of https://github.com/govuk-one-login/di-account-management-frontend/pull/1257
UCD Review in dev

OLH-1649 - Onboard RP: Find and use a DfE API - Make corrections.

---

src/components/change-email/change-email-validation.ts
src/components/change-email/tests/change-email-integration.test.ts

There is an issue on the "Enter your new email address" page where when there is an error (the form is submitted with an invalid address or the form is submitted with an empty email field), there is an additional "@" character prepended on the input field.
https://github.com/govuk-one-login/di-account-management-frontend/assets/7116819/b74df4df-a0c7-4b42-af74-4baefed67d3e
As far as I could ascertain, this bug does not appear to be as a result of an issue on our side, but rather it seems like it's coming from  the `express-validator` middleware. This made it difficult to debug/fix, however I have found a workaround which seems to fix it by changing the order of the functions in the validation chain, making the `normalizeEmail` one execute after other checks.
Tests were missing for the …

OLH-1748: Fix bug on Change email page

---

src/components/your-services/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Update the content in the information box on the `/your-services` page. We now link out to the GOV.UK guidance for One Login rather than maintaining our own list of services as well.
This makes it clearer to users now HMRC are onboarding and also gives us one less thing to maintain.
[Figma](https://www.figma.com/file/0JbNRTnq5ibRtfg8BMxXDL/One-Login-Home---Design-thinking?type=design&node-id=7563-18869&mode=design&t=6OKUlOQIVSyVOwhy-0)
[Jira ticket with Welsh translation
](https://govukverify.atlassian.net/jira/software/c/projects/OLH/boards/195?selectedIssue=OLH-1604)
Please check the English and Welsh content against the content in the ticket. 
Before:
After:

OLH-1604: Update services content

---

deploy/template.yaml

Change Alarm for 5xx errors to sample every 300 seconds and consider the last 24 hours when evaluating whether it should activate.  It will activate if there were 5 5xx errors in the last 24 hour period and the alarm will activate within 300 seconds of teh 5xx error.
The Alarm definition in the AWS SAM template was updated.
To provide a more useful alarm when error responses are returned to the users in production.
We will check this in production and monitor whether it gives us the required level of alerting.

OLH-1655 - improve alerting of 5xx errors.

---

.github/workflows/on-pull-request.yml

Allow tests to be run in a merge queue. This change won't have any impact on its own. Once it's merged I'll set up the merge queue in the repository settings.
[^1]: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#about-merge-queues
We're going to try out merge queues[^1] as a solution for constantly needing to rebase our PRs when another PR is merged.
Some of the steps in this workflow are required before a PR is merged. The same restriction applies to Github merging a PR from a merge queue, so before we can set up the queue we need to allow the workflow to be triggered by the queue.

BAU: Allow tests to be run in a merge queue

---

src/components/enter-password/enter-password-controller.ts
src/components/enter-password/index.njk

Fix bug where some of the content is missing on the "Enter password" page when there is an empty field validation error. What is happening is that the logic that renders different pieces of content for different "states" of this page was moved into the controller, with the strings being passed into the view as local vars. 
This works fine in the normal/default state of the view, but it doesn't work when the form is POSTed and the `validateEnterPasswordRequest()` chain function fails with an error, triggering `renderBadRequest()` which renders the view again minus those local vars.
My initial intention was to modify `renderBadRequest` to allow it to receive locals but I ran into some difficulties with that when re-rendering in the context of middleware functions. Having spent way too much …

OLH-1750: Enter password error state content issue

---

src/config/helmet.ts

Updated our current google analytics domain to accept any subdomain, also *.analytics.google.com was added.
It looks like Google have changed the subdomain they serve the tracking code from and it’s now being blocked from loading by our CSP. This means we have no GA tracking working at the moment.
Reviewed in dev all working.
New CSP must match the one on the PR.
Console should not throw any CSP errors

OLH-1771 unblock Google analytics from our content security policy

---

deploy/template.yaml

Enable the Cloudfront header in all environments by removing the condition.
We've confirmed with TxMA that they're ready to receive events with this new field in production, and with our service transition lead that this is a minor change for us since we're not doing any of the DNS changes.
That means we're ready to call the function in production and start setting the new header for requests to our frontend.
I've deployed this to dev to check my template changes are valid.

OLH-1766: Enable the Cloudfront header in all environments

---

src/components/delete-account/delete-account-controller.ts
src/components/delete-account/tests/delete-account-controller.test.ts
src/components/update-confirmation/tests/update-confirmation-controller.test.ts
src/components/update-confirmation/update-confirmation-controller.ts
src/utils/session-store.ts
src/utils/test/session-store.test.ts

OLH-1706 - Stop am cookie being used to sign in to deleted  or account where password has changed
https://govukverify.atlassian.net/browse/OLH-1706
Expire am cookie when account deleted or password changed.
As recommended by remediation action on Purple Teaming exercise.
https://docs.google.com/presentation/d/1PCdEJzY0XlS8nY9UjNnvRoMs73qyZLcI_AE9BAuR3nQ/edit#slide=id.g2c25a21a9b4_0_0
Deploy to dev and after accoutn deletion and/or password is changed, the am cookie expiry time is set to a date in the past.
Test and code completeness

OLH-1706 - Stop am cookie being used to sign in to deleted  or changed password account 

---

src/components/change-phone-number/index.njk
src/components/check-your-email/index.njk
src/components/check-your-phone/check-your-phone-controller.ts
src/components/check-your-phone/index.njk
src/components/enter-password/index.njk
src/components/resend-phone-code/index.njk
src/components/resend-phone-code/resend-phone-code-controller.ts
src/components/resend-phone-code/tests/resend-phone-code-controller.test.ts
src/components/update-confirmation/index.njk
src/components/update-confirmation/update-confirmation-controller.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/utils/strings.ts
test/unit/utils/strings.test.ts

Update some of the content on the update phone number journey (and a few bits in some other journeys) in light of bringing account management frontend more in line with auth. 
The content updates include:
-  moving the "Problems with the code" dropdown under the submit button on all versions of this page
- changing "I do not want to change my [thing]" to "Cancel and go back to Security"
- updating how we play back the new phone number in the update phone number journey:  changed the language and the way the phone number is displayed. Now we consistently display the last 4 digits, in bold, instead of the obfuscated "*******1111" format
- use uppercase "Security" across the journey when talking about the Security page 
More consistent language across the old and new journeys.
Mel has …

OLH-1745: Update content on update phone journey

---

src/app.ts

Override the req.t function (provided by the i18n middleware), instead of calling it directly, call it using the `safeTranslate` function.
We added a `safeTranslation` system in [this PR](https://github.com/govuk-one-login/di-account-management-frontend/pull/1347), so that we could log cases of missing Welsh translations.
As part of the change, the fallback translation key was [removed](https://github.com/govuk-one-login/di-account-management-frontend/pull/1347/files#diff-f85240b4ea55d79848a6c10ada2ee5a7c8a98322e7a473fd53a54f50f8057072R8).
Since the `safeTranslation` was only used in the nunjucks `translate` [filter](https://github.com/govuk-one-login/di-account-management-frontend/pull/1347/files#diff-56d484fb2dd4640edebe2d84825c06d6b2cfdcd75abbae7801a858ee4637467fL17), we don't …

OLH-1805 Security Page breaks when lng cookie is not set

---

src/components/contact-govuk-one-login/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Remove the option to contact GOVUK OL on the weekend as this will no longer be available.
For the time being we are simply removing the weekend bullet point. 
This is only until we get back Welsh translations for the paragraph version which is when the content can be updated from
> You can call us on: 
• Monday to Friday, 8am to 8pm
to
> You can call us Monday to Friday, 8am to 8pm
The decision to proceed like this is because it's fairly urgent that the content is updated asap as users will no longer be able to get in touch with contact centre starting this weekend.
Check that the opening hours have been updated on the webchat and phone contact options on the triage page.

OLH-1804: Update contact hours

---

src/app.ts
src/assets/javascript/cookies.js
src/components/change-authenticator-app/tests/change-authenticator-app-controller.test.ts
src/components/change-authenticator-app/tests/change-authenticator-app-integration.test.ts
src/components/check-your-phone/check-your-phone-controller.ts
src/components/check-your-phone/tests/check-your-phone-controller.test.ts
src/components/common/mfa/index.ts
src/utils/mfa/index.ts
src/utils/mfa/types.d.ts
src/utils/test/mfa-test.ts
src/utils/types.ts

OLH-1798 - Check the stub is validating the right things
Update the change SMS mfa method to call as per agreed validations where 
- Endpoint field - empty when updating AUTH_APP mfa method and for SMS, it will be the phone number
- credential field - empty when updating SMS mfa method and for AUTH_APP, it will be the secret
So that calling services can adhere to the method management api specification and validation rules.
https://govukverify.atlassian.net/browse/OLH-1798
Deploy to dev and confirm changing sms auth method works to completion.

OLH-1798 - Check the stub is validating the right things

---

deploy/template.yaml

OLH-1844 - Enable GA4 in staging.
What: Enable GA4 in staging
Why: So that performance analysts can test report suspicious activity pages with GA4
- Set GA4DISABLED to false

OLH-1844 - Enable GA4 in staging.

---

src/components/contact-govuk-one-login/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Change opening hours for phone and webchat from a bullet list format to a paragraph format.
The option to contact the contact centre on the weekend [has been removed](https://github.com/govuk-one-login/di-account-management-frontend/pull/1397). 
We have now received the Welsh translations so the content can be re-formatted as a sentence.
Also, remove random empty `<p>` tag.
https://govukverify.atlassian.net/browse/OLH-1835
https://github.com/govuk-one-login/di-account-management-frontend/pull/1397 
Test the contact page in English and Welsh, checking that the content matches the content from the [JIRA ticket](https://govukverify.atlassian.net/browse/OLH-1835) (Welsh translations sheet in the comments)

OLH-1835: update phone/webchat opening hours (again)

---

src/locales/cy/translation.json
src/locales/en/translation.json

OLH-1875 - Update webchat accessibility wording
Translation files to change webchat wording for english and welsh.
Align with latest from central UCD team
https://govukverify.atlassian.net/browse/OLH-1875
Deploy to dev and confirm works as expected for welsh and english.

OLH-1875 - Update webchat accessibility wording

---

src/locales/cy/translation.json

Hyphenate gwe-sgwrs (webchat) in welsh translation file. 
The hyphenated version is correct. The non-hyphenated version (which we’ve been sent in a few previous translation requests) means “web course” or “evening course”.
Check I've not missed any instances of `gwesgwrs` or `Gwesgwrs`.

OLH-1885: Hyphenate gwe-sgwrs (webchat)

---

src/components/common/layout/banner.njk

Link to the One Login cookie policy from the cookie banner. 
When you accept or reject cookies the banner updates to say "You've accepted additional cookies. You can [change your cookie settings] at any time." where [change your cookie settings] is a link to GOV.UK's cookie policy.
This is the wrong place to send users as they're not covered by GOV.UK's policy while using One Login. Update the link to point to our cookie policy instead.
https://govukverify.atlassian.net/browse/INCIDEN-827

OLH-1890: Link to the One Login cookie policy

---

deploy/template.yaml

OLH-1874 Turn on GA4 in production.
Enable GA4 in prod
GA4 is planned for Go Live tomorrow morning 10am
https://govukverify.atlassian.net/browse/OLH-1874
Changed the flag GA4_DISABLED to false.
Replicate same config in dev and check the GA4 is being shown.

OLH-1874 Turn on GA4 in production.

---

src/components/contact-govuk-one-login/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Tweak the way the webchat accessibility statement paragraph is displayed on the contact triage page.
The inset text used to have several paragraphs which were stored as an array in the translation files. This has since been updated so there is one paragraph only, which means the current solution is a bit overengineered. 
Some additional small style updates: use em dash instead of a regular hyphen and move the full stop outside of the anchor tag. The differences are pretty subtle:
There is no need to store the a11y statement related content as an array of paragraphs anymore (it is only one paragraph now). And em dash is technically the correct character for this use case. 
Tested that the content on the inset text displays as expected in the en and cy versions
Verify the above

BAU: a11y statement inset text tweak

---

src/locales/cy/translation.json
src/locales/en/translation.json

This adds a link to the new "What to do about unexpected messages from GOV.UK One Login" guide under the "Read our guidance if you're having a problem with:" section on the contact triage page.
Fraud have published a new guide about what to do if you receive unexpected email or text messages about GOV.UK One Login.
https://govukverify.atlassian.net/browse/OLH-1881 
Tested that the content appears on the triage page as specified in the JIRA ticket and links to the correct guidance page (in English as well as Welsh)
Confirm the above.

OLH-1881: add new guide to contact triage page

---

.github/workflows/update-dependabot-nvmrc.yml

[OLH-1717] Set nvmrc version based on Dockerfile
Added a new workflow to run everytime dependabot updates the Dockerfile
Since Dependabot only updates node versions in our Dockerfiles, it is easier to keep .nvmrc file up to date once dependabot creates a PR that updates node
The workflow would only update .nvmrc if both node versions are different, making it easier to maintain rather than having build environment variables in our dockerfile and github actions. (See previous PR)
https://github.com/govuk-one-login/di-account-management-frontend/pull/1417
I have modified the Dockerfile on a separate draft PR and how checked the workflow updates the .nvmrc file and creates a new PR
[OLH-1717]: https://govukverify.atlassian.net/browse/OLH-1717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhY …

OLH-1717 Set nvmrc version based on Dockerfile

---

src/components/check-your-phone/check-your-phone-controller.ts
src/components/check-your-phone/tests/check-your-phone-controller.test.ts

Include new phone number in payload to calls to the Account Management API when a user is changing their phone number. 
It looks like when we refactored this controller to switch between the new MFA method API or the old API based on the feature flag we set up a common type definition for both. In #1401 we removed the new phone number from the payload when we added new logic for the endpoint field, but this inadvertently also removed it for the old method which is still in use at the moment.
This means users cannot currently change their phone number. Add the new value back into the payload for all requests.
After this PR we'll need to remove this new field from the payload in the new-style API calls, but that can be done in a followup PR since it's not in use yet.
#1401

INCIDEN-834: Include new phone number in payload

---

src/components/check-your-email/tests/check-your-email-integration.test.ts
src/components/check-your-phone/tests/check-your-phone-integration.test.ts
src/components/common/mfa/add-auth-app.njk
src/locales/cy/translation.json
src/locales/en/translation.json

This update is to reflect Auth's content changes, removing the phrase "security code" from input field labels (and the error messages associated with them), and replacing it with simply "code".
The reason behind this update is that some mobile browsers interpret input fields labelled "security code" as being credit card related, and therefore prompt users to enter their card security code which is obviously not correct.
https://govukverify.atlassian.net/browse/OLH-1868
A UCD check of the content updates has been done in the dev environment

OLH-1868: Update wording around "security codes"

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

[OLH-1908] Onboard RP: ATE Capital Schemes [PB]
Added the correct production id and testing id to both english and welsh translation files
ATE Capital Schemes service is being onboarded
Tested locally and in dev
[OLH-1908]: https://govukverify.atlassian.net/browse/OLH-1908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1908 Onboard RP: ATE Capital Schemes [PB]

---

package-lock.json
package.json
src/components/common/layout/base.njk

Update the analytics package to v2.0.1. 
In this PR we go from v1.0.3 to v2.0.1, which includes the major version update to v2. This introduced a new parameter (see the V2 upgrade [in the README](https://www.npmjs.com/package/@govuk-one-login/frontend-analytics)) that allows for form field tracking if we're sure that there's no personal data in our forms. We can't make that assumption as we have phone numbers, email addresses etc. so I've set the new param to `isDataSensitive: true`. 
This is required before we can switch off the old UA implementation. 
https://gds.slack.com/archives/C05JLGJU6BV/p1719825552253399
I've run this locally against the test GA4 property and seen the events firing.

OLH-1923: Update analytics package to v2.0.1

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

The auth-only "Find an apprenticeship" service is due to onboard on the 8th July. 
This adds the content for the new service card to the translation files and adds the service IDs to the config.
The service is due to onboard on the 8th July
https://govukverify.atlassian.net/browse/OLH-1927
Tested the service card locally using the provision script. 
https://github.com/govuk-one-login/di-account-management-frontend/assets/7116819/bb787a7b-5481-4bfb-81dc-9d384e6350f3

OLH-1927: Onboard Find an apprenticeship

---

.github/PULL_REQUEST_TEMPLATE.md
src/components/check-your-email/types.ts
src/components/check-your-phone/check-your-phone-controller.ts
src/components/check-your-phone/tests/check-your-phone-controller.test.ts
src/components/security/index.njk

[OLH-1920]
Add additional check to handle both legacy and MFA API calls
To address what was fixed in https://github.com/govuk-one-login/di-account-management-frontend/pull/1481
https://github.com/govuk-one-login/di-account-management-frontend/pull/1481
Unit tests
Is easier to review by commits. The first one has the original code, the last one is a code refactor.
[OLH-1920]: https://govukverify.atlassian.net/browse/OLH-1920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1920 Resolve payloads between legacy & new API calls [MFA]

---

.github/workflows/on-manual-publish-to-dev.yml

[OLH-1952] Remove pre deploy job from publish to Dev on frontend repo
Removal of validate application and validate deployment  from publish to dev workflow.
Jobs run before merge to main and on pull request. Not necessary before deploying to dev and will save ~4 minutes of dev time.
- I have run the publish to dev flow and validated it is still working.
[OLH-1952]: https://govukverify.atlassian.net/browse/OLH-1952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove pre deploy jobs from publish to Dev on frontend repo

---

package.json

[OLH-1856] Removed eslint check from lint staged
Removed additional eslint check from lint staged as it is checking all files instead of js ts. Not needed as we have it at github actions stage.
Added in prettier config change but files checked include unsupported files. Removing for now.
[OLH-1856]: https://govukverify.atlassian.net/browse/OLH-1856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1856-implement-prettier-config-file-at-repo-level-tweak

---

src/locales/cy/translation.json
src/locales/en/translation.json

New guidance has been published on linking the ID check app to GOV.UK.
We've received a request to add a link to this guidance on the contact triage page, following the "Using the GOV.UK ID Check app" link.
Help users to connect the app to the website if they need to prove their identity with GOV.UK One Login.
https://govukverify.atlassian.net/browse/OLH-1976
Tested that the links work locally. Sent screen recording to Tom Hughes who confirmed that the update looks correct.

OLH-1976: Add new guidance link on the triage page

---

src/components/security/index.njk
src/components/security/security-controller.ts
src/locales/en/translation.json

Display the authenticator app MFA method as read-only in prod (so when the `supportChangeMfa()` flag is off) as MFA method management is not supported yet.
A bug was discovered where we are accidentally displaying the option to change authenticator app in production. This is not good as changing authenticator app would not work yet. So when users would have tried to change their auth app to a different one, they would have seen an error.
| Before  | After |
| ------------- | ------------- |
| <img width="723" alt="Screenshot 2024-07-17 at 15 47 39" src="https://github.com/user-attachments/assets/91430e92-5fb5-459d-8633-ddef36d35ae2"> | <img width="691" alt="Screenshot 2024-07-17 at 15 47 05" src="https://github.com/user-attachments/assets/6487e556-2b81-4a5d-9c4f-50a97cf7655d"> |
Tested …

INCIDEN-867: Display auth app as read-only in prod

---

src/config/aws.ts

[OLH-1931 Bug fix for Local Key ID not found
Changed from a constant to a function call.
Constant was getting initialised during build and threw an error as the env var did not exist.

OLH-1931-local-key-id-not-found-in-dev-environment

---

deploy/template.yaml

[OLH-1953] Remove Task Definition for Canary Deployment  - Can only be deployed after OLH-1893.
Removed Task Definition when Canary Deployment is enabled. 
Code Pipeline fails if Task Definition is present.
- Deployed to Dev and validated works.
On,y lines changewd compared to OLH 1893 is line 374-377.
[OLH-1953]: https://govukverify.atlassian.net/browse/OLH-1953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Olh 1953 set up canary deployments for the frontend deploy pipeline second stage

---

src/utils/mfa/index.ts
src/utils/mfa/types.d.ts
src/utils/types.ts

OLH-1863 - Bug Fix to ensure correctly structured post is sent to create MFA method
Ensures correctly structured post is sent to create MFA method, to match expected input as per the open-api spec
here: https://github.com/govuk-one-login/openapi-specs/blob/main/auth/method-management-api.yaml
Previously sending as
`{
"email": "xxxxx",
"otp": "111111",
"credential": "xxxxx",
"mfaMethod": {
"mfaIdentifier": 2,
"priorityIdentifier": "BACKUP",
"method": {
"mfaMethodType": "SMS",
"endPoint": "xxxxx"
},
"methodVerified": true
}
}`
Whereas actual method management API expects as
`{
"email": "xxxx",
"credential": "xxxx",
"otp": "111111",
"mfaMethod": {
"priorityIdentifier": "BACKUP",
"mfaMethodType": "xxxxx"
},
"methodVerified": true
}`

OLH-1863 - Bug Fix to ensure correctly structured post is sent to create MFA method

---

deploy/template.yaml

[OLH-1896] Enable cloud front caching in build
Enabled caching in build
To allow performance testing of caching in build.
[OLH-1896]: https://govukverify.atlassian.net/browse/OLH-1896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1896-enable-caching-in-build

---

deploy/template.yaml

Refactor the container CPU, memory, min containers and max containers out into a mapping per-environment.
There's no changes to these values in any environment at the moment, but this will make it easier to do so when we want to.
We're going to want to tweak these values in response to performance testing, and we'll probably end up on different values in different environments to save money in eg. staging where there's very little traffic.

BAU: Refactor the container configuration to a mapping

---

deploy/template.yaml

Use the correct parameter for container memory
I used the wrong value in #1539 which is failing to deploy.

BAU: Use the correct parameter for container memory

---

src/app.ts
src/components/change-authenticator-app/tests/change-authenticator-app-integration.test.ts

Move `changeAuthenticatorAppRouter` behind the `supportChangeMfa` flag so that the page cannot be accessed when the feature isn't live yet.
Update tests to verify that the update worked.
For some reason I could not fully understand, the tests weren't picking up on the value of `supportChangeMfa` when using `sandbox.stub` to update its value to false within the `it()` test functions.  
I refactored the test somewhat to work around this problem so all the tests seem to function correctly now (though I am not sure why it wasn't functioning correctly to begin with 🙃 )
The OL home team had an incident where the "change authenticator app" page was accessible in spite of the flag being off. 
https://govukverify.atlassian.net/browse/OLH-1992
Manual test: the change authenticator app route returns …

OLH-1992: changeAuthenticatorAppRouter feature flag fix

---

README.md
post-deploy-tests/Dockerfile
post-deploy-tests/jest.config.ts
post-deploy-tests/package-lock.json
post-deploy-tests/package.json
post-deploy-tests/run-tests.sh
post-deploy-tests/tests/features/contact-govuk-one-login.feature
post-deploy-tests/tests/step-definitions/contact-govuk-one-login.step.ts
post-deploy-tests/tests/utils/launch.ts
post-deploy-tests/tsconfig.json
tsconfig.json

Add an initial feature test for the contact page that checks it's returning a 200 status code. This test uses Jest, [jest-cucumber](https://www.npmjs.com/package/jest-cucumber) and [Puppeteer](https://pptr.dev/) to visit the page in a headless browser and carry out the checks.
These technologies are what's used in many other teams on the programme to orchestrate their feature tests (eg. see [the AIS tests](https://github.com/govuk-one-login/account-interventions-service/tree/main/feature-tests)), give a good framework to expand the test suite in a sensible structure in the future, and are based on Jest which we're aiming to use across our services anyway.
This initial test is very simple but it at least allows us to verify the app has started and is able to serve requests.
Merging this PR …

OLH-1991: Add initial post-deploy tests

---

deploy/template.yaml

Increase the container CPU in build to 2048 (2 vCPU) and change the autoscaling configuration so we're running 8 containers by default, scaling up to 16.
Once this is rolled out we'll re-run the performance tests and see how we do. I'm hopeful this many containers is more than we need, but I'd prefer to start with too many then gradually reduce it (and the cost) once we're sure.
In our performance tests there’s two main causes of problems:
1. Our containers run out of CPU
2. Our containers don’t scale up fast enough
We can solve both of these fairly easily by throwing more resources at the traffic.
Please check the CPU / memory configuration against the allowed combinations for Fargate tasks[^1].
[^1]: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html

OLH-1994: Increase container resources in build

---

.github/workflows/merge-post-deploy-tests-to-main.yml

Add a new Github action that builds and pushes the post-deploy tests image to ECR in our build environment. I've already set up the ECR repository as described in the documentation[^1].
This action is triggered when a PR is merged to main that includes changes to the post-deploy tests folder or the action itself. I've set this up as a separate action rather than a new step in the existing post-merge actions so it doesn't add to the time between merging code and it getting deployed to production.
The image needs to be pushed to ECR before the pipeline starts running the test step, but I think we should be safe to do this as a parallel step. The only slow part in this action is building the image, most of which is network time downloading Chrome. It takes well under 5 minutes on my laptop …

OLH-1991: Add a Github action to build the test image

---

src/components/delete-account/index.njk
src/components/enter-password/enter-password-controller.ts
src/components/enter-password/index.njk
src/components/security/index.njk
src/components/security/security-controller.ts
src/components/security/tests/security-controller.test.ts

Users now have some options for changing their identity information when using an identity RP. However they can only change one part of their name. If they want to change multiple parts of their name they must delete their account and create a new one again.
Identity would like to link straight to the delete journey in account management for this purpose.
A requirement has come through to remove the home specific navigation items from the delete account journey when users arrive to this journey from this route as it was deemed that these elements might cause some confusion.
The way I've gone about this has been to append a query parameter when linking to this journey from the security page.
This seemed most logical as those elements should only be visible the Security page was part of the …

OLH-1906: enter password and delete journey tweaks

---

deploy/template.yaml

[OLH-1895] Skip Canary deployment for the frontend 
Addition of latest deployment strategy options
To update to latest pipeline version which enables canary deployments.
Manually configured template.zip to have skip canary enabled which skipped canary deployment.
[OLH-1895]: https://govukverify.atlassian.net/browse/OLH-1895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1895-set-up-the-feature-to-skip-canary-deployments-for-the-frontend [skip canary]

---

post-deploy-tests/Dockerfile

Disable the interactive pager so AWS commands can run in the headless test container.
By default the AWS CLI uses `less` to display an interactive pager on commands that have a long expected runtime (eg. uploading a file to S3).
This Docker image doesn't have `less` installed, so the tests were failing when the pipeline ran the AWS command to get the frontend stack outputs.
Merge this before https://github.com/govuk-one-login/di-account-management-frontend/pull/1565 
I've built this image locally, pushed it to ECR and verified it runs in the pipeline:

OLH-1991: Disable interactive pager for test image

---

.github/workflows/merge-post-deploy-tests-to-main.yml

Downgrade the AWS action versions in the `merge-post-deploy-tests-to-main.yml` to match those in the action which deploys a branch to dev.
**Don't merge this** before https://github.com/govuk-one-login/di-account-management-frontend/pull/1565
This action is currently failing with a permissions error:
```
denied: User: arn:aws:sts::301577035144:assumed-role/account-mgmt-frontend-pipeline-GitHubActionsRole-AHD0ZJ9UGXU4/GitHubActions is not authorized to perform: ecr:InitiateLayerUpload on resource: arn:aws:ecr:eu-west-2:301577035144:repository/*** because no identity-based policy allows the ecr:InitiateLayerUpload action
```
I think this is because the newer version of one of these actions is a breaking change and slightly changes the role ARN that we end up using (`assumed-role` in the ARN …

OLH-1991: Downgrade image upload action versions

---

.github/dependabot.yml

Add dependabot config for post deploy tests.
This uses the same options as we have for our application code, most notably the Node major version restrictions to keep us on Node 20.

OLH-1991: Add dependabot config for post deploy tests

---

deploy/template.yaml

[OLH-2028] - Update cloudwatch alarm for canary deployment
Replaced cloudwatch alarms that would trigger canary rollback with a ELB 5XX 10% alarm which would trigger if more than 10% of requests return a 5XX.
Reduces the chances of false positives.
[OLH-2028]: https://govukverify.atlassian.net/browse/OLH-2028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2028-create-a-success-rate-alarm-for-the-fe-canary-deployment

---

deploy/template.yaml

[OLH-2029] Enable canary Deployment in production and integration
Conditional change. Removed extra config.
Enabling as part of Canary Initiative.
Deployed to dev.
[OLH-2029]: https://govukverify.atlassian.net/browse/OLH-2029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Olh 2029 enable canary deployment in prod integration for fe

---

deploy/template.yaml

[OLH-2046] Enabled required canary deployment resources in all environments and defaulted canary deployment to all at once
NOTE - I expect this to throw a cloud formation error in production and integration.
- Enabled canary deployment in all environments so resources are available
- Defaulted to all at once deployments
- Maintained 10% every 3 mins canary deployment strategy in prod and integration
Current implementation uses useCanaryDeployment to set which environment's use canary deployment.
If the environment's are changed the 2 stage canary enablement process is required to make it work.
If an environment with canary deployment's enabled is disabled, it causes confusion between target groups which could cause pipeline's to fail and 503's on the frontend.
To resolve this I am …

OLH-2046-enable-canary-deployment-in-all-environments-stage-1

---

deploy/template.yaml

[OLH-2046] Enabled required canary deployment resources in all environments and defaulted canary deployment to all at once
- Enabled canary deployment in all environments so resources are available
- Defaulted to all at once deployments
- Maintained 10% every 3 mins canary deployment strategy in prod and integration
Current implementation uses useCanaryDeployment to set which environment's use canary deployment.
If the environment's are changed the 2 stage canary enablement process is required to make it work.
If an environment with canary deployment's enabled is disabled, it causes confusion between target groups which could cause pipeline's to fail and 503's on the frontend.
To resolve this I am repurposing the conditional to use 10% every 3 mins instead which can be updated without …

OLH-2046-enable-canary-deployment-in-all-environments-stage-2

---

src/app.ts
src/components/common/errors/404.njk
src/components/common/errors/500.njk
src/components/common/layout/base.njk
src/components/contact-govuk-one-login/contact-govuk-one-login-controller.ts
src/config/nunjucks.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/middleware/is-user-logged-in-middleware.ts
src/middleware/set-local-vars-middleware.ts
src/utils/isUserLoggedIn.ts
src/utils/test/isUserLoggedIn.test.ts
test/unit/config/nunjucks.test.ts
test/unit/middleware/is-user-logged-in-middleware.test.ts

Changed the way 404 page behaves depending on whether a user is logged in or not.
For logged in users, navigation is displayed and the main CTA button goes to `your-services` page
For not logged in users, navigation is not shown and the main CTA button goes to sign in page.
Because that’s the more appropriate place to send users who get a “not found” while navigating their One Login home, and less confusing when we don't show the navigation
Local testing for both logged in and not logged in users
Navigate to any non-existent page to see the 404 page. Check both navigation and CTA  button copy

OLH-1488 Update 404 page

---

src/locales/cy/translation.json
src/locales/en/translation.json

OLH-2052 Add new DWP integration client service card and update existing one
https://govukverify.atlassian.net/browse/OLH-2052
Add new entry and update URL for existing entry in translation files for DWP to test new RP in integration environment only. 
So that DWP can test their new service cards before releasing to production.
As it is integration environment only, there is no point deploying this to dev environment to check. i confirmed with Ben this is OK and matches what was done before by @alex9smith  as this is not the same as adding a new RP to prod.
Code completeness and invalid JSON.

OLH-2052 Add new DWP integration client service card and update existing one

---

deploy/template.yaml

[OLH-1958] Security group update to only VPC, Added cloudfront log to access logs, corrected api gateway alarm to 5%
1. Security group ingress rule was configured for all internet. Has been changed to 10.0.0.0/16 which is the VPC.
2. Changed CloudFront Logs to use the access logs bucket
3. ApiGateway4xxStatusAlarm false triggers as it is configured for 0.05% instead of 5%
To resolve pipeline failing tests.
Left in Dev for ~ a week to validate no issues.
[OLH-1958]: https://govukverify.atlassian.net/browse/OLH-1958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1958-fix-code-pipeline-failing-tests-on-frontend-pipeline

---

deploy/template.yaml

OLH-2034 - Add the new header params to the cache policy.
To ensure Missing country code / ja3_fingerprint values in Cloudfront Headers are available.
In cloudformation template, update the cache policy to include the headers
To ensure Missing country code / ja3_fingerprint values in Cloudfront Headers are available as part of data sent to TICF using the TICFFraudHeadersFunction cloudfront function
**EDIT** - Guidance from TxMA QA for testing suggests this testing the TxMA event contains the value can only be done in a higher environment like Staging which means we would need this approved on the basis on yes it didn' t break dev and on dev environment, we can visibly see the new parameters
https://govukverify.atlassian.net/browse/TT2-2015
Deploy to dev and manually check the new headers …

OLH-2034 - Add the new header params to the cache policy.

---

deploy/template.yaml
src/components/common/layout/base.njk
src/components/contact-govuk-one-login/index.njk

Add a line to the robots.txt to allow the contact page to be crawled, this will display the icon in search results
Add a "noindex" meta tag to all pages, unless specifically opted in to crawling.
The gov.uk icon wasn't displaying when our pages appeared in search results, we suspect that this was because it was disallowed in robots.txt, so it wasn't being crawled.
Robots.txt only stops a page from being crawled directly, but if a third party page links to a page, it can still get crawled. Adding a noindex meta tag stops a page from ever getting crawled.

OLH-1983 Update robots.txt, and add a noindex meta tag

---

.github/PULL_REQUEST_TEMPLATE.md

This commit introduces some updates on the PR template. The addition of the feature flag testing tickbox was initially prompted by an incident where a link and a page which were supposed to be behind a feature flag were inadvertently made available in prod.
I also added a UCD review checklist item and PA review checklist item. 
Questions have come up several times about the process of getting changes signed off by UCD so it seemed like a potentially useful reminder to add to the template.
There have been questions on when changes should be signed off by UCD (or a PA, in the case of analytics). 
There was an incident where a journey that shouldn't have been visible in production yet was accidentally available to users.
https://govukverify.atlassian.net/browse/OLH-1990
Feed back if any of …

OLH-1990: Update PR template

---

src/components/add-mfa-method-app/tests/add-mfa-methods-app-controller.test.ts
src/components/add-mfa-method/tests/add-mfa-methods-controller.test.ts
src/components/change-authenticator-app/tests/change-authenticator-app-controller.test.ts
src/components/change-authenticator-app/tests/change-authenticator-app-integration.test.ts
src/components/change-authenticator-app/tests/change-authenticator-app-service.test.ts
src/components/change-default-method/change-default-method-controllers.ts
src/components/change-default-method/tests/change-default-method-controller.test.ts
src/components/check-your-phone/check-your-phone-controller.ts
src/components/check-your-phone/tests/check-your-phone-controller.test.ts
src/components/check-your-phone/tests/check-your-phone-integration.test.ts
src/components/check-your-phone/tests/check-your-phone-service.test.ts
src/components/delete-mfa-method/delete-mfa-method-controller.ts
src/components/security/security-controller.ts
src/components/security/tests/security-controller.test.ts
src/components/security/tests/security-integration.test.ts
src/components/switch-backup-method/switch-backup-method-controller.ts
src/components/switch-backup-method/tests/change-default-method-controller.test.ts
src/components/update-confirmation/tests/update-confirmation-controller.test.ts
src/components/update-confirmation/update-confirmation-controller.ts
src/middleware/mfa-methods-legacy.ts
src/utils/mfa/types.d.ts
src/utils/test/mfa.test.ts
test/unit/middleware/mfa-method-middleware.test.ts
test/unit/middleware/update-session-middleware.test.ts

[OLH-2053] Replaced mfamethod scheme to have SMS phone number instead of endpoint
1) mfa schema updated to differentiate between AUTH APP and SMS
2) replaced endpoint with phone number
3) Fixed tests
4) Replaced logic which added backup method as AUTH APP by default 
In line with mfa api
Deployed updated stub and frontend to dev and changed phone number and added a new SMS mfa backup. 
[OLH-2053]: https://govukverify.atlassian.net/browse/OLH-2053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2053-endpoint-will-be-changed-to-phone-number-in-the-method-management-api

---

src/config.ts
src/locales/en/translation.json

OLH-2074 - Help DWP with their non-appearing service card
Fix issue with DWP integration where service cards are not showing up
Added new client ID to config file and remove duplicate link text line.
Corrected and incorrectly configured service card.
https://govukverify.atlassian.net/browse/OLH-2074
Test in integration environment post merge to main
Sign-off by UCD Team
Verify configuration is set up correctly.

OLH-2074 - Help DWP with their non-appearing service card

---

src/app.ts
src/components/common/errors/404.njk
src/components/common/errors/500.njk
src/components/common/layout/base.njk
src/components/contact-govuk-one-login/contact-govuk-one-login-controller.ts
src/components/oidc-callback/call-back-controller.ts
src/config/nunjucks.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/middleware/is-user-logged-in-middleware.ts
src/middleware/requires-auth-middleware.ts
src/middleware/set-local-vars-middleware.ts
src/utils/isUserLoggedIn.ts
src/utils/test/isUserLoggedIn.test.ts
test/unit/config/nunjucks.test.ts
test/unit/middleware/is-user-logged-in-middleware.test.ts

Changed the way 404 page behaves depending on whether a user is logged in or not.
For logged in users, navigation is displayed and the main CTA button goes to `your-services` page
For not logged in users, navigation is not shown and the main CTA button goes to sign in page.
Because that’s the more appropriate place to send users who get a “not found” while navigating their One Login home, and less confusing when we don't show the navigation
Local testing for both logged in and not logged in users
Navigate to any non-existent page to see the 404 page. Check both navigation and CTA  button copy

OLH-1488 Update 404 page - Fix

---

deploy/template.yaml

Update our CloudFront policy, to forward the `CloudFront-View-Address` header to the app 
The `connection_port` header was missing from the `AUTH_DELETE_ACCOUNT` event that we send. I can see from [here
](https://github.com/govuk-one-login/devplatform-fraud-function/blob/53d68c01bc5c0175bfb12081227a1f9b5837aa39/cloudformation/fraud-function/fraud-function.js#L48-L51) that it comes from the `CloudFront-View-Address` header.

OLH-2076 Collect cloudfront header used to populate connection-port in txMA event

---

src/components/report-suspicious-activity/index.njk
src/components/report-suspicious-activity/success.njk

- Implement the Page View Tracker for the` /activity-history/report-activity?` and `/activity-history/report-activity/done `pages.
- Set contentId and taxonomy values dynamically for the activity-history/report-activity?
As part of GA4 CI work
(DFC-644)[https://govukverify.atlassian.net/browse/DFC-644]

[DFC-644]: Add tracking to activity report pages

---

deploy/template.yaml

OLH-2095 - Fix issue with di-account-frontend deployment failing
Remove Cloudfront-Viewer-Address from Cloudfront cache policy because as per guide here: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/adding-cloudfront-headers.html
CloudFront-Viewer-Address can be added in an origin request policy, but not in a cache policy.
To fix deployment failures.
https://govukverify.atlassian.net/browse/OLH-2076
Deploy to dev and confirm deployment successful
Login to aws in dev and confirm with codepipeline deployment completes successfully.

OLH-2095 - Fix issue with di-account-frontend deployment failing

---

src/locales/cy/translation.json
src/locales/en/translation.json

Change translations of "advisor" to "member of the support team"
On the contact triage page we talk about chatting to an 'advisor' via webchat, but in the webchat itself they're calling themselves a 'member of the support team'

OLH-1705 Change "advisor" to "member of the support team"

---

src/components/change-password/index.njk
src/components/enter-password/index.njk

The show password component script was not loading due to the nonce missing from the inline script tag.
This adds the nonce to the script  which should resolve the problem.
While users can still enter their password fine without the button, having the button is a very important usability/accessibility aid.
Tested change on my local environment.  
Double check that the button is now functioning on all the templates which import this component.

OLH-2136: Fix show password script CSP issue

---

src/app.constants.ts
src/components/common/confirmation-page/confirmation.njk
src/components/common/layout/base.njk
src/components/delete-mfa-method/delete-mfa-method-controller.ts
src/components/delete-mfa-method/tests/delete-mfa-method-controller.test.ts
src/components/switch-backup-method/tests/change-default-method-controller.test.ts
src/locales/en/translation.json

[OLH-2137] UCD Fixes confirmation pages
- Updated mfa text displayed to user to have fullstops
- corrected URL's to follow design 
- added backLinkBlock
- override backLinkBlock in confirmation page
- removed ?id= from delete mfa method controller
- replaced text 'phone number ending in' with 'phone number ending with'
UCD Review
Validated changes locally
Reviewer to validate text's with full stops have not included unintended changes and use of backLinkBlock is not problematic due to unfamiliarity with frontend.
[OLH-2137]: https://govukverify.atlassian.net/browse/OLH-2137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2137-ucd-fixes-confirmation-pages

---

src/config/helmet.ts

OLH-2175 - Fix Dynatrace RUM script CSP issue
Relax CSP to allow script from dynatrace and ruxit to load.
So that scripts from dynatrace can load.
Previous PRs to get RUM working on One Login Home: https://github.com/govuk-one-login/di-account-management-frontend/pull/1624
Previous User Story: https://govukverify.atlassian.net/browse/OLH-1973
Due to RUM being available in staging upwards, not able to test in lower environments.

OLH-2175 - Fix Dynatrace RUM script CSP issue

---

src/components/contact-govuk-one-login/index.njk
src/components/security/security-controller.ts
src/components/your-services/index.njk
src/locales/cy/translation.json

Logs in cloudwatch were showing multiple errors flagging that key '/track-and-redirect' was missing for the en and cy languages. There was no such key in our translation files. I traced it back to the contact triage page where the nunjucks translate filter was accidentally used on a local variable. This didn't have any user-facing consequence so it went unnoticed for a while.
I addressed a couple other errors at the same time:
- on the your services page, it seems like the details element was removed but the njk html block that used to be its content was not. The contents of that nunjucks block were leading to a translation error as the relevant strings had been removed from the translation files
- on the security page, the translation being passed as visually hidden text for the phone …

OLH-2207: Fix translation errors

---

src/locales/cy/translation.json
src/locales/en/translation.json

There was a request to label contact centre hours as UK time as some RPs have large numbers of users outside of the UK.
The content change recommended has been to add "UK time" to the different contact channels.
| Changed content in English  | Changed content in Welsh |
| ------------- | ------------- |
| ![Screenshot 2024-10-23 at 09 46 30](https://github.com/user-attachments/assets/c0038590-a7b6-491c-913b-b35a719257fc) | ![Screenshot 2024-10-23 at 09 47 37](https://github.com/user-attachments/assets/6836cb8f-6629-4f3f-a3e8-dfff8d981112) |

OLH-2132: label contact centre hours as UK time

---

deploy/template.yaml
src/server.ts

[OLH-2217] Adjust ALB timeouts
Increased node KeepAliveTimeout to 65s as there was not enough gap for other stuff to happen.
Increased ALB Target group Deregistration timeout to 62s following RFC 0083.
Optimising EC2 scaling.
https://github.com/govuk-one-login/architecture/blob/913c04af8b57e2cdce07c4b242a409690852d527/rfc/0083-express-on-ecs.md
[OLH-2217]: https://govukverify.atlassian.net/browse/OLH-2217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2217-validate-deregistration-delay-timeout-of-the-target-groups-is-higher-than-the-idle-timeout-of-the-alb

---

Dockerfile
package-lock.json

[OLH-2219] - Set tini as pid1 handler
Advice in RFC for frontend performance improvements
https://github.com/govuk-one-login/architecture/blob/913c04af8b57e2cdce07c4b242a409690852d527/rfc/0083-express-on-ecs.md
Deployed to Dev
[OLH-2219]: https://govukverify.atlassian.net/browse/OLH-2219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2219-use-tini-as-your-pid-1-handler

---

.github/workflows/validate-docker-image-dev.yml

[OLH-2236] Resolve Trivy DB rate limit error
NOTE: This is the temp fix suggested by the Trivy Action team while they continue to investigate a solution 
GCHR have changed something / trivy action has become a lot more popular leading to the db exceeding the ceiling traffic of 44,000 requests per minute from all traffic. The team themselves are unsure what the fix is but have provided a temporary solution through a db mirror. Additionally, in a newer version of trivy action they have supported caching which will lead to less calls to the endpoint.
If the rate limit was reached on the public endpoint we were blocked from merging our PR's into main. I did not see a current method to skip this but we can explore this in the future. Temp solution was to wait a minute and then try again. …

OLH-2236 Resolve Trivy DB rate limit error

---

src/locales/cy/translation.json
src/locales/en/translation.json

OLH-2269 - Repay my debt: update production URL and restore non-production client service cards' signed in state URLs
DWP is different and cleanup activity to remove several integration service cards was not necessary. Also an http URL was initially provided rather than an https URL.
To align the service cards accross all environments to DWPs requirements.
Initial work was done via this PR: https://github.com/govuk-one-login/di-account-management-frontend/pull/1794/files

OLH-2269 - Repay my debt: update product URL and restore non-prod service cards

---

src/locales/en/translation.json

The style guide states we should use "adviser" with an "e" as opposed to "advisor" with an "o".
Correct all instances of "advisor" to "adviser", for consistency.

OLH-2244: style guide formatting correction

---

src/components/change-password/index.njk

The `showPassword` script has been removed as part of the work to replace the OLH local show password component with the DS equivalent in this PR [#1850](https://github.com/govuk-one-login/di-account-management-frontend/pull/1850)
I missed this `<script>` tag in the process of removing the old component. All assets related to this component are now automatically imported from the DS package (`govuk-frontend`) so this is not needed anymore.
This script no longer exists so there is a 404 error on the change password page.

BAU: remove redundant call to `showPassword` script

---

deploy/template.yaml

OLH-2326 - Point integration contact page at UAT webchat (temporarily)
Cloud formation template to point our web chat url to the UAT version for the integration environment.
So that the supplier can test some changes they are making to the webchat component.
https://govukverify.atlassian.net/browse/OLH-2326

OLH-2326 - Point integration contact page at UAT webchat (temporarily)

---

src/utils/dynamo.ts
src/utils/session-store.ts

[OLH-2205] Dynamo DB Client Singleton
- Used a single dynamo db client for all calls instead of within the function
- Creating a new client on every function call has a lot of overhead
- Deployed to dev
- Ran performance tests
[OLH-2205]: https://govukverify.atlassian.net/browse/OLH-2205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

dynamo singleton

---

package-lock.json
package.json
src/components/activity-history/activity-history-controller.ts
src/components/activity-history/tests/activity-history-integration.test.ts
src/components/change-authenticator-app/tests/change-authenticator-app-integration.test.ts
src/components/change-email/tests/change-email-integration.test.ts
src/components/change-password/tests/change-password-integration.test.ts
src/components/change-phone-number/tests/change-phone-number-integration.test.ts
src/components/check-your-email/tests/check-your-email-integration.test.ts
src/components/check-your-phone/tests/check-your-phone-integration.test.ts
src/components/delete-account/tests/delete-account-integration.test.ts
src/components/enter-password/tests/enter-password-integration.test.ts
src/components/global-logout/global-logout-controller.ts
src/components/global-logout/tests/global-logout-controller.test.ts
src/components/resend-email-code/tests/resend-email-code-integration.test.ts
src/components/resend-phone-code/tests/resend-phone-code-integration.test.ts
src/components/security/tests/security-integration.test.ts
src/components/your-services/tests/your-services-integration.test.ts
src/utils/cache.ts
src/utils/oidc.ts
test/unit/utils/oidc.test.ts

[OLH-2205] Replace fast memoize with custom caching mechanism
- Removed fast memoise
- Implemented custom caching mechanism
- Cached getJwks and getIssuer
- Fast memoise was not caching the well known end point for an unknown reason
- As the end point does not change often (every 2 years or so) it is better to implement a custom caching mechanism with a longer TTL
- deployed to Dev
- Ran against performance tests
[OLH-2205]: https://govukverify.atlassian.net/browse/OLH-2205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2205-performance-testing-implementation-of-overload-protection-library-causing-http-503-errors-remove-fast-memoize

---

.github/workflows/build-test-application.yml
.github/workflows/sonarcloud.yml
src/components/track-and-redirect/track-and-redirect-controller.ts
src/middleware/mfa-method-middleware.ts

Reverts govuk-one-login/di-account-management-frontend#1883 as we do not have a URL for METHOD_MANAGEMENT_BASE_URL in production. Unsure why this is but deployment is failing due to this.

Revert "url singleton"

---

localstack/provision.sh
scripts/sync-translations.sh
src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Adds the Air Pollution Service
Also adds (and ran) a script which ensures all entries in the backend clientRegistry are in the frontend clientRegistry as well. It is then safe to copy of the frontend clientRegistry to the backend.

OLH-2170 Add Air pollution assesment service

---

src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

OLH-2352 - Onboard RP: DBTrade: Apply for a licence to provide sanctioned trade services
Add new service card info to translations files for english and welsh.
Add English info for the welsh in this case as this service card has no welsh translation.
Onboard RP: DBTrade: Apply for a licence to provide sanctioned trade services
https://govukverify.atlassian.net/browse/OLH-2352
https://govukverify.atlassian.net/browse/DIOT-691

OLH-2352 - Onboard RP: DBTrade: Apply for a licence to provide sanctioned trade services

---

src/components/search-services/index.njk

Change "searchable list" layout to the standards two-thirds layout used on all other OLH home pages.
Replace custom html markup with design system components. 
| Before | After |
| --- | --- |
| <img width="1191" alt="Screenshot 2025-01-23 at 09 55 38" src="https://github.com/user-attachments/assets/69300079-4bdb-4077-9a79-0b7550245f76" /> | ![Screenshot 2025-01-24 at 18 18 21](https://github.com/user-attachments/assets/d4bbe97d-5b68-473e-80a8-b2a55d205cd3) |
We should use the standard layout and out-of-the-box Design System components where possible
The page is behind a feature flag and likely to undergo many more design changes.
You can visually check the updates by running the application locally and visiting `/search-services`
Not much would have changed visually, other than width of …

Olh 2373 searchable list layout tweak

---

.github/workflows/sonarcloud.yml

The sonarcloud-github-action is now deprecated. The recommendation is to replace it with the sonarqube-scan-action. This should work as a drop-in replacement.
Implemented Sonarqube Scan to prepare for migration when our existing sonarqube cloud action is deprecated.
Sonarqube Cloud Action is being deprecated and replaced with Sonarqube scan.
https://github.com/sonarsource/sonarcloud-github-action
Workflow working in this PR.

BAU: replace sonarqube cloud with sonarqube scan

---

package-lock.json
src/locales/cy/translation.json
src/locales/en/translation.json

OLH-2378 - Update SignedIn URL for Immigration Advice Authority
Update SignedIn URL for Immigration Advice Authority RP
To provide a more user friendly experience for signed in card user
https://govukverify.atlassian.net/browse/OLH-2378
Deploy to dev for UCD review

OLH-2378 - Update SignedIn URL for Immigration Advice Authority

---

src/app.constants.ts
src/components/change-authenticator-app/change-authenticator-app-controller.ts
src/components/change-authenticator-app/tests/change-authenticator-app-controller.test.ts
src/components/change-authenticator-app/tests/change-authenticator-app-integration.test.ts
src/components/common/mfa/tests/index.test.ts
src/components/enter-password/enter-password-controller.ts
src/components/security/security-controller.ts
src/components/security/tests/security-controller.test.ts
src/components/update-confirmation/update-confirmation-controller.ts
src/locales/en/translation.json
src/utils/state-machine.ts

Use `changeAuthApp` instead of `changeAuthenticatorApp` in the URL on the enter password page.
This is consistent with the rest of the content.
I could have just changed the key since that's the only part which shows up in the URL, but all the other states have have the state machine variant, key etc. all called the same thing. I think we'd be making our future lives harder if we made this one different.

OLH-2140: Use AuthApp instead of AuthenticatorApp in URL

---

src/components/common/mfa/index.ts

Safely check for an existing auth app secret in the request body.
Use optional chaining to safely check for an existing app secret. This is needed because it's possible to reach the create auth app page in such a way where there's no `req.body` present - eg. when a user is redirected to this page after confirming their password.
This fixes a bug I found when running the app locally and getting a 500 status code whenever I tried to set up a new app.
https://gds.slack.com/archives/C011Y5SAY3U/p1742903618471749

BAU: Safely check for an existing secret

---

src/components/add-mfa-method-app/tests/add-mfa-methods-app-controller.test.ts
src/components/change-authenticator-app/tests/change-authenticator-app-controller.test.ts
src/components/common/mfa/index.ts
src/components/common/mfa/tests/index.test.ts

Allow an optional backlink to be rendered on MFA pages. To do this, I've added another optional parameter to renderMfaMethodPage. Two optional parameters is ok for this function, but I think if we add another we should consider exposing the parameters as a separate interface object instead.
This just allows us to add backlinks. No pages have them set up so this PR doesn't make any changes to the user journey.
I initially made this change as part of #2053, but when reviewing we realised we didn't actually want a backlink on that page. We will want on on some of the other MFA pages though, so I've pulled this commit out into a separate PR so we can use the same functionality later on. 
#2053

OLH-2140: Allow passing a backlink to renderMfaMethodPage

---

deploy/template.yaml

[BAU] Increase ApiGatewayStatus4xxAlarm Threshold
Threshold increased along with number of datapoints to alarm
Currently the alarm is tripping due to bot traffic scanning the site. This is diluting the alert's in the channel whilst provided no benefit. The purpose of the alarm was to notify us if all users were getting 4xx messages as quick as possible. Thus the threshold has been increased to identify a more significant number of errors over a longer period.

[BAU] Increase ApiGatewayStatus4xxAlarm Threshold

---

src/utils/mfaClient/index.ts
src/utils/mfaClient/types.ts

Refactor the MFA method types to use a union type for the `method` property. 
When I initially set this up I thought that the Typescript compiler would allow us to pass any interface that extended `Method` to a function that required a `Method` and then would infer which interface it was based on the properties.
Unfortunately that's not quite how it works. The more Typescript-native approach to allowing multiple options for the shape of an object is a union type. This achieves the original functionality I wanted and also gives some extra protections as when we use the union type the compiler forces us to write code that can handle each variant.

OLH-2534: Refactor the MFA method types

---

deploy/template.yaml

Add `/v1` to the MM API base URL in dev and build
In #2105 I moved this out of the API client config because the API in staging doesn't have the `/v1` in the path yet.
I forgot that our stub API does still require it. Update the API base URLs in the environments which call the stubs so they stil work.
#2105
I'll deploy this to dev to check it's worked.

OLH-2534: Add `/v1` to the MM API base URL in dev and build

---

deploy/template.yaml
src/components/common/layout/base.njk
src/components/contact-govuk-one-login/index.njk

- Updates `robots.txt` to ensure its format is valid and to allow access to all URLs in production and no URLs otherwise.
- Removes unnecessary meta robots tag from contact page.
When investigating why Google is not displaying the favicon in search results for the contact page I noticed that there were some issues with the way we are controlling robot access to the site.
Standard practice is to allow access to all URLs and then blacklist specific URLs rather than to block all URLs and then whitelist certain URLs.
These current changes allow access to all URLs with nothing blacklisted. This also means that the favicons are accessible and so hopefully Google will start to show them in the search results for the contact page (I'll make a ticket to check in a few weeks).
**If there are any …

[OLH-1983] serve valid robots.txt to hopefully show crown logo in search engine results

---

README.md
post-deploy-tests/Dockerfile
post-deploy-tests/package-lock.json
post-deploy-tests/package.json
post-deploy-tests/tests/step-definitions/contact-govuk-one-login.step.ts
post-deploy-tests/tests/utils/launch.ts

Post-deploy tests migrated from Puppeteer to Playwright.
- Playwright offers a better experience installing and managing browsers and does not to be told where the executable is for each browser. This is useful because running tests locally on `arm64` machines requires running against the locally installed version of Chrome. With Playwright this will just work without having to update variables to point to the executable.
- Having worked with both Puppeteer and Playwright in the past Playwright has always been much less flaky and has more extensive cross-browser capabilities which may be useful in future tests.
- In the last couple of years Playwright seems to have replaced Puppeteer as the go-to tool.
https://govukverify.atlassian.net/browse/OLH-2266

[OLH-2266] migrate post-deploy tests from puppeteer to playwright

---

package-lock.json

This updates to the latest version of the RP registry[^1] which adds Home as an allowed activity log service.
This effectively rolls the feature out to everyone as any user who's logged into Home to view their activity history must by definition have Home in their service history.
[^1]: https://github.com/govuk-one-login/di-account-management-rp-registry/pull/53
The Fraud team have given us the go-ahead to release this feature to all users following our slow rollout trial period. This is the simplest way to do that release that also allows us to roll it back later if we need to.
[Slack conversation with approval to release.](https://gds.slack.com/archives/C02F70D2LQN/p1744630647115329)

OLH-2566: Enable the activity history for all users

---

.github/workflows/sonarcloud.yml
Dockerfile
README.md
local.Dockerfile
package.json

Use `npm ci` instead of `npm install` to install dependencies.
Use of `npm ci` ensures reproducible builds by strictly installing the versions of dependencies specified in the `package-lock.json` file.
https://govukverify.atlassian.net/browse/OLH-2567

OLH-2567: Reproducible builds using npm ci

---

src/utils/mfaClient/index.ts
src/utils/mfaClient/types.ts
src/utils/mfaClient/validate.ts
test/unit/utils/mfaClient.test.ts

This PR includes 2 fixes to the MFA API client:
1. Pass the OTP in the API call when a user creates an SMS method.
2. Use the correct payload structure when creating a new method.
We only need to pass the OTP when a user is creating an SMS method. When they create an authenticator app our frontend can (and does) do all the required validation on the OTP they provide. 
The journey to create a new SMS method isn't migrated to use the API client yet - I'll include the OTP in the calls from the controller when I do that. This PR just has the API client changes.
Andrew and I found these mistakes when we were debugging the journeys in staging. 
[API spec](https://github.com/govuk-one-login/openapi-specs/blob/main/auth/account-management-api/account-management-with-mfa-method-management.yaml)

OLH-2534: Fix the API calls to create an MFA method

---

src/components/delete-mfa-method/delete-mfa-method-controller.ts
src/components/delete-mfa-method/tests/delete-mfa-method-controller.test.ts
src/components/switch-backup-method/switch-backup-method-controller.ts
src/components/switch-backup-method/tests/change-default-method-controller.test.ts
src/middleware/mfa-method-middleware.ts
src/utils/mfaClient/index.ts
src/utils/mfaClient/types.ts
test/unit/middleware/mfa-method-middleware.test.ts
test/unit/utils/mfaClient.test.ts

Update the error type returned by the MFA API client to match the API spec[^1].
I've also added a helper function that takes a response and formats the error data into a nice string. I considered making a new class that implements the `ApiResponse` interface so that function could be a class method but it felt like a lot of boilerplate for what's essentially the same outcome. If we have one more function that needs to operate on a response object we should reconsider that decision.
Originally the API design was going to use RFC 9457[^2] as a standard format for error messages returned by the API. We'd set up the parsing, interfaces etc. to handle errors in this format.
We've now changed our mind about using the format described in that RFC and gone with a simpler error structure.
The …

OLH-2534: Update the error type returned by the MFA API

---

deploy/template.yaml

Tag the Cloudfront distribution in dev for firewall manager. I've deployed this to dev to make sure I've used the conditions right.
Security engineering are rolling out firewall manager to manage all our WAF rules centrally. This is controlled by tags on the resources that we want to enroll in firewall manager.
Set up these tags and conditionally only apply them to the dev environment so we can test enrollment.
See the [parent Jira ticket](https://govukverify.atlassian.net/jira/software/c/projects/OLH/boards/195?selectedIssue=OLH-2281) for more details.

OLH-2559: Tag the Cloudfront distribution in dev

---

src/components/delete-account/delete-account-controller.ts
src/components/delete-account/index.njk
src/components/delete-account/tests/delete-account-controller.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/utils/yourServices.ts
test/unit/utils/yourServices.test.ts

- Services listed on account deletion page are displayed in alphabetical order even when there are both English titled and Welsh titled services in the list.
- When viewing the account deletion page in Welsh services listed with English titles have the attribute `lang="en"`.
- When viewing the account deletion page in Welsh and there are English titled services in the list then a message is displayed explaining why this is.
To improve the experience for users using the account deletion page in Welsh.
https://govukverify.atlassian.net/browse/OLH-2458

[OLH-2458] delete account services Welsh updates

---

src/components/add-mfa-method-app/add-mfa-method-app-controller.ts
src/components/add-mfa-method-app/tests/add-mfa-methods-app-controller.test.ts
src/utils/mfaClient/index.ts
test/unit/utils/mfaClient.test.ts

Fix a bug we found in staging where the API client tries to create new MFA methods as default. This is a mistake as users can only create backup methods - they'll always need to create a new one as a backup and then switch their backup and default.
I've also improved the logs we get when this request fails to make it easier to diagnose this problem in the future.
This fixes a bug which prevented users from adding a new MFA method.

OLH-2534: Create new MFA methods as backup 

---

deploy/template.yaml

Use Firewall Manager to manage the WAF in build and staging.
We've successfully tested in dev so we can simplify the template and make the tagging changes at the same time as we disassociate our custom ACL.
There is a risk of a few seconds downtime (of the WAF - our apps will stay up) between us removing our ACL, the tags being applied and Firewall Manager taking over. This has been investigate and accepted by security.
We're moving our WAF rules to a centrally managed solution so the security team have oversight.

OLH-2560: Use Firewall Manager in build and staging

---

.env.sample

Update `.env.sample` with the correct URL for the MFA method management stub API.

Update the MFA management base URL in .env.sample

---

src/app.constants.ts
src/components/add-mfa-method-app/add-mfa-method-app-controller.ts
src/components/add-mfa-method-app/add-mfa-method-app-routes.ts
src/components/add-mfa-method-app/tests/add-mfa-methods-app-controller.test.ts
src/components/add-mfa-method-sms/add-mfa-method-sms-controller.ts
src/components/add-mfa-method-sms/add-mfa-method-sms-routes.ts
src/components/add-mfa-method-sms/index.njk
src/components/add-mfa-method-sms/tests/add-mfa-method-sms-controller.test.ts
src/components/change-authenticator-app/tests/change-authenticator-app-controller.test.ts
src/components/change-default-method/tests/change-default-method-controller.test.ts
src/components/change-email/tests/change-email-controller.test.ts
src/components/change-password/tests/change-password-controller.test.ts
src/components/change-phone-number/tests/change-phone-number-controller.test.ts
src/components/choose-backup/index.njk
src/components/common/mfa/add-phone-number.njk
src/components/common/mfa/tests/index.test.ts
src/locales/en/translation.json
src/utils/state-machine.ts
test/unit/utils/state-machine.test.ts
test/utils/builders.ts

- Added back link to enter phone number screen which goes back to the screen for choosing a backup method
- Renamed `addMfaAppMethodGoBackGet` to `addMfaMethodGoBackGet` to make it more generic
- Changed path `/back-from-set-up-auth-app` to `/back-from-set-up-method` to make it more generic
- Renamed `addMfaAppMethodConfirmationGet` in `src/components/add-mfa-method-sms/add-mfa-method-sms-controller.ts` to `addMfaSmsMethodConfirmationGet`
- Fix to ensure supporting text shows on screen for choosing SMS as a backup method
- Make inputs correct width on enter phone number screen
- Show correct page title and heading on enter phone number screen when adding SMS as a backup method
- Text corrections for supporting text shown on enter phone number screen
- In the test request builder renamed …

[OLH-2135] MFA journey fixes post UCD review

---

src/components/switch-backup-method/index.njk
src/locales/en/translation.json

- Added 'Cancel and go back to Security' link to the switch MFA methods action screen
https://govukverify.atlassian.net/browse/OLH-2141

[OLH-2141] MFA journey 6 UCD review fixes

---

deploy/template.yaml

Update our Cloudfront distribution to call the new version of the headers function in all environments except production. I'll then let the dev platform team know and they can verify the function is being called.
Once we get the ok there, I'll release to prod.
There was an issue with some AWS accounts not being part of the correct Organisational Unit in Control Tower which meant the dev platform team had to deploy a new version of the headers function to update it with the new device intelligence requirements.
See the equivalent parameter in the [dev platform team's Cloudfront template](https://github.com/govuk-one-login/devplatform-deploy/blob/main/cloudfront-distribution/template.yaml#L22).

OLH-2557: Use the new headers function up to integration

---

deploy/template.yaml

Call the new headers function from our frontend Cloudfront in production. This means we can also get rid of the conditional check.
I've checked the data from integration and got the go-ahead from dev platform.
#2142

OLH-2557: Call the new headers function in production

---

deploy/template.yaml

Enable Firewall Manager in integration. 
This PR also updates the policy names for dev and production. The new policy in dev has all the same rules as the old one, but the name now matches all other environments. We also know what the name will be for production, so we can set it now even though we're not using it.
We're replacing our custom WAF rules with centrally managed ones. 
#2129 
#2130

OLH-2562: Use Firewall Manager in integration

---

src/utils/mfaClient/index.ts
src/utils/mfaClient/types.ts
test/unit/utils/mfaClient.test.ts

Correct the payload when creating or updating an SMS method.
According to the spec[^1] the OTP should be at the same level as the method type and phone number, not at the level above like we had it.
```yaml
CreateSmsMethod:
type: object
properties:
mfaMethodType:
type: string
enum:
- SMS
phoneNumber:
type: string
otp:
type: string
```
[^1]: https://github.com/govuk-one-login/openapi-specs/blob/main/auth/account-management-api/account-management-with-mfa-method-management.yaml#L359-L369
So the API calls work.

OLH-2534: Correct payload when creating or updating an SMS method

---

package-lock.json
package.json
src/components/change-email/index.njk
src/components/check-your-email/index.njk
src/components/check-your-phone/index.njk
src/components/common/mfa/add-auth-app.njk
src/components/common/mfa/add-phone-number.njk
src/components/common/show-password/macro.njk

Update the version of govuk-frontend from `5.7.0` to `5.9.0`. 
Form control components no longer require an ID attribute, and automatically use the value of the `name` parameter for their id. The `name` parameters have been removed from input components where the `id` and `name` had the same value, seeing as the `id` param is now redundant in those instances.
This is the most recent working version. 
The next big release is likely to be the brand update. It's sensible to bring our FE in line with the latest stable version of the package in anticipation of that.
Please sanity check the release notes from `5.7.0` to `5.9.0` to confirm there is nothing that has the potential to break functionality on account management frontend  https://github.com/alphagov/govuk-frontend/releases

BAU: Bump govuk-frontend to 5.9.0

---

package-lock.json
src/components/your-services/tests/your-services-controller.test.ts
src/config.ts

Update to the latest version of the RP registry and filter the lists of allowed accounts and services to exclude offboarded services.
We want to hide offboarded services from the service cards and on the 'delete your account' page, but not from the activity history.
The service cards and 'delete your account' pages both filter the list of services a user's accessed using the list of account and service RPs from the registry. The activity log doesn't do this filter - it just gets all the entries for that user from the table.
This means that updating the filter on these allow lists will stop offboarded services from appearing where we don't want them, but they'll still show and have the correct content in users' activity history.
https://github.com/govuk-one-login/di-account-management-rp-re …

OLH-2584: Offboard Connect Families to Support and Manage Family Support services

---

src/components/switch-backup-method/switch-backup-method-controller.ts
src/components/switch-backup-method/tests/change-default-method-controller.test.ts
src/utils/mfaClient/index.ts
src/utils/mfaClient/types.ts
test/unit/utils/mfaClient.test.ts

Change the payload when switching an MFA method to default.
NOTE: This will require a corresponding update to the validation logic in our stubs.
The Auth team have decided to update the required payload when switching an MFA mthod from backup to default. This reduces the number of fields and will make it easier for them to validate the request.
The new format is
```
PUT /{publicSubjectId}/{mfaIdentifier}
{
"mfaMethod": {
"priorityIdentifier": "DEFAULT"
}
}
```
[Example payload from the updated API spec](https://github.com/govuk-one-login/authentication-api/pull/6385/files#diff-2ac5c584bf7c5f5f231563c56e1a0e6dd0a48109b7c76cf5629cb3f5a2002fe3R411-R412)
[Stubs update PR](https://github.com/govuk-one-login/account-management-stubs/pull/460)

OLH-2592: Change the payload when switching an MFA method to default

---

deploy/template.yaml

Add `/v1` to the method management API base URL in staging
The latest change to the Auth team's API include a version number in the URL. Add this in staging so our frontend can still reach the API.
[See the planned update to the API spec.
](https://github.com/govuk-one-login/authentication-api/pull/6385/files#diff-2ac5c584bf7c5f5f231563c56e1a0e6dd0a48109b7c76cf5629cb3f5a2002fe3R69)

OLH-2592: Add `/v1` to the API base URL in staging

---

src/components/contact-govuk-one-login/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

When JavaScript is disabled the text on contact page has a list of links to browser vendor websites explaining how to enable JavaScript. These changes make it clear to the user that these links will open in a new tab.
So that users aren’t confused when they click a link and are taken to a new tab.
https://govukverify.atlassian.net/browse/OLH-2583

[OLH-2583] Contact page accessibility improvements when JavaScript is disabled

---

deploy/template.yaml

Rather than allowing everything in robots.txt it has been changed to only allow crawling of the contact page and things in the `public` and `assets` folders.
To try and get Google to display nicer search results for the contact page, which is the only page we want to be crawled and indexed.

Disallow everything except specific paths in robots.txt

---

src/components/add-mfa-method-sms/add-mfa-method-sms-routes.ts
src/components/change-default-method/change-default-method-routes.ts
src/components/change-phone-number/change-phone-number-routes.ts
src/components/change-phone-number/change-phone-number-validation.ts
src/components/change-phone-number/tests/change-phone-number-validation.test.ts
src/components/resend-phone-code/resend-phone-code-routes.ts
src/locales/en/translation.json
src/utils/phone-number.ts
src/utils/test/phone-number.test.ts

Adds validation to prevent the user from entering a phone number they're already using when they're adding/updating an SMS MFA method.
This required adding test coverage for `src/components/change-phone-number/tests/change-phone-number-validation.ts` to satisfy SonarCloud.
To ensure the user journeys match those required by the designs.
https://govukverify.atlassian.net/browse/OLH-2612

Don't allow user to use phone number which is already in use

---

post-deploy-tests/tests/features/@contact-govuk-one-login.feature

Disabled a post-deploy test which is failing in the build pipeline, with a comment to fix it later.
There is also a Jira ticket in the backlog to address this https://govukverify.atlassian.net/browse/OLH-2631.
To unblock the deployment pipeline.

Disable failing post-deploy test with comment to fix it later

---

deploy/template.yaml
src/app.ts

- Serve favicon.ico
- Revert robots.txt changes which were unsuccessful at fixing search results icon issue
To try and get the favicon to show in search results

Serve favicon.ico and revert unneeded robots.txt changes

---

src/components/add-mfa-method-sms/add-mfa-method-sms-controller.ts
src/components/add-mfa-method-sms/add-mfa-method-sms-routes.ts
src/components/add-mfa-method-sms/tests/add-mfa-method-sms-controller.test.ts
src/components/change-default-method/change-default-method-controllers.ts
src/components/change-default-method/change-default-method-routes.ts
src/components/change-phone-number/change-phone-number-controller.ts
src/components/change-phone-number/change-phone-number-routes.ts
src/components/change-phone-number/change-phone-number-validation.ts
src/components/change-phone-number/tests/change-phone-number-validation.test.ts
src/components/resend-phone-code/resend-phone-code-controller.ts
src/components/resend-phone-code/resend-phone-code-routes.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/utils/phone-number.ts
src/utils/test/phone-number.test.ts

Remove validation which checks if the user provided phone number is the same as any of their existing MFA phone numbers.
Rather than validating this in the frontend we will rely on receiving a 400 response with the error code `1044` when sending requests to `/send-otp-notification`.
https://govukverify.atlassian.net/browse/OLH-2652

OLH-2652: Don't validate MFA same phone number

---

deploy/template.yaml

Temporarily update the webchat URL for integration to point to the new prod webchat infrastructure. This is being done for testing purposes and should be reverted once webchat is confirmed to be working.
We've confirmed the dev and uat versions of the "new" webchat are working.
The next step in the testing plan is to test the production version in our integration environment.
The supplier have confirmed that integration has been allowlisted for use with their Prod environment. 
Check that the URL matches the one provided for prod on the description of [the ticket](https://govukverify.atlassian.net/browse/OLH-2628).
We should be able to perform a manual test once this commit makes it to integration. 
Once it's been confirmed to be working, this change should be reverted.

OLH-2628: Update webchat URL for integration

---

src/utils/present-activity-history.ts

`Array.sort()` sorts the original array in place and also returns a reference to the same array. Assigning this reference to a new variable can be confusing if we ever needed to do anything else with the original variable, as it implies that the original hasn't been sorted.
There's no issues with that in the case, but we can make our intentions clear by not assigning the result of `.sort()` and returning the original variable.
We already have a unit test to check this function does sort the array.
This addresses [a code smell in Sonar](https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&types=CODE_SMELL&id=di-account-management-frontend).

OLH-2680: Make it clear array is sorted in place

---

src/app.constants.ts
src/app.ts
src/components/delete-account/delete-account-controller.ts
src/components/delete-account/tests/delete-account-integration.test.ts
src/components/enter-password/enter-password-controller.ts
src/components/enter-password/tests/enter-password-controller.test.ts
src/components/enter-password/tests/enter-password-integration.test.ts
src/components/logout-redirect/logout-redirect-controller.ts
src/components/logout-redirect/logout-redirect-routes.ts
src/components/logout-redirect/tests/logout-redirect-controller.test.ts
src/components/logout/logout-controller.ts
src/utils/logout.ts

[OLH-2664] Create a logout return route to handle redirects after calling OIDC end session
Created a new logout-redirect route which the oidc will redirect to. We will then use the state to redirect the user somewhere in home. Currently supported redirects are: temp suspended, perm blocked, account deleted, and default
Adding post logout redirects requires support from another team which is adding overhead. With this implementation we will only require one url and can use the state value to redirect within home. The state is validated our side and defaults to sign out.
Tested locally with temp suspended, perm suspended, account deletion and normal logout.
[OLH-2664]: https://govukverify.atlassian.net/browse/OLH-2664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …

OLH-2664: create a logout return route to handle redirects after calling OIDC end session

---

src/services/event-service.ts

Replaces `||` with `??`
To fix code smell warnings in Sonar
https://govukverify.atlassian.net/browse/OLH-2671

OLH-2671: replace || with ?? to fix code smell warnings

---

src/components/signed-out/signed-out-controller.ts
src/components/signed-out/tests/signed-out-controller.test.ts

[OLH 2707] Signed out page should return 200 status code
Signed-Out page returns status code 200 instead of 401. 
Performance tests were failing as they were expecting status 200 but got 401. This was due to the logout redirect changes where we have stopped using auths sign out page.

OLH 2707: Signed out page should return 200 status code

---

src/middleware/mfa-method-middleware.ts
test/unit/middleware/mfa-method-middleware.test.ts

[OLH-2328] resolve SelectMFAMethod error logs
In production the env var for method management is set to a empty string, this was being read and then changed into a URL. As it threw an error due to invalid URL, a error message was logged. Currently we don't have method management in production so this is valid, but we don't need the error message. This resolves this issue and now also checks if there is a valid URL passed in and warns us otherwise.
To reduce the non critical errors we are logging.
[OLH-2328]: https://govukverify.atlassian.net/browse/OLH-2328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2328: Resolve error message due to invalid MFA method URL 

---

src/utils/strings.ts

Use regex literal not RegExp constructor
To fix Sonar code smell warning
https://govukverify.atlassian.net/browse/OLH-2679

OLH-2679: use regex literal not RegExp constructor

---

src/middleware/outbound-contact-us-links-middleware.ts
src/middleware/update-session-middleware.ts
test/unit/middleware/outbound-contact-us-links-middleware.test.ts
test/unit/middleware/update-session-middleware.test.ts

[OLH-2328] Adjust fromURL logic
- Adjusted from URL logic to keep the original fromURL to prevent infinite depth fromURLs
- Changed the logger.warn for invalid fromURLs to include the invalid URL
- Reduce bot traffic which is spamming the contact us page due to different URLs caused by fromURLs
- Better understand why we have a significant number of invalid URL errors in production
Are there any issues with logging the from URL?
[OLH-2328]: https://govukverify.atlassian.net/browse/OLH-2328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2328: Keep original from url and log invalid from URL

---

post-deploy-tests/tests/features/@contact-govuk-one-login.feature

Reenables previously failing post-deploy tests to see if they now pass.
https://govukverify.atlassian.net/browse/OLH-2631

OLH-2631: Reenable previously failing post-deploy tests

---

post-deploy-tests/tests/features/@contact-govuk-one-login.feature

Reverts govuk-one-login/di-account-management-frontend#2232 as the tests still failed in the build pipeline

Revert "OLH-2631: Reenable previously failing post-deploy tests"

---

@types/express/index.d.ts
src/config/i18next.ts
src/config/nunjucks.ts
src/utils/safeTranslate.ts
test/unit/config/nunjucks.test.ts
test/unit/utils/safeTranslate.test.ts

[OLH-2721] Check if language selected is supported or fallback to en
Check language selection matches our supported options (en, cy) if not fallback to cy.
Some users are passing a lng value of "" which is interpreted as an unknown language. As this value is not nullish it is not picked up by ?? and is passed to safeTranslate.  We could have changed it to || but with this change we now check against our list of supported languages.
https://govukverify.atlassian.net/browse/OLH-2721
[OLH-2721]: https://govukverify.atlassian.net/browse/OLH-2721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2721: Check if language selected is supported or fallback to en

---

post-deploy-tests/tests/features/@contact-govuk-one-login.feature

Previously skipped post-deploy tests have been enabled to see if they pass now that the webchat domain has been allowlisted in the network firewall.
https://govukverify.atlassian.net/browse/OLH-2631

OLH-2631: enable skipped post-deploy tests

---

src/app.ts
src/components/add-mfa-method-sms/add-mfa-method-sms-controller.ts
src/components/change-default-method/change-default-method-controllers.ts
src/components/change-default-method/change-default-method-routes.ts
src/components/change-email/change-email-controller.ts
src/components/change-password/change-password-controller.ts
src/components/change-phone-number/change-phone-number-controller.ts
src/components/check-your-email/check-your-email-controller.ts
src/components/check-your-phone/check-your-phone-controller.ts
src/components/check-your-phone/check-your-phone-routes.ts
src/components/choose-backup/choose-backup-controller.ts
src/components/choose-backup/choose-backup-routes.ts
src/components/delete-account/delete-account-controller.ts
src/components/delete-mfa-method/delete-mfa-method-routes.ts
src/components/enter-password/enter-password-controller.ts
src/components/enter-password/tests/enter-password-integration.test.ts
src/components/report-suspicious-activity/report-suspicious-activity-controller.ts
src/components/resend-email-code/resend-email-code-controller.ts
src/components/resend-phone-code/resend-phone-code-controller.ts
src/components/security/security-controller.ts
src/components/security/security-routes.ts
src/components/switch-backup-method/switch-backup-method-routes.ts
src/components/update-confirmation/update-confirmation-controller.ts
src/components/update-confirmation/update-confirmation-routes.ts
src/config.ts
src/middleware/mfa-method-middleware.ts
src/middleware/mfa-methods-legacy.ts
src/utils/opl.ts
test/unit/middleware/mfa-method-middleware.test.ts

Makes it possible to test MFA in production. When we're ready to test MFA in production then the production environment variables `SUPPORT_METHOD_MANAGEMENT`, `SUPPORT_CHANGE_MFA` and `SUPPORT_ADD_BACKUP_MFA` should have their value set to `qa`.
MFA will still not be available at this point but if you set a cookie in dev tools called `enable_mfa_for_qa` with the value `1` then MFA will become enabled.
https://govukverify.atlassian.net/browse/OLH-2715

OLH-2715: Enable testing of MFA in production

---

src/components/oidc-callback/call-back-controller.ts
src/components/oidc-callback/tests/callback-controller.test.ts
src/utils/session-store.ts

[OLH-2722] Handle Auth Callback Errors
Redirect the user to /session expired if the auth callback contains an error 
We noticed a few error on the oidc.callback end point as the query params contained an error that we did not handle e.g.  /auth/callback?error=server_error&error_description=Unexpected+server+error&state=xxxx
On auth side we found that as the user was coming from another RP to home there were multiple requests to recreate the session in a split second causing miss match of the state param. This is happening to other's as well, not just home. Ultimately this request returned a server error that is returned to home.
In this instance we want to redirect the user to sign in again to ensure they get valid tokens. 
https://govukverify.atlassian.net/jira/software/c/projects/OLH/boa …

OLH-2722: Handle all auth callback errors

---

src/components/change-default-method/index.njk
src/components/common/confirmation-page/confirmation.njk

Use `govukButton` macro for link buttons to ensure they have the role `button`.
To improve accessibility. When a link is styled as a button the user is likely to expect to be able to "click" the link using both the enter and space keys as is the case with HTML button elements. Without the `button` role links can only be "clicked" with the enter key. Adding the `button` role makes the link clickable with the space key too.
https://govukverify.atlassian.net/browse/OLH-2796

OLH-2796: add button role to links styled as buttons

---

src/components/check-your-email/types.ts
src/components/resend-phone-code/resend-phone-code-controller.ts
src/components/resend-phone-code/tests/resend-phone-code-controller.test.ts
src/components/resend-phone-code/tests/resend-phone-code-integration.test.ts

- Check intent before redirecting user
- Throw a badRequestError if a unknown intent is passed
Prevent user controlled actions controlling the intent

OLH-2809: prevent res redirect on intent from user passed variable

---

src/components/search-services/index.njk
src/components/search-services/search-services-controller.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Add "Clear search" link to "Services you can use with GOV.UK One Login" page.
Update page title to reflect current search term.
Add missing Welsh translations for searchable list
Change input field type from `search` to `text` as a quick fix for the inline "x" which is appended to the field in some browsers – this can also be done with CSS but I figured changing the type of field would be easier and would avoid increasing CSS payload, with minimal consequence:
- when AT is used, the form still appears in the landmarks list as a `search` landmark and functions the same way
- there is a subtle difference in the way the field is announced when using screen readers ("text" vs "search"). However the purpose of the field is clear from the label/context
- there are slight differences in mobile …

Olh 2506: searchable list updates

---

src/locales/cy/translation.json

Fixed Welsh translations on activity history page. Mel flagged up that some of the content wasn't looking quite right.
Plus: added missing translation for `securityNoticeContentAlt`.
Please check that the new additions match the content in the description of the ticket (and in Mel's comment lower down)

OLH-2792: activity history Welsh language tweaks

---

src/components/common/layout/base.njk

I was investigating something else and accidentally realised the `international-phone` script was no longer loading on the "Enter your new mobile phone number" template.
I traced this back to the fact that the scripts block in `base.njk` went missing, so the script was no longer being appended to `bodyEnd`. 
That being said it might be worth reassessing our use of `scripts` seeing as other than webchat, `international-phone` might be the only page-specific script remaining.
On the `/change-phone-number page`, when "I do not have a UK mobile number" is selected, the UK mobile phone number input box should be deactivated. This was a request from interaction design. 
This stopped working as the script was missing, but it should work again now. 
Verify the behaviour described under **Why did …

BAU: add missing script block

---

deploy/template.yaml

Fix ECS Task Log Group's Subscription Filter's Filter pattern.
ECS Task Log Group's Subscription Filter's Filter pattern.
ECS Task logs are not being propagated to CSLS’s Splunk endpoint since we updated the SubcriptionFilter’s FilterPattern as the SubscriptionFilter filter pattern was incorrect.
[OLH-2329: Implement powertools metric logging](https://github.com/govuk-one-login/di-account-management-frontend/pull/2294)
Tested Filter expression in CloudWatch Log Group called [/ecs/account-mgmt-frontend/server](https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#logsV2:log-groups/log-group/$252Fecs$252Faccount-mgmt-frontend$252Fserver)
**Log group without any filter**
**Log group with new filter applied - all EMF events disappear**

OLH-2880: updated subsciption filter to exclude EMF logs

---

src/components/change-default-method/change-default-method-routes.ts
src/components/check-your-phone/check-your-phone-routes.ts
src/components/choose-backup/choose-backup-routes.ts
src/components/delete-mfa-method/delete-mfa-method-routes.ts
src/components/security/security-routes.ts
src/components/security/tests/security-integration.test.ts
src/components/switch-backup-method/switch-backup-method-routes.ts
src/components/update-confirmation/update-confirmation-routes.ts

Call refresh token middleware before middleware to fetch MFA methods.
To ensure the user has a valid token when fetching MFA methods.

OLH-2799: fix forward refresh token middleware [skip canary]

---

sonar-project.properties
src/components/oidc-callback/call-back-controller.ts
src/components/oidc-callback/call-back-utils.ts
src/components/oidc-callback/tests/callback-utils.test.ts

Resolve access denied error that is being logged
remove double wrapping for async handler on all controllers
Ensure all sampled OIDC errors are handled and users are sent to sign-in
So that we OIDC errors are handled correctly and to remove unnecessary error messages from the log
https://govukverify.atlassian.net/browse/OLH-2720
Deploy to dev and ensure core functionalities are not broken

OLH-2720 Resolve access denied error that is being logged

---

src/components/oidc-callback/call-back-controller.ts
src/components/oidc-callback/call-back-utils.ts
src/components/oidc-callback/tests/callback-controller.test.ts
src/components/oidc-callback/tests/callback-utils.test.ts

OLH-2900 Resolve TypeErrors being raised in OIDC callback controller
Check for null or undefined session
To resolve two errors found in prod
- Global async error handler : TypeError: Cannot read properties of undefined (reading 'state')	23	10.648%	
- Global async error handler : TypeError: Cannot read properties of undefined (reading 'currentURL')
https://govukverify.atlassian.net/browse/OLH-2900

OLH-2900 Resolve TypeErrors being raised in OIDC callback controller

---

src/utils/oidc.ts
test/unit/utils/oidc.test.ts

Remove error logging when token refresh fails. It is a legitimate error which can occur when the user's token has expired. We catch the error and the user is redirected to sign in so there is no need to log the error. We also have a metric `refreshTokenError` which we can use to see volumes of the error occuring.

OLH-2898: remove error logging

---

deploy/template.yaml

A while ago the webchat source URL for integration was updated to the new production URL. This was done in order to test the new infrastructure in integration first, before proceeding to prod.
The prod script running in integration is attempting calls to the prod version of websocket, however the integration CSP is currently configured to only allow calls to the integration version of the websocket. 
This updates the relevant env variable in order to enable connection to the prod websocket on our integration env. This (along with the aforementioned Webchat src URL change) should be reverted as soon as testing is complete.
To allow testing of prod webchat on integration (for real this time)
Verify that only the integration config has been changed.

OLH-2628: Update ML websocket addr for integration env

---

src/utils/global-try-catch.ts

OLH-2905 Resolve missing stack trace in global try catch
Fix logging to include stak trace
So that stack trace is shown the logs.

OLH-2905 Resolve missing stack trace in global try catch

---

src/app.constants.ts
src/handlers/internal-server-error-handler.ts
src/utils/http.ts
src/utils/oidc.ts
test/unit/utils/oidc.test.ts

Don't throw an error when refreshing the token fails, just log the user out.
There's no need to throw an error as we're not considering it an error and the user won't see an error page.

OLH-2878: don't error on refresh token fail

---

src/components/oidc-callback/call-back-controller.ts
src/components/oidc-callback/call-back-utils.ts
src/components/oidc-callback/tests/callback-utils.test.ts
src/utils/global-try-catch.ts
test/utils/global-try-catch.test.ts

OLH-2905 Resolve missing stack trace in global try catch
Fix logging to include stak trace
So that stack trace is shown the logs.

OLH-2905 Resolve missing stack trace in global try catch -2

---

src/components/search-services/search-services-controller.ts
src/components/search-services/tests/search-services-controller.test.ts

When searching RPs match against the `startText` field not the `header` field.
To ensure the search is performed against the same string as is shown in the searchable list.

OLH-2921: perform search against searchText not header

---

src/components/add-mfa-method-sms/add-mfa-method-sms-controller.ts
src/components/add-mfa-method-sms/tests/add-mfa-method-sms-controller.test.ts

Delete the `changePhoneNumber` not `addBackup` user state after adding an SMS backup in order to stop `Error:Could not change phone number. Status code: 400, API error code: 1001, API error message: Request is missing parameters` errors.
A separate ticket will be created to investigate refactoring the way we use state machines to make them easier to understand and change.

OLH-2896: delete correct user state after adding SMS backup

---

src/components/switch-backup-method/switch-backup-method-controller.ts
src/components/switch-backup-method/switch-backup-method-routes.ts
src/components/switch-backup-method/tests/switch-backup-method-controller.test.ts
src/middleware/log-error-middleware.ts

If an error occurred in the switch MFA methods POST handler the page would just hang. These changes ensure that the error bubbles up to the `log-error-middleware` for logging. The user will also now see the error page. Unnecessary use of  `globalTryCatchAsync` has also been removed from the switch MFA methods routes and metrics have been added to `log-error-middleware`.

OLH-2883: improved handling of switch MFA methods errors

---

src/app.constants.ts
src/app.ts
src/config.ts

Setting `NODE_ENV` to anything other than `production` is considered an anti-pattern and is discouraged[^1].
This is to prevent issues where we write code that behaves differently in our tests vs. when deployed.
That means we should also not use this variable to determine what environment we're currently in. This replaces any use of `getNodeEnv()` with the more appropriate `getAppEnv()` and removes `getNodeEnv()`.
I've also updated the `ENVIRONMENT_NAME` constant to:
1. a const enum, in line with our other recent changes (see the `EventName` enum)
2. actually reflect the environment names, not the NODE_ENV options
[^1]: https://nodejs.org/en/learn/getting-started/nodejs-the-difference-between-development-and-production
This will make it easier for us to understand the intent of switches …

BAU: Only use `APP_ENV` to determine environment

---

src/components/check-your-phone/check-your-phone-controller.ts
src/components/check-your-phone/tests/check-your-phone-controller.test.ts

Check that `newPhoneNumber` is actually defined in the session before proceeding in the `check your phone` `POST` controller.
To eliminate errors where we try to add an SMS backup MFA method but submit `undefined` as the phone number.

OLH-2966: check new phone number is defined

---

integration-tests/README.md

- Remove redundant text about step scoping
- Mention the need to create a `.env.integration-tests` file

OLH-2819: integration tests README updates

---

src/components/activity-history/tests/activity-history-controller.test.ts
src/components/security/tests/security-controller.test.ts

Stub environment variables in tests
I spotted that these tests were failing when I made some other unrelated changes, and realised that they were using the values from my `.env` file.
I've tried to look for other examples and didn't find any but I may have missed some.

BAU: Stub environment variables in tests

---

src/app.ts
src/components/choose-backup/choose-backup-controller.ts
src/middleware/monkey-patch-redirect-to-save-session-middleware.ts
test/unit/middleware/monkey-patch-redirect-to-save-session-middleware.test.ts

- Removes unnecessary `res.end` call which was preventing redirect headers from being written to the response
- Reinstates the redirect monkey patch middleware
- Updates the redirect monkey patching logic to only redirect if headers have not already been sent, and to add more logging
Monkey-patch res.redirect to defer calling it until after the session has been saved to prevent race conditions where the user follows a redirect response and the subsequent request reads the session before the changes to the session made in the previous request have been saved.
The removal of `res.end` and checking whether headers have already been sent ensure that the monkey patching middleware won't try to write headers when they've already been sent, which was causing fatal exceptions.

OLH-3076: redirect monkey patch improvements

---

src/services/event-service.test.ts
src/services/event-service.ts
src/services/types.ts

Moves the `phone` property from the `extensions` object and into the `user` object in the following audit events:
AUTH_MFA_METHOD_ADD_STARTED
AUTH_MFA_METHOD_SWITCH_STARTED
AUTH_MFA_METHOD_DELETE_STARTED
So that the phone number is in the correct location as per the event specs and to prevent leaking of PII.
Event specs:
https://event-catalogue.internal.account.gov.uk/events/AUTH_MFA_METHOD_ADD_STARTED/
https://event-catalogue.internal.account.gov.uk/events/AUTH_MFA_METHOD_SWITCH_STARTED/
https://event-catalogue.internal.account.gov.uk/events/AUTH_MFA_METHOD_DELETE_STARTED/

OLH-3086: move phone number in audit events

---

src/components/activity-history/activity-history-routes.ts
src/components/activity-history/tests/activity-history-integration.test.ts
src/components/security/index.njk
src/components/security/security-controller.ts
src/components/security/tests/security-controller.test.ts
src/components/security/tests/security-integration.test.ts
src/middleware/check-allowed-services-list.ts
test/unit/middleware/check-allowed-services-list.test.ts

Show the activity log to all users by removing the middleware check for an allowed service in the user's history and the conditional from the security page. 
I've left in the similar check for the report suspicious activity journey as it's possible we want to use the same mechanism for a slow rollout of that feature in the future.
We're not going to turn this feature off again, so we can remove all the conditional checks for an allowed service in a user's history. This will save us several database calls and make it easier to work in the frontend.
I've run the app locally and checked the activity history shows up for users who don't have any history. The simplest way to do this is to sign in as the performance test user as that gets a unique user ID each time, so can't have any sign in …

OLH-3048: Show the activity log to all users

---

package-lock.json
package.json

This version introduces several minor bug fixes as per the [release notes](https://github.com/alphagov/govuk-frontend/releases). 
The only change that is relevant to us is https://github.com/alphagov/govuk-frontend/pull/6184

BAU: Bump govuk-frontend to most recent version

---

src/components/change-email/index.njk
src/components/change-password/index.njk
src/components/check-your-email/index.njk
src/components/check-your-phone/index.njk
src/components/choose-backup/index.njk
src/components/common/layout/base-page.njk
src/components/common/mfa/add-auth-app.njk
src/components/common/mfa/add-phone-number.njk
src/components/delete-account/index.njk
src/components/enter-password/index.njk

Move `errorSummary.njk` from the individual `index.njk` templates into the shared `base-page.njk` layout file.
`errorSummary.njk` only displays an error if the relevant locals ([primarily, `errorList`](https://github.com/govuk-one-login/di-account-management-frontend/blob/main/src/components/common/errors/errorSummary.njk#L5)) exist within the context of the page.
Therefore moving repeated calls to the `errorSummary` partial into the shared `base-page.njk` should be a relatively risk free operation.
Nothing should have changed visually speaking.
Reduce repetition
Visit any pages that do not contain input fields (for ex contact page, your services, security), and check that error messages do not appear. 
Visit pages that do contain input fields, and check that error messages do appear if …

BAU: Move error summary partial into base-page.njk

---

docker-compose.yml

Set `DYNAMODB_REMOVE_EXPIRED_ITEMS` to `1` when starting LocalStack so that expired sessions are removed from the database as is the case in AWS.
Set `DYNAMODB_IN_MEMORY` to `1` when starting LocalStack so that the database is just held in memory while the container is running. This improves performance significantly and there is no need for changes to be persisted to disk.

BAU: LocalStack DynamoDB tweaks

---

.github/workflows/integration-tests.yml

Update triggers for the integration tests GitHub Action so that it runs for pull requests and also prior to a group of changes being merged via the merge queue. By running the integration tests in the merge queue it helps to ensure that changes being merged into `main` haven't caused regressions.

BAU: change integration test action triggers

---

deploy/template.yaml

OLH-3047 Add ALB Request count scaling alarm and policies
Added metric and alarms for when requests per minute on an ALB target is above a given threshold
Added scale out an din policy when the alarms are triggered
So that we can pro-actively scale out based on an increased request count
Ensure deployment to dev is successful
Verify the scaling policy on the dev environment by looking at the auto scaling configuration in the AWS console

OLH-3047 Add request count alarms and policy

---

deploy/template.yaml

Increase the threshold on the traffic spike alarm so that it will only alarm if the last 5 minutes have 2500 or more requests than the preceding 5 minutes.
Hopefully this will mean the alarm only goes off for a 'real' traffic spike.
The alarm was constantly triggering on our normal traffic levels and wasn't useful. I ran the below query in Splunk to see the 5 minute traffic level difference over the last 72 hours. It's often higher than 1000 (as I expected with the alarm triggering) but it never goes above 2500.
```
index=gds_di_production source=*026991849909*
sourcetype="aws:cloudwatchlogs:api-access-logs"
"home.account.gov.uk" |
bucket _time span=5m |
stats count by _time |
delta count |
where isnotnull(count)
```
Blue is the requests per 5 minutes, and pink is the difference to the …

BAU: Increase traffic spike alarm threshold to 2500
